--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [1/2-] 2780.23 (21) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 586.0 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11667 (23)
PL2/PK =  8.16E-4 (22)
PM1/PK =  0.01850 (8)
PM2/PK =  1.246E-4 (37)
PN1/PK =  0.001029 (17)

L/K =  0.11749 (25)
M/K =  0.01863 (8)
N/K =  0.001029 (17)


------------------------------
Relative capture probabilities

PK  =  0.87939 (27)
PL1 =  0.10260 (17)
PL2 =  7.18E-4 (19)
PM1 =  0.01627 (6)
PM2 =  1.095E-4 (32)
PN1 =  9.05E-4 (15)

K =  0.87939 (27)
L =  0.10332 (19)
M =  0.01638 (7)
N =  9.05E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.0298 (21) %


---------------------
Capture probabilities

PK  =  0.87939 (27)
PL1  =  0.10260 (17)
PL2  =  7.18E-4 (19)
PM1  =  0.01627 (6)
PM2  =  1.095E-4 (32)
PN1  =  9.05E-4 (15)

K =  0.87939 (27)
L =  0.10332 (19)
M =  0.01638 (7)
N =  9.05E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 5.97

Log ft value (ec)    =  5.967 (32)
with log f           =  -0.921 (10)
and log partial T1/2 =  6.888 (31)

