--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [1/2-] 2888.90 (40) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 477.3 (16) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11739 (23)
PL2/PK =  8.20E-4 (22)
PM1/PK =  0.01863 (8)
PM2/PK =  1.252E-4 (37)
PN1/PK =  0.001036 (17)

L/K =  0.11821 (25)
M/K =  0.01876 (8)
N/K =  0.001036 (17)


------------------------------
Relative capture probabilities

PK  =  0.87873 (27)
PL1 =  0.10315 (17)
PL2 =  7.21E-4 (19)
PM1 =  0.01637 (6)
PM2 =  1.100E-4 (32)
PN1 =  9.11E-4 (15)

K =  0.87873 (27)
L =  0.10388 (19)
M =  0.01648 (7)
N =  9.11E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.0104 (14) %


---------------------
Capture probabilities

PK  =  0.87873 (27)
PL1  =  0.10315 (17)
PL2  =  7.21E-4 (19)
PM1  =  0.01637 (6)
PM2  =  1.100E-4 (32)
PN1  =  9.11E-4 (15)

K =  0.87873 (27)
L =  0.10388 (19)
M =  0.01648 (7)
N =  9.11E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 6.24

Log ft value (ec)    =  6.24 (6)
with log f           =  -1.102 (11)
and log partial T1/2 =  7.34 (6)

