--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [3/2-] 2012.92 (11) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 1353.3 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11492 (22)
PL2/PK =  8.13E-4 (21)
PM1/PK =  0.01819 (7)
PM2/PK =  1.238E-4 (36)
PN1/PK =  0.001012 (17)

L/K =  0.11573 (24)
M/K =  0.01832 (8)
N/K =  0.001012 (17)


------------------------------
Relative capture probabilities

PK  =  0.88101 (26)
PL1 =  0.10124 (16)
PL2 =  7.16E-4 (19)
PM1 =  0.01603 (6)
PM2 =  1.091E-4 (32)
PN1 =  8.91E-4 (15)

K =  0.88101 (26)
L =  0.10196 (18)
M =  0.01614 (6)
N =  8.91E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  28.9 (10)
L1/b+ =  3.32 (11)
L2/b+ =  0.0235 (6)
M1/b+ =  0.526 (16)
M2/b+ =  0.00358 (10)
N1/b+ =  0.0292 (6)

K/b+ =  28.9 (10)
L/b+ =  3.35 (11)
M/b+ =  0.529 (16)
N/b+ =  0.0292 (6)

EC/b+ =  32.8 (11)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.013390 (30) %   Iec =   0.01300 (30) %   Ib+ =   3.90E-4 (20) %
Iec      =   0.01300 (30) % (input data kept)
Ib+      =   3.90E-4 (20) % (input data kept)
Iec tot. =   0.01339 (30) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8550 (9)
PL1  =  0.09825 (19)
PL2  =  6.95E-4 (18)
PM1  =  0.01555 (6)
PM2  =  1.059E-4 (31)
PN1  =  8.65E-4 (14)

K =  0.8550 (9)
L =  0.09894 (20)
M =  0.01566 (6)
N =  8.65E-4 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.063

Log ft value (ec)    =  7.061 (13)
with log f           =  -0.186 (9)
and log partial T1/2 =  7.248 (10)

