--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [5/2-] 2535.83 (7) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 830.4 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11576 (22)
PL2/PK =  8.13E-4 (22)
PM1/PK =  0.01834 (8)
PM2/PK =  1.239E-4 (37)
PN1/PK =  0.001020 (17)

L/K =  0.11657 (24)
M/K =  0.01846 (8)
N/K =  0.001020 (17)


------------------------------
Relative capture probabilities

PK  =  0.88024 (26)
PL1 =  0.10189 (16)
PL2 =  7.15E-4 (19)
PM1 =  0.01614 (6)
PM2 =  1.091E-4 (32)
PN1 =  8.98E-4 (15)

K =  0.88024 (26)
L =  0.10261 (18)
M =  0.01625 (6)
N =  8.98E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.261 (14) %


---------------------
Capture probabilities

PK  =  0.88024 (26)
PL1  =  0.10189 (16)
PL2  =  7.15E-4 (19)
PM1  =  0.01614 (6)
PM2  =  1.091E-4 (32)
PN1  =  8.98E-4 (15)

K =  0.88024 (26)
L =  0.10261 (18)
M =  0.01625 (6)
N =  8.98E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 5.33

Log ft value (ec)    =  5.331 (25)
with log f           =  -0.614 (9)
and log partial T1/2 =  5.945 (23)

