--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [3/2-] 2808.10 (8) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 558.1 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11683 (23)
PL2/PK =  8.17E-4 (22)
PM1/PK =  0.01853 (8)
PM2/PK =  1.247E-4 (37)
PN1/PK =  0.001031 (17)

L/K =  0.11765 (25)
M/K =  0.01866 (8)
N/K =  0.001031 (17)


------------------------------
Relative capture probabilities

PK  =  0.87925 (27)
PL1 =  0.10272 (17)
PL2 =  7.18E-4 (19)
PM1 =  0.01629 (6)
PM2 =  1.096E-4 (32)
PN1 =  9.06E-4 (15)

K =  0.87925 (27)
L =  0.10344 (19)
M =  0.01640 (7)
N =  9.06E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.0052 (10) %


---------------------
Capture probabilities

PK  =  0.87925 (27)
PL1  =  0.10272 (17)
PL2  =  7.18E-4 (19)
PM1  =  0.01629 (6)
PM2  =  1.096E-4 (32)
PN1  =  9.06E-4 (15)

K =  0.87925 (27)
L =  0.10344 (19)
M =  0.01640 (7)
N =  9.06E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 6.68

Log ft value (ec)    =  6.68 (8)
with log f           =  -0.964 (10)
and log partial T1/2 =  7.65 (8)

