--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [5/2-] 1412.160 (40) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 1954.0 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11451 (21)
PL2/PK =  8.17E-4 (21)
PM1/PK =  0.01812 (7)
PM2/PK =  1.244E-4 (36)
PN1/PK =  0.001008 (17)

L/K =  0.11533 (24)
M/K =  0.01824 (8)
N/K =  0.001008 (17)


------------------------------
Relative capture probabilities

PK  =  0.88138 (26)
PL1 =  0.10093 (16)
PL2 =  7.20E-4 (19)
PM1 =  0.01597 (6)
PM2 =  1.096E-4 (31)
PN1 =  8.88E-4 (15)

K =  0.88138 (26)
L =  0.10165 (18)
M =  0.01608 (6)
N =  8.88E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  0.753 (17)
L1/b+ =  0.0862 (18)
L2/b+ =  6.15E-4 (8)
M1/b+ =  0.01364 (26)
M2/b+ =  9.36E-5 (15)
N1/b+ =  7.58E-4 (5)

K/b+ =  0.753 (17)
L/b+ =  0.0868 (18)
M/b+ =  0.01373 (26)
N/b+ =  7.58E-4 (5)

EC/b+ =  0.854 (19)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.910 (28) %   Iec =   0.420 (20) %   Ib+ =   0.490 (20) %
Iec      =   0.420 (20) % (input data kept)
Ib+      =   0.490 (20) % (input data kept)
Iec tot. =   0.910 (28) % (input data kept)


---------------------
Capture probabilities

PK  =  0.406 (5)
PL1  =  0.0465 (6)
PL2  =  3.32E-4 (10)
PM1  =  0.00736 (9)
PM2  =  5.05E-5 (16)
PN1  =  4.09E-4 (8)

K =  0.406 (5)
L =  0.0468 (6)
M =  0.00741 (10)
N =  4.09E-4 (8)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.87

Log ft value (ec)    =  5.873 (22)
with log f           =  0.135 (8)
and log partial T1/2 =  5.738 (21)

