--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [1/2-] 2062.45 (8) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 1303.8 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11497 (22)
PL2/PK =  8.12E-4 (21)
PM1/PK =  0.01820 (7)
PM2/PK =  1.238E-4 (36)
PN1/PK =  0.001012 (17)

L/K =  0.11578 (24)
M/K =  0.01832 (8)
N/K =  0.001012 (17)


------------------------------
Relative capture probabilities

PK  =  0.88097 (26)
PL1 =  0.10128 (16)
PL2 =  7.16E-4 (19)
PM1 =  0.01603 (6)
PM2 =  1.091E-4 (32)
PN1 =  8.92E-4 (15)

K =  0.88097 (26)
L =  0.10200 (18)
M =  0.01614 (6)
N =  8.92E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  53.6 (21)
L1/b+ =  6.16 (23)
L2/b+ =  0.0435 (13)
M1/b+ =  0.975 (34)
M2/b+ =  0.00663 (21)
N1/b+ =  0.0542 (12)

K/b+ =  53.6 (21)
L/b+ =  6.20 (23)
M/b+ =  0.982 (34)
N/b+ =  0.0542 (12)

EC/b+ =  60.8 (23)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.156 (13) %   Iec =   0.153 (13) %   Ib+ =   0.00250 (20) %
Iec      =   0.153 (13) % (input data kept)
Ib+      =   0.00250 (20) % (input data kept)
Iec tot. =   0.156 (13) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8667 (6)
PL1  =  0.09964 (17)
PL2  =  7.04E-4 (18)
PM1  =  0.01578 (6)
PM2  =  1.073E-4 (31)
PN1  =  8.77E-4 (14)

K =  0.8667 (6)
L =  0.10035 (19)
M =  0.01588 (6)
N =  8.77E-4 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.96

Log ft value (ec)    =  5.958 (38)
with log f           =  -0.219 (9)
and log partial T1/2 =  6.177 (37)

