--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [5/2-] 2336.54 (12) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 1029.7 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11533 (22)
PL2/PK =  8.12E-4 (22)
PM1/PK =  0.01827 (7)
PM2/PK =  1.237E-4 (36)
PN1/PK =  0.001016 (17)

L/K =  0.11615 (24)
M/K =  0.01839 (8)
N/K =  0.001016 (17)


------------------------------
Relative capture probabilities

PK  =  0.88063 (26)
PL1 =  0.10157 (16)
PL2 =  7.15E-4 (19)
PM1 =  0.01609 (6)
PM2 =  1.090E-4 (32)
PN1 =  8.94E-4 (15)

K =  0.88063 (26)
L =  0.10228 (18)
M =  0.01619 (6)
N =  8.94E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  1.2E9 (26)
L1/b+ =  1.4E8 (30)
L2/b+ =  1.0E6 (21)
M1/b+ =  2.2E7 (48)
M2/b+ =  1.5E5 (33)
N1/b+ =  1.2E6 (26)

K/b+ =  1.2E9 (26)
L/b+ =  1.4E8 (30)
M/b+ =  2.2E7 (48)
N/b+ =  1.2E6 (26)

EC/b+ =  1.4E9 (30)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.141 (9) %   Iec =   0.141 (9) %   Ib+ =   0. %
Iec      =   0.141 (9) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.141 (9) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88063 (26)
PL1  =  0.10157 (16)
PL2  =  7.15E-4 (19)
PM1  =  0.01609 (6)
PM2  =  1.090E-4 (32)
PN1  =  8.94E-4 (15)

K =  0.88063 (26)
L =  0.10228 (18)
M =  0.01619 (6)
N =  8.94E-4 (15)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.79

Log ft value (ec)    =  5.787 (29)
with log f           =  -0.426 (9)
and log partial T1/2 =  6.213 (28)

