--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [1/2-] 669.930 (40) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 2696.3 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11426 (21)
PL2/PK =  8.23E-4 (21)
PM1/PK =  0.01808 (7)
PM2/PK =  1.254E-4 (36)
PN1/PK =  0.001005 (17)

L/K =  0.11508 (24)
M/K =  0.01820 (8)
N/K =  0.001005 (17)


------------------------------
Relative capture probabilities

PK  =  0.88161 (26)
PL1 =  0.10073 (16)
PL2 =  7.26E-4 (19)
PM1 =  0.01594 (6)
PM2 =  1.105E-4 (31)
PN1 =  8.86E-4 (15)

K =  0.88161 (26)
L =  0.10146 (18)
M =  0.01605 (6)
N =  8.86E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1155 (24)
L1/b+ =  0.01320 (25)
L2/b+ =  9.51E-5 (10)
M1/b+ =  0.002088 (35)
M2/b+ =  1.448E-5 (19)
N1/b+ =  1.161E-4 (5)

K/b+ =  0.1155 (24)
L/b+ =  0.01330 (25)
M/b+ =  0.002103 (34)
N/b+ =  1.161E-4 (5)

EC/b+ =  0.1310 (26)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   7.920 (22) %   Iec =   0.920 (10) %   Ib+ =   7.000 (20) %
Iec      =   0.920 (10) % (input data kept)
Ib+      =   7.000 (20) % (input data kept)
Iec tot. =   7.920 (22) % (input data kept)


---------------------
Capture probabilities

PK  =  0.1021 (18)
PL1  =  0.01167 (21)
PL2  =  8.41E-5 (26)
PM1  =  0.001846 (34)
PM2  =  1.280E-5 (43)
PN1  =  1.027E-4 (25)

K =  0.1021 (18)
L =  0.01175 (21)
M =  0.001859 (34)
N =  1.027E-4 (25)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.814

Log ft value (ec)    =  5.815 (10)
with log f           =  0.417 (8)
and log partial T1/2 =  5.3979 (49)

