--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [1/2-] 2696.66 (13) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 669.5 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11628 (22)
PL2/PK =  8.14E-4 (22)
PM1/PK =  0.01843 (8)
PM2/PK =  1.242E-4 (37)
PN1/PK =  0.001025 (17)

L/K =  0.11710 (25)
M/K =  0.01856 (8)
N/K =  0.001025 (17)


------------------------------
Relative capture probabilities

PK  =  0.87975 (26)
PL1 =  0.10230 (17)
PL2 =  7.17E-4 (19)
PM1 =  0.01622 (6)
PM2 =  1.093E-4 (32)
PN1 =  9.02E-4 (15)

K =  0.87975 (26)
L =  0.10302 (18)
M =  0.01633 (7)
N =  9.02E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.122 (6) %


---------------------
Capture probabilities

PK  =  0.87975 (26)
PL1  =  0.10230 (17)
PL2  =  7.17E-4 (19)
PM1  =  0.01622 (6)
PM2  =  1.093E-4 (32)
PN1  =  9.02E-4 (15)

K =  0.87975 (26)
L =  0.10302 (18)
M =  0.01633 (7)
N =  9.02E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 5.47

Log ft value (ec)    =  5.472 (23)
with log f           =  -0.803 (10)
and log partial T1/2 =  6.275 (21)

