--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [5/2-] 962.020 (30) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 2404.2 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11434 (21)
PL2/PK =  8.21E-4 (21)
PM1/PK =  0.01809 (7)
PM2/PK =  1.250E-4 (36)
PN1/PK =  0.001006 (17)

L/K =  0.11516 (24)
M/K =  0.01821 (8)
N/K =  0.001006 (17)


------------------------------
Relative capture probabilities

PK  =  0.88154 (26)
PL1 =  0.10080 (16)
PL2 =  7.23E-4 (19)
PM1 =  0.01595 (6)
PM2 =  1.102E-4 (31)
PN1 =  8.87E-4 (15)

K =  0.88154 (26)
L =  0.10152 (18)
M =  0.01606 (6)
N =  8.87E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  0.2107 (44)
L1/b+ =  0.02410 (47)
L2/b+ =  1.729E-4 (19)
M1/b+ =  0.00381 (7)
M2/b+ =  2.633E-5 (36)
N1/b+ =  2.120E-4 (11)

K/b+ =  0.2107 (44)
L/b+ =  0.02427 (46)
M/b+ =  0.00384 (7)
N/b+ =  2.120E-4 (11)

EC/b+ =  0.239 (5)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   6.15 (13) %   Iec =   1.190 (30) %   Ib+ =   4.96 (13) %
Iec      =   1.190 (30) % (input data kept)
Ib+      =   4.96 (13) % (input data kept)
Iec tot. =   6.15 (13) % (input data kept)


---------------------
Capture probabilities

PK  =  0.1701 (29)
PL1  =  0.01945 (33)
PL2  =  1.396E-4 (43)
PM1  =  0.00308 (5)
PM2  =  2.13E-5 (7)
PN1  =  1.711E-4 (40)

K =  0.1701 (29)
L =  0.01959 (33)
M =  0.00310 (5)
N =  1.711E-4 (40)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.602

Log ft value (ec)    =  5.602 (14)
with log f           =  0.316 (8)
and log partial T1/2 =  5.286 (11)

