--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [1/2-] 3101.40 (40) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 264.8 (16) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12058 (27)
PL2/PK =  8.40E-4 (23)
PM1/PK =  0.01920 (9)
PM2/PK =  1.287E-4 (39)
PN1/PK =  0.001068 (18)

L/K =  0.12142 (29)
M/K =  0.01933 (9)
N/K =  0.001068 (18)


------------------------------
Relative capture probabilities

PK  =  0.87580 (31)
PL1 =  0.10561 (20)
PL2 =  7.36E-4 (20)
PM1 =  0.01681 (7)
PM2 =  1.127E-4 (33)
PN1 =  9.36E-4 (16)

K =  0.87580 (31)
L =  0.10634 (22)
M =  0.01693 (7)
N =  9.36E-4 (16)


------------------------------
Capture branch from input data

Iec =   7.0E-4 (20) %


---------------------
Capture probabilities

PK  =  0.87580 (31)
PL1  =  0.10561 (20)
PL2  =  7.36E-4 (20)
PM1  =  0.01681 (7)
PM2  =  1.127E-4 (33)
PN1  =  9.36E-4 (16)

K =  0.87580 (31)
L =  0.10634 (22)
M =  0.01693 (7)
N =  9.36E-4 (16)


------------------------------------------------------------
Input log ft value (ec): 6.89

Log ft value (ec)    =  6.89 (12)
with log f           =  -1.625 (13)
and log partial T1/2 =  8.52 (12)

