--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [1/2-] 2857.90 (30) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 508.3 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11715 (23)
PL2/PK =  8.19E-4 (22)
PM1/PK =  0.01859 (8)
PM2/PK =  1.250E-4 (37)
PN1/PK =  0.001034 (17)

L/K =  0.11797 (25)
M/K =  0.01871 (8)
N/K =  0.001034 (17)


------------------------------
Relative capture probabilities

PK  =  0.87895 (27)
PL1 =  0.10297 (17)
PL2 =  7.20E-4 (19)
PM1 =  0.01634 (6)
PM2 =  1.099E-4 (32)
PN1 =  9.09E-4 (15)

K =  0.87895 (27)
L =  0.10369 (19)
M =  0.01645 (7)
N =  9.09E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.0069 (12) %


---------------------
Capture probabilities

PK  =  0.87895 (27)
PL1  =  0.10297 (17)
PL2  =  7.20E-4 (19)
PM1  =  0.01634 (6)
PM2  =  1.099E-4 (32)
PN1  =  9.09E-4 (15)

K =  0.87895 (27)
L =  0.10369 (19)
M =  0.01645 (7)
N =  9.09E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 6.48

Log ft value (ec)    =  6.48 (8)
with log f           =  -1.046 (10)
and log partial T1/2 =  7.52 (8)

