--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [1/2-] 2511.06 (6) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 855.1 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11569 (22)
PL2/PK =  8.12E-4 (22)
PM1/PK =  0.01833 (7)
PM2/PK =  1.239E-4 (36)
PN1/PK =  0.001019 (17)

L/K =  0.11650 (24)
M/K =  0.01845 (8)
N/K =  0.001019 (17)


------------------------------
Relative capture probabilities

PK  =  0.88030 (26)
PL1 =  0.10184 (16)
PL2 =  7.15E-4 (19)
PM1 =  0.01614 (6)
PM2 =  1.090E-4 (32)
PN1 =  8.97E-4 (15)

K =  0.88030 (26)
L =  0.10256 (18)
M =  0.01624 (6)
N =  8.97E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.0110 (20) %


---------------------
Capture probabilities

PK  =  0.88030 (26)
PL1  =  0.10184 (16)
PL2  =  7.15E-4 (19)
PM1  =  0.01614 (6)
PM2  =  1.090E-4 (32)
PN1  =  8.97E-4 (15)

K =  0.88030 (26)
L =  0.10256 (18)
M =  0.01624 (6)
N =  8.97E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 6.73

Log ft value (ec)    =  6.73 (8)
with log f           =  -0.588 (9)
and log partial T1/2 =  7.32 (8)

