--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [3/2-] 1547.00 (5) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 1819.2 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11458 (22)
PL2/PK =  8.16E-4 (21)
PM1/PK =  0.01813 (7)
PM2/PK =  1.242E-4 (36)
PN1/PK =  0.001008 (17)

L/K =  0.11539 (24)
M/K =  0.01826 (8)
N/K =  0.001008 (17)


------------------------------
Relative capture probabilities

PK  =  0.88132 (26)
PL1 =  0.10098 (16)
PL2 =  7.19E-4 (19)
PM1 =  0.01598 (6)
PM2 =  1.095E-4 (31)
PN1 =  8.89E-4 (15)

K =  0.88132 (26)
L =  0.10170 (18)
M =  0.01609 (6)
N =  8.89E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  1.267 (30)
L1/b+ =  0.1452 (32)
L2/b+ =  0.001033 (15)
M1/b+ =  0.02298 (46)
M2/b+ =  1.574E-4 (27)
N1/b+ =  0.001277 (10)

K/b+ =  1.267 (30)
L/b+ =  0.1462 (32)
M/b+ =  0.02313 (46)
N/b+ =  0.001277 (10)

EC/b+ =  1.438 (34)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.102 (8) %   Iec =   0.060 (7) %   Ib+ =   0.0420 (40) %
Iec      =   0.060 (7) % (input data kept)
Ib+      =   0.0420 (40) % (input data kept)
Iec tot. =   0.102 (8) % (input data kept)


---------------------
Capture probabilities

PK  =  0.520 (5)
PL1  =  0.0596 (6)
PL2  =  4.24E-4 (12)
PM1  =  0.00942 (10)
PM2  =  6.46E-5 (20)
PN1  =  5.24E-4 (10)

K =  0.520 (5)
L =  0.0600 (6)
M =  0.00949 (10)
N =  5.24E-4 (10)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.65

Log ft value (ec)    =  6.66 (5)
with log f           =  0.072 (8)
and log partial T1/2 =  6.58 (5)

