--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [5/2-] 2081.32 (22) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 1284.9 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11499 (22)
PL2/PK =  8.12E-4 (21)
PM1/PK =  0.01820 (7)
PM2/PK =  1.238E-4 (36)
PN1/PK =  0.001012 (17)

L/K =  0.11580 (24)
M/K =  0.01833 (8)
N/K =  0.001012 (17)


------------------------------
Relative capture probabilities

PK  =  0.88095 (26)
PL1 =  0.10130 (16)
PL2 =  7.16E-4 (19)
PM1 =  0.01604 (6)
PM2 =  1.090E-4 (32)
PN1 =  8.92E-4 (15)

K =  0.88095 (26)
L =  0.10201 (18)
M =  0.01615 (6)
N =  8.92E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  70.0 (28)
L1/b+ =  8.05 (31)
L2/b+ =  0.0569 (18)
M1/b+ =  1.275 (47)
M2/b+ =  0.00867 (29)
N1/b+ =  0.0709 (17)

K/b+ =  70.0 (28)
L/b+ =  8.11 (31)
M/b+ =  1.283 (47)
N/b+ =  0.0709 (17)

EC/b+ =  79.5 (32)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.035 (7) %   Iec =   0.035 (7) %   Ib+ =   4.3E-4 (9) %
Iec      =   0.035 (7) % (input data kept)
Ib+      =   4.3E-4 (9) % (input data kept)
Iec tot. =   0.035 (7) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8700 (5)
PL1  =  0.10004 (17)
PL2  =  7.07E-4 (18)
PM1  =  0.01584 (6)
PM2  =  1.077E-4 (31)
PN1  =  8.81E-4 (14)

K =  0.8700 (5)
L =  0.10075 (18)
M =  0.01595 (6)
N =  8.81E-4 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.59

Log ft value (ec)    =  6.59 (9)
with log f           =  -0.232 (9)
and log partial T1/2 =  6.82 (9)

