--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [5/2-] 3042.59 (8) keV
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 323.6 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11926 (25)
PL2/PK =  8.31E-4 (22)
PM1/PK =  0.01896 (8)
PM2/PK =  1.272E-4 (38)
PN1/PK =  0.001055 (18)

L/K =  0.12009 (27)
M/K =  0.01909 (9)
N/K =  0.001055 (18)


------------------------------
Relative capture probabilities

PK  =  0.87701 (29)
PL1 =  0.10459 (19)
PL2 =  7.29E-4 (19)
PM1 =  0.01663 (7)
PM2 =  1.116E-4 (33)
PN1 =  9.25E-4 (15)

K =  0.87701 (29)
L =  0.10532 (20)
M =  0.01674 (7)
N =  9.25E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.0048 (8) %


---------------------
Capture probabilities

PK  =  0.87701 (29)
PL1  =  0.10459 (19)
PL2  =  7.29E-4 (19)
PM1  =  0.01663 (7)
PM2  =  1.116E-4 (33)
PN1  =  9.25E-4 (15)

K =  0.87701 (29)
L =  0.10532 (20)
M =  0.01674 (7)
N =  9.25E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 6.24

Log ft value (ec)    =  6.23 (7)
with log f           =  -1.446 (12)
and log partial T1/2 =  7.68 (7)

