--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-63 [3/2-] g.s.  -->  Daughter nucleus: 29-Cu-63 [3/2-] g.s.
Calculation of the allowed transition from the electron capture decay of Zn-63

Transition energy: 3366.2 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11413 (21)
PL2/PK =  8.30E-4 (21)
PM1/PK =  0.01805 (7)
PM2/PK =  1.264E-4 (36)
PN1/PK =  0.001004 (17)

L/K =  0.11496 (24)
M/K =  0.01818 (8)
N/K =  0.001004 (17)


------------------------------
Relative capture probabilities

PK  =  0.88172 (26)
PL1 =  0.10063 (16)
PL2 =  7.32E-4 (19)
PM1 =  0.01592 (6)
PM2 =  1.114E-4 (31)
PN1 =  8.85E-4 (14)

K =  0.88172 (26)
L =  0.10136 (18)
M =  0.01603 (6)
N =  8.85E-4 (14)


--------------------------
Capture-to-positron ratios

K/b+ =  0.0412 (8)
L1/b+ =  0.00470 (8)
L2/b+ =  3.414E-5 (31)
M1/b+ =  7.43E-4 (12)
M2/b+ =  5.20E-6 (6)
N1/b+ =  4.131E-5 (15)

K/b+ =  0.0412 (8)
L/b+ =  0.00473 (8)
M/b+ =  7.48E-4 (12)
N/b+ =  4.131E-5 (15)

EC/b+ =  0.0467 (9)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   84.0 (6) %   Iec =   3.75 (5) %   Ib+ =   80.3 (6) %
Iec      =   3.75 (5) % (input data kept)
Ib+      =   80.3 (6) % (input data kept)
Iec tot. =   84.1 (6) % (input data kept)


---------------------
Capture probabilities

PK  =  0.0393 (7)
PL1  =  0.00449 (8)
PL2  =  3.26E-5 (10)
PM1  =  7.10E-4 (13)
PM2  =  4.97E-6 (17)
PN1  =  3.95E-5 (10)

K =  0.0393 (7)
L =  0.00452 (8)
M =  7.15E-4 (13)
N =  3.95E-5 (10)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.397

Log ft value (ec)    =  5.399 (10)
with log f           =  0.611 (8)
and log partial T1/2 =  4.788 (6)

