--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [2+] 2514.663 (13) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 2448 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10995 (19)
PL2/PK =  0.0011452 (17)
PM1/PK =  0.01845 (11)
PM2/PK =  1.845E-4 (6)
PN1/PK =  0.002791 (33)
PN2/PK =  1.637E-5 (18)

L/K =  0.11110 (19)
M/K =  0.01863 (11)
N/K =  0.002808 (33)


------------------------------
Relative capture probabilities

PK  =  0.88297 (26)
PL1 =  0.09709 (14)
PL2 =  0.0010112 (18)
PM1 =  0.01629 (9)
PM2 =  1.6292E-4 (48)
PN1 =  0.002465 (28)
PN2 =  1.445E-5 (15)

K =  0.88297 (26)
L =  0.09810 (14)
M =  0.01645 (9)
N =  0.002479 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0.373 (11)
L1/b+ =  0.0410 (11)
L2/b+ =  4.27E-4 (13)
M1/b+ =  0.00689 (16)
M2/b+ =  6.88E-5 (18)
N1/b+ =  0.001042 (25)
N2/b+ =  6.11E-6 (14)

K/b+ =  0.373 (11)
L/b+ =  0.0415 (11)
M/b+ =  0.00695 (16)
N/b+ =  0.001048 (25)

EC/b+ =  0.423 (12)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.39 (18) %   Iec =   0.11 (7) %   Ib+ =   0.28 (17) %
Iec      =   0.11 (7) % (input data kept)
Ib+      =   0.28 (17) % (input data kept)
Iec tot. =   0.39 (18) % (input data kept)


---------------------
Capture probabilities

PK  =  0.262 (5)
PL1  =  0.0288 (6)
PL2  =  3.00E-4 (6)
PM1  =  0.00484 (10)
PM2  =  4.84E-5 (10)
PN1  =  7.32E-4 (17)
PN2  =  4.29E-6 (10)

K =  0.262 (5)
L =  0.0291 (6)
M =  0.00489 (10)
N =  7.37E-4 (17)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.3

Log ft value (ec)    =  8.31 (28)
with log f           =  0.590 (7)
and log partial T1/2 =  7.72 (28)

