--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [2-] 2669.880 (40) keV
Calculation of the allowed transition from the electron capture decay of Br-76

Transition energy: 2293 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11002 (19)
PL2/PK =  0.0011434 (17)
PM1/PK =  0.01846 (11)
PM2/PK =  1.842E-4 (6)
PN1/PK =  0.002793 (33)
PN2/PK =  1.635E-5 (18)

L/K =  0.11116 (19)
M/K =  0.01865 (11)
N/K =  0.002810 (33)


------------------------------
Relative capture probabilities

PK  =  0.88291 (26)
PL1 =  0.09714 (14)
PL2 =  0.0010096 (18)
PM1 =  0.01630 (9)
PM2 =  1.6267E-4 (48)
PN1 =  0.002466 (29)
PN2 =  1.443E-5 (15)

K =  0.88291 (26)
L =  0.09815 (14)
M =  0.01646 (9)
N =  0.002481 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0.539 (17)
L1/b+ =  0.0593 (18)
L2/b+ =  6.17E-4 (20)
M1/b+ =  0.00996 (26)
M2/b+ =  9.93E-5 (28)
N1/b+ =  0.001506 (40)
N2/b+ =  8.81E-6 (22)

K/b+ =  0.539 (17)
L/b+ =  0.0600 (18)
M/b+ =  0.01006 (26)
N/b+ =  0.001515 (40)

EC/b+ =  0.611 (19)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   2.37 (12) %   Iec =   0.88 (6) %   Ib+ =   1.49 (10) %
Iec      =   0.88 (6) % (input data kept)
Ib+      =   1.49 (10) % (input data kept)
Iec tot. =   2.37 (12) % (input data kept)


---------------------
Capture probabilities

PK  =  0.335 (6)
PL1  =  0.0368 (7)
PL2  =  3.83E-4 (7)
PM1  =  0.00618 (12)
PM2  =  6.17E-5 (12)
PN1  =  9.35E-4 (21)
PN2  =  5.47E-6 (12)

K =  0.335 (6)
L =  0.0372 (7)
M =  0.00624 (13)
N =  9.41E-4 (21)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.33

Log ft value (ec)    =  7.351 (31)
with log f           =  0.532 (7)
and log partial T1/2 =  6.819 (30)

