--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 4436.9 (10) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 526 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11363 (28)
PL2/PK =  0.0011523 (23)
PM1/PK =  0.01915 (13)
PM2/PK =  1.864E-4 (7)
PN1/PK =  0.002898 (37)
PN2/PK =  1.654E-5 (19)

L/K =  0.11478 (28)
M/K =  0.01933 (13)
N/K =  0.002915 (37)


------------------------------
Relative capture probabilities

PK  =  0.87949 (35)
PL1 =  0.09993 (21)
PL2 =  0.0010134 (23)
PM1 =  0.01684 (11)
PM2 =  1.639E-4 (6)
PN1 =  0.002549 (31)
PN2 =  1.455E-5 (16)

K =  0.87949 (35)
L =  0.10095 (21)
M =  0.01700 (11)
N =  0.002564 (31)


------------------------------
Capture branch from input data

Iec =   0.067 (15) %


---------------------
Capture probabilities

PK  =  0.87949 (35)
PL1  =  0.09993 (21)
PL2  =  0.0010134 (23)
PM1  =  0.01684 (11)
PM2  =  1.639E-4 (6)
PN1  =  0.002549 (31)
PN2  =  1.455E-5 (16)

K =  0.87949 (35)
L =  0.10095 (21)
M =  0.01700 (11)
N =  0.002564 (31)


------------------------------------------------------------
Input log ft value (ec): 7.2

Log ft value (ec)    =  7.18 (10)
with log f           =  -0.762 (19)
and log partial T1/2 =  7.94 (10)

