--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4621.5 (20) keV
Calculation of the allowed transition from the electron capture decay of Br-76

Transition energy: 342 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11628 (42)
PL2/PK =  0.0011764 (37)
PM1/PK =  0.01965 (16)
PM2/PK =  1.908E-4 (10)
PN1/PK =  0.002976 (42)
PN2/PK =  1.694E-5 (22)

L/K =  0.11745 (42)
M/K =  0.01984 (16)
N/K =  0.002992 (42)


------------------------------
Relative capture probabilities

PK  =  0.87698 (47)
PL1 =  0.10197 (31)
PL2 =  0.0010317 (33)
PM1 =  0.01723 (13)
PM2 =  1.673E-4 (8)
PN1 =  0.002609 (35)
PN2 =  1.486E-5 (18)

K =  0.87698 (47)
L =  0.10300 (31)
M =  0.01740 (13)
N =  0.002624 (35)


------------------------------
Capture branch from input data

Iec =   0.210 (40) %


---------------------
Capture probabilities

PK  =  0.87698 (47)
PL1  =  0.10197 (31)
PL2  =  0.0010317 (33)
PM1  =  0.01723 (13)
PM2  =  1.673E-4 (8)
PN1  =  0.002609 (35)
PN2  =  1.486E-5 (18)

K =  0.87698 (47)
L =  0.10300 (31)
M =  0.01740 (13)
N =  0.002624 (35)


------------------------------------------------------------
Input log ft value (ec): 6.3

Log ft value (ec)    =  6.29 (9)
with log f           =  -1.148 (28)
and log partial T1/2 =  7.44 (8)

