--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 3669.5 (10) keV
Calculation of the allowed transition from the electron capture decay of Br-76

Transition energy: 1294 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11083 (20)
PL2/PK =  0.0011359 (16)
PM1/PK =  0.01862 (11)
PM2/PK =  1.832E-4 (6)
PN1/PK =  0.002817 (34)
PN2/PK =  1.626E-5 (17)

L/K =  0.11197 (20)
M/K =  0.01880 (11)
N/K =  0.002833 (34)


------------------------------
Relative capture probabilities

PK  =  0.88214 (27)
PL1 =  0.09777 (15)
PL2 =  0.0010021 (17)
PM1 =  0.01642 (10)
PM2 =  1.6160E-4 (46)
PN1 =  0.002485 (29)
PN2 =  1.434E-5 (15)

K =  0.88214 (27)
L =  0.09877 (15)
M =  0.01658 (10)
N =  0.002499 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  132 (20)
L1/b+ =  14.7 (22)
L2/b+ =  0.150 (23)
M1/b+ =  2.46 (36)
M2/b+ =  0.0242 (36)
N1/b+ =  0.37 (6)
N2/b+ =  0.00215 (32)

K/b+ =  132 (20)
L/b+ =  14.8 (22)
M/b+ =  2.49 (37)
N/b+ =  0.37 (6)

EC/b+ =  150 (23)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.74 (19) %   Iec =   0.73 (19) %   Ib+ =   0.0050 (10) %
Iec      =   0.73 (19) % (input data kept)
Ib+      =   0.0050 (10) % (input data kept)
Iec tot. =   0.74 (19) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8763 (9)
PL1  =  0.09712 (18)
PL2  =  9.954E-4 (20)
PM1  =  0.01631 (10)
PM2  =  1.6053E-4 (49)
PN1  =  0.002468 (29)
PN2  =  1.424E-5 (15)

K =  0.8763 (9)
L =  0.09812 (18)
M =  0.01647 (10)
N =  0.002483 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.9

Log ft value (ec)    =  6.93 (11)
with log f           =  0.031 (10)
and log partial T1/2 =  6.90 (11)

