--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4492.0 (30) keV
Calculation of the allowed transition from the electron capture decay of Br-76

Transition energy: 471 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11419 (31)
PL2/PK =  0.0011572 (26)
PM1/PK =  0.01925 (14)
PM2/PK =  1.873E-4 (8)
PN1/PK =  0.002915 (38)
PN2/PK =  1.662E-5 (19)

L/K =  0.11535 (31)
M/K =  0.01944 (14)
N/K =  0.002931 (38)


------------------------------
Relative capture probabilities

PK  =  0.87895 (37)
PL1 =  0.10037 (23)
PL2 =  0.0010171 (25)
PM1 =  0.01692 (11)
PM2 =  1.646E-4 (6)
PN1 =  0.002562 (32)
PN2 =  1.461E-5 (16)

K =  0.87895 (37)
L =  0.10139 (23)
M =  0.01709 (11)
N =  0.002577 (32)


------------------------------
Capture branch from input data

Iec =   0.052 (15) %


---------------------
Capture probabilities

PK  =  0.87895 (37)
PL1  =  0.10037 (23)
PL2  =  0.0010171 (25)
PM1  =  0.01692 (11)
PM2  =  1.646E-4 (6)
PN1  =  0.002562 (32)
PN2  =  1.461E-5 (16)

K =  0.87895 (37)
L =  0.10139 (23)
M =  0.01709 (11)
N =  0.002577 (32)


------------------------------------------------------------
Input log ft value (ec): 7.2

Log ft value (ec)    =  7.19 (13)
with log f           =  -0.861 (22)
and log partial T1/2 =  8.05 (13)

