--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 4215.50 (20) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 748 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11222 (23)
PL2/PK =  0.0011414 (19)
PM1/PK =  0.01888 (12)
PM2/PK =  1.843E-4 (6)
PN1/PK =  0.002857 (35)
PN2/PK =  1.636E-5 (18)

L/K =  0.11336 (23)
M/K =  0.01906 (12)
N/K =  0.002874 (35)


------------------------------
Relative capture probabilities

PK  =  0.88083 (30)
PL1 =  0.09884 (17)
PL2 =  0.0010054 (19)
PM1 =  0.01663 (10)
PM2 =  1.624E-4 (5)
PN1 =  0.002517 (30)
PN2 =  1.441E-5 (15)

K =  0.88083 (30)
L =  0.09985 (17)
M =  0.01679 (10)
N =  0.002531 (30)


------------------------------
Capture branch from input data

Iec =   0.610 (30) %


---------------------
Capture probabilities

PK  =  0.88083 (30)
PL1  =  0.09884 (17)
PL2  =  0.0010054 (19)
PM1  =  0.01663 (10)
PM2  =  1.624E-4 (5)
PN1  =  0.002517 (30)
PN2  =  1.441E-5 (15)

K =  0.88083 (30)
L =  0.09985 (17)
M =  0.01679 (10)
N =  0.002531 (30)


------------------------------------------------------------
Input log ft value (ec): 6.5

Log ft value (ec)    =  6.527 (26)
with log f           =  -0.452 (14)
and log partial T1/2 =  6.978 (22)

