--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [2+] 3459.40 (8) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 1504 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11057 (20)
PL2/PK =  0.0011366 (16)
PM1/PK =  0.01857 (11)
PM2/PK =  1.832E-4 (6)
PN1/PK =  0.002809 (34)
PN2/PK =  1.626E-5 (17)

L/K =  0.11171 (20)
M/K =  0.01875 (11)
N/K =  0.002826 (34)


------------------------------
Relative capture probabilities

PK  =  0.88239 (27)
PL1 =  0.09757 (15)
PL2 =  0.0010029 (18)
PM1 =  0.01638 (9)
PM2 =  1.6169E-4 (47)
PN1 =  0.002479 (29)
PN2 =  1.435E-5 (15)

K =  0.88239 (27)
L =  0.09857 (15)
M =  0.01655 (10)
N =  0.002493 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  14.9 (12)
L1/b+ =  1.65 (13)
L2/b+ =  0.0170 (14)
M1/b+ =  0.277 (21)
M2/b+ =  0.00274 (21)
N1/b+ =  0.0420 (32)
N2/b+ =  2.43E-4 (18)

K/b+ =  14.9 (12)
L/b+ =  1.67 (13)
M/b+ =  0.280 (21)
N/b+ =  0.0422 (32)

EC/b+ =  16.9 (13)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.92 (15) %   Iec =   1.81 (15) %   Ib+ =   0.108 (9) %
Iec      =   1.81 (15) % (input data kept)
Ib+      =   0.108 (9) % (input data kept)
Iec tot. =   1.92 (15) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8332 (37)
PL1  =  0.09213 (43)
PL2  =  9.470E-4 (45)
PM1  =  0.01547 (11)
PM2  =  1.527E-4 (8)
PN1  =  0.002341 (29)
PN2  =  1.355E-5 (15)

K =  0.8332 (37)
L =  0.09307 (44)
M =  0.01562 (11)
N =  0.002354 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.65

Log ft value (ec)    =  6.668 (37)
with log f           =  0.163 (9)
and log partial T1/2 =  6.506 (36)

