--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 3929.1 (6) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 1034 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11130 (21)
PL2/PK =  0.0011366 (17)
PM1/PK =  0.01871 (12)
PM2/PK =  1.834E-4 (6)
PN1/PK =  0.002831 (34)
PN2/PK =  1.627E-5 (18)

L/K =  0.11244 (21)
M/K =  0.01889 (12)
N/K =  0.002847 (34)


------------------------------
Relative capture probabilities

PK  =  0.88170 (28)
PL1 =  0.09814 (16)
PL2 =  0.0010022 (17)
PM1 =  0.01649 (10)
PM2 =  1.6170E-4 (47)
PN1 =  0.002496 (29)
PN2 =  1.435E-5 (15)

K =  0.88170 (28)
L =  0.09914 (15)
M =  0.01665 (10)
N =  0.002510 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0E11 (6)
L1/b+ =  0E10 (7)
L2/b+ =  0E8 (7)
M1/b+ =  0.0E10 (12)
M2/b+ =  0.0E8 (12)
N1/b+ =  0.0E9 (18)
N2/b+ =  0.0E7 (11)

K/b+ =  0E11 (6)
L/b+ =  0E10 (7)
M/b+ =  0.0E10 (12)
N/b+ =  0.0E9 (19)

EC/b+ =  0E11 (7)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.170 (40) %   Iec =   0.170 (40) %   Ib+ =   0. %
Iec      =   0.170 (40) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.170 (40) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88170 (28)
PL1  =  0.09814 (16)
PL2  =  0.0010022 (17)
PM1  =  0.01649 (10)
PM2  =  1.6170E-4 (47)
PN1  =  0.002496 (29)
PN2  =  1.435E-5 (15)

K =  0.88170 (28)
L =  0.09914 (15)
M =  0.01665 (10)
N =  0.002510 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.4

Log ft value (ec)    =  7.37 (10)
with log f           =  -0.166 (11)
and log partial T1/2 =  7.53 (10)

