--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [2+] 3160.07 (6) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 1803 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11030 (20)
PL2/PK =  0.0011386 (17)
PM1/PK =  0.01852 (11)
PM2/PK =  1.835E-4 (6)
PN1/PK =  0.002802 (33)
PN2/PK =  1.628E-5 (18)

L/K =  0.11144 (20)
M/K =  0.01870 (11)
N/K =  0.002818 (34)


------------------------------
Relative capture probabilities

PK  =  0.88264 (27)
PL1 =  0.09736 (14)
PL2 =  0.0010050 (18)
PM1 =  0.01634 (9)
PM2 =  1.6198E-4 (47)
PN1 =  0.002473 (29)
PN2 =  1.437E-5 (15)

K =  0.88264 (27)
L =  0.09836 (14)
M =  0.01651 (9)
N =  0.002487 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  2.71 (13)
L1/b+ =  0.299 (14)
L2/b+ =  0.00308 (15)
M1/b+ =  0.0502 (22)
M2/b+ =  4.97E-4 (23)
N1/b+ =  0.00759 (33)
N2/b+ =  4.41E-5 (19)

K/b+ =  2.71 (13)
L/b+ =  0.302 (14)
M/b+ =  0.0506 (22)
N/b+ =  0.00763 (34)

EC/b+ =  3.07 (15)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   5.31 (15) %   Iec =   3.99 (14) %   Ib+ =   1.320 (40) %
Iec      =   3.99 (14) % (input data kept)
Ib+      =   1.320 (40) % (input data kept)
Iec tot. =   5.31 (15) % (input data kept)


---------------------
Capture probabilities

PK  =  0.666 (8)
PL1  =  0.0734 (9)
PL2  =  7.58E-4 (9)
PM1  =  0.01233 (16)
PM2  =  1.222E-4 (15)
PN1  =  0.001865 (31)
PN2  =  1.084E-5 (17)

K =  0.666 (8)
L =  0.0742 (9)
M =  0.01245 (16)
N =  0.001876 (31)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.47

Log ft value (ec)    =  6.484 (18)
with log f           =  0.322 (8)
and log partial T1/2 =  6.162 (16)

