--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4019.3 (5) keV
Calculation of the allowed transition from the electron capture decay of Br-76

Transition energy: 944 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11153 (22)
PL2/PK =  0.0011375 (17)
PM1/PK =  0.01875 (12)
PM2/PK =  1.836E-4 (6)
PN1/PK =  0.002837 (34)
PN2/PK =  1.629E-5 (18)

L/K =  0.11267 (22)
M/K =  0.01893 (12)
N/K =  0.002854 (34)


------------------------------
Relative capture probabilities

PK  =  0.88148 (29)
PL1 =  0.09831 (16)
PL2 =  0.0010027 (18)
PM1 =  0.01653 (10)
PM2 =  1.6182E-4 (48)
PN1 =  0.002501 (29)
PN2 =  1.436E-5 (15)

K =  0.88148 (29)
L =  0.09932 (16)
M =  0.01669 (10)
N =  0.002515 (30)


------------------------------
Capture branch from input data

Iec =   0.36 (7) %


---------------------
Capture probabilities

PK  =  0.88148 (29)
PL1  =  0.09831 (16)
PL2  =  0.0010027 (18)
PM1  =  0.01653 (10)
PM2  =  1.6182E-4 (48)
PN1  =  0.002501 (29)
PN2  =  1.436E-5 (15)

K =  0.88148 (29)
L =  0.09932 (16)
M =  0.01669 (10)
N =  0.002515 (30)


------------------------------------------------------------
Input log ft value (ec): 7.

Log ft value (ec)    =  6.96 (9)
with log f           =  -0.246 (12)
and log partial T1/2 =  7.21 (8)

