--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 2374.2 (6) keV
Calculation of the allowed transition from the electron capture decay of Br-76

Transition energy: 2589 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10990 (19)
PL2/PK =  0.0011469 (17)
PM1/PK =  0.01844 (11)
PM2/PK =  1.848E-4 (6)
PN1/PK =  0.002790 (33)
PN2/PK =  1.639E-5 (18)

L/K =  0.11105 (19)
M/K =  0.01863 (11)
N/K =  0.002806 (33)


------------------------------
Relative capture probabilities

PK  =  0.88302 (26)
PL1 =  0.09704 (14)
PL2 =  0.0010127 (18)
PM1 =  0.01628 (9)
PM2 =  1.6316E-4 (48)
PN1 =  0.002463 (28)
PN2 =  1.448E-5 (15)

K =  0.88302 (26)
L =  0.09806 (14)
M =  0.01645 (9)
N =  0.002478 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0.277 (7)
L1/b+ =  0.0305 (8)
L2/b+ =  3.18E-4 (9)
M1/b+ =  0.00511 (11)
M2/b+ =  5.12E-5 (12)
N1/b+ =  7.74E-4 (17)
N2/b+ =  4.55E-6 (9)

K/b+ =  0.277 (7)
L/b+ =  0.0308 (8)
M/b+ =  0.00517 (11)
N/b+ =  7.78E-4 (17)

EC/b+ =  0.314 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.280 (22) %   Iec =   0.070 (10) %   Ib+ =   0.210 (20) %
Iec      =   0.070 (10) % (input data kept)
Ib+      =   0.210 (20) % (input data kept)
Iec tot. =   0.280 (22) % (input data kept)


---------------------
Capture probabilities

PK  =  0.2111 (42)
PL1  =  0.02320 (47)
PL2  =  2.421E-4 (49)
PM1  =  0.00389 (8)
PM2  =  3.90E-5 (8)
PN1  =  5.89E-4 (14)
PN2  =  3.46E-6 (8)

K =  0.2111 (42)
L =  0.02344 (47)
M =  0.00393 (8)
N =  5.92E-4 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.6

Log ft value (ec)    =  8.56 (6)
with log f           =  0.639 (7)
and log partial T1/2 =  7.92 (6)

