--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [2+] 1787.648 (8) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 3175 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10973 (19)
PL2/PK =  0.0011543 (17)
PM1/PK =  0.01841 (11)
PM2/PK =  1.859E-4 (6)
PN1/PK =  0.002785 (33)
PN2/PK =  1.650E-5 (18)

L/K =  0.11089 (19)
M/K =  0.01859 (11)
N/K =  0.002801 (33)


------------------------------
Relative capture probabilities

PK  =  0.88317 (26)
PL1 =  0.09691 (14)
PL2 =  0.0010195 (18)
PM1 =  0.01626 (9)
PM2 =  1.6421E-4 (49)
PN1 =  0.002460 (28)
PN2 =  1.457E-5 (15)

K =  0.88317 (26)
L =  0.09793 (14)
M =  0.01642 (9)
N =  0.002474 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1035 (22)
L1/b+ =  0.01136 (22)
L2/b+ =  1.195E-4 (27)
M1/b+ =  0.001906 (29)
M2/b+ =  1.924E-5 (35)
N1/b+ =  2.883E-4 (47)
N2/b+ =  1.707E-6 (26)

K/b+ =  0.1035 (22)
L/b+ =  0.01148 (23)
M/b+ =  0.001925 (30)
N/b+ =  2.900E-4 (47)

EC/b+ =  0.1172 (25)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.00 (40) %   Iec =   0.100 (40) %   Ib+ =   0.90 (40) %
Iec      =   0.100 (40) % (input data kept)
Ib+      =   0.90 (40) % (input data kept)
Iec tot. =   1.00 (40) % (input data kept)


---------------------
Capture probabilities

PK  =  0.0927 (17)
PL1  =  0.01017 (19)
PL2  =  1.070E-4 (20)
PM1  =  0.001706 (33)
PM2  =  1.723E-5 (33)
PN1  =  2.58E-4 (6)
PN2  =  1.529E-6 (33)

K =  0.0927 (17)
L =  0.01028 (19)
M =  0.001723 (34)
N =  2.60E-4 (6)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.6

Log ft value (ec)    =  8.58 (17)
with log f           =  0.818 (6)
and log partial T1/2 =  7.76 (17)

