--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 3556.46 (8) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 1407 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11068 (20)
PL2/PK =  0.0011362 (16)
PM1/PK =  0.01859 (11)
PM2/PK =  1.832E-4 (6)
PN1/PK =  0.002813 (34)
PN2/PK =  1.626E-5 (17)

L/K =  0.11182 (20)
M/K =  0.01877 (11)
N/K =  0.002829 (34)


------------------------------
Relative capture probabilities

PK  =  0.88229 (27)
PL1 =  0.09765 (15)
PL2 =  0.0010024 (17)
PM1 =  0.01640 (9)
PM2 =  1.6164E-4 (46)
PN1 =  0.002481 (29)
PN2 =  1.434E-5 (15)

K =  0.88229 (27)
L =  0.09866 (15)
M =  0.01656 (10)
N =  0.002496 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  34.5 (35)
L1/b+ =  3.81 (38)
L2/b+ =  0.0391 (40)
M1/b+ =  0.64 (6)
M2/b+ =  0.0063 (6)
N1/b+ =  0.097 (9)
N2/b+ =  5.6E-4 (5)

K/b+ =  34.5 (35)
L/b+ =  3.85 (39)
M/b+ =  0.65 (6)
N/b+ =  0.097 (10)

EC/b+ =  39.0 (40)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.57 (8) %   Iec =   1.53 (8) %   Ib+ =   0.0400 (40) %
Iec      =   1.53 (8) % (input data kept)
Ib+      =   0.0400 (40) % (input data kept)
Iec tot. =   1.57 (8) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8603 (22)
PL1  =  0.09521 (28)
PL2  =  9.774E-4 (30)
PM1  =  0.01599 (10)
PM2  =  1.576E-4 (6)
PN1  =  0.002420 (29)
PN2  =  1.398E-5 (15)

K =  0.8603 (22)
L =  0.09619 (28)
M =  0.01615 (10)
N =  0.002433 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.67

Log ft value (ec)    =  6.683 (25)
with log f           =  0.104 (9)
and log partial T1/2 =  6.579 (23)

