--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [0+] g.s.
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 4963 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10946 (19)
PL2/PK =  0.0011790 (17)
PM1/PK =  0.01836 (11)
PM2/PK =  1.899E-4 (6)
PN1/PK =  0.002777 (33)
PN2/PK =  1.684E-5 (18)

L/K =  0.11064 (19)
M/K =  0.01855 (11)
N/K =  0.002794 (33)


------------------------------
Relative capture probabilities

PK  =  0.88340 (26)
PL1 =  0.09670 (14)
PL2 =  0.0010415 (18)
PM1 =  0.01622 (9)
PM2 =  1.677E-4 (5)
PN1 =  0.002453 (28)
PN2 =  1.488E-5 (16)

K =  0.88340 (26)
L =  0.09774 (14)
M =  0.01638 (9)
N =  0.002468 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  0.01694 (26)
L1/b+ =  0.001854 (25)
L2/b+ =  1.996E-5 (33)
M1/b+ =  3.109E-4 (29)
M2/b+ =  3.214E-6 (38)
N1/b+ =  4.703E-5 (47)
N2/b+ =  2.851E-7 (25)

K/b+ =  0.01694 (26)
L/b+ =  0.001874 (25)
M/b+ =  3.141E-4 (29)
N/b+ =  4.732E-5 (48)

EC/b+ =  0.01917 (28)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   5.8 (8) %   Iec =   0.100 (20) %   Ib+ =   5.7 (8) %
Iec      =   0.100 (20) % (input data kept)
Ib+      =   5.7 (8) % (input data kept)
Iec tot. =   5.8 (8) % (input data kept)


---------------------
Capture probabilities

PK  =  0.01662 (24)
PL1  =  0.001819 (27)
PL2  =  1.959E-5 (29)
PM1  =  3.051E-4 (48)
PM2  =  3.155E-6 (47)
PN1  =  4.61E-5 (9)
PN2  =  2.80E-7 (5)

K =  0.01662 (24)
L =  0.001839 (27)
M =  3.082E-4 (48)
N =  4.64E-5 (9)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.93

Log ft value (ec)    =  8.97 (9)
with log f           =  1.211 (5)
and log partial T1/2 =  7.76 (9)

