--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [2+] 559.102 (5) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 4404 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10952 (19)
PL2/PK =  0.0011711 (17)
PM1/PK =  0.01837 (11)
PM2/PK =  1.886E-4 (6)
PN1/PK =  0.002779 (33)
PN2/PK =  1.673E-5 (18)

L/K =  0.11070 (19)
M/K =  0.01856 (11)
N/K =  0.002796 (33)


------------------------------
Relative capture probabilities

PK  =  0.88335 (26)
PL1 =  0.09675 (14)
PL2 =  0.0010345 (18)
PM1 =  0.01623 (9)
PM2 =  1.666E-4 (5)
PN1 =  0.002455 (28)
PN2 =  1.478E-5 (16)

K =  0.88335 (26)
L =  0.09778 (14)
M =  0.01639 (9)
N =  0.002470 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  0.02662 (43)
L1/b+ =  0.002915 (43)
L2/b+ =  3.12E-5 (5)
M1/b+ =  4.89E-4 (5)
M2/b+ =  5.02E-6 (7)
N1/b+ =  7.40E-5 (8)
N2/b+ =  4.452E-7 (45)

K/b+ =  0.02662 (43)
L/b+ =  0.002947 (43)
M/b+ =  4.94E-4 (5)
N/b+ =  7.44E-5 (8)

EC/b+ =  0.03013 (48)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   26.4 (9) %   Iec =   0.750 (30) %   Ib+ =   25.7 (9) %
Iec      =   0.750 (30) % (input data kept)
Ib+      =   25.7 (9) % (input data kept)
Iec tot. =   26.5 (9) % (input data kept)


---------------------
Capture probabilities

PK  =  0.02584 (40)
PL1  =  0.002830 (44)
PL2  =  3.026E-5 (47)
PM1  =  4.75E-4 (8)
PM2  =  4.87E-6 (8)
PN1  =  7.18E-5 (14)
PN2  =  4.32E-7 (8)

K =  0.02584 (40)
L =  0.002860 (45)
M =  4.80E-4 (8)
N =  7.22E-5 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.98

Log ft value (ec)    =  7.994 (19)
with log f           =  1.106 (5)
and log partial T1/2 =  6.888 (18)

