--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [3-] 2429.095 (11) keV
The 2nd forbidden non-unique transition from the electron capture decay of Br-76 is calculated as 1st forbidden unique

Transition energy: 2534 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11087 (20)
PL2/PK =  0.0011516 (17)
PL3/PK =  1.397E-4 (11)
PM1/PK =  0.01862 (11)
PM2/PK =  1.857E-4 (6)
PM3/PK =  2.007E-5 (23)
PN1/PK =  0.002818 (34)
PM4/PK =  9.23E-9 (21)
PN2/PK =  1.648E-5 (18)
PN3/PK =  9.99E-7 (21)

L/K =  0.11216 (20)
M/K =  0.01883 (11)
N/K =  0.002835 (34)


------------------------------
Relative capture probabilities

PK  =  0.88197 (27)
PL1 =  0.09778 (15)
PL2 =  0.0010157 (18)
PL3 =  1.232E-4 (10)
PM1 =  0.01643 (9)
PM2 =  1.6381E-4 (48)
PM3 =  1.770E-5 (20)
PN1 =  0.002485 (29)
PM4 =  8.14E-9 (18)
PN2 =  1.454E-5 (15)
PN3 =  8.81E-7 (19)

K =  0.88197 (27)
L =  0.09892 (14)
M =  0.01661 (10)
N =  0.002501 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  1.022 (31)
L1/b+ =  0.1133 (33)
L2/b+ =  0.001177 (37)
L3/b+ =  1.43E-4 (6)
M1/b+ =  0.01904 (47)
M2/b+ =  1.90E-4 (5)
M3/b+ =  2.05E-5 (7)
N1/b+ =  0.00288 (7)
M4/b+ =  9.44E-9 (34)
N2/b+ =  1.685E-5 (41)
N3/b+ =  1.021E-6 (36)

K/b+ =  1.022 (31)
L/b+ =  0.1147 (33)
M/b+ =  0.01925 (47)
N/b+ =  0.00290 (7)

EC/b+ =  1.159 (35)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.80 (41) %   Iec =   0.20 (10) %   Ib+ =   0.60 (40) %
Iec      =   0.20 (10) % (input data kept)
Ib+      =   0.60 (40) % (input data kept)
Iec tot. =   0.80 (41) % (input data kept)


---------------------
Capture probabilities

PK  =  0.473 (7)
PL1  =  0.0525 (7)
PL2  =  5.45E-4 (8)
PL3  =  6.62E-5 (11)
PM1  =  0.00882 (13)
PM2  =  8.79E-5 (13)
PM3  =  9.50E-6 (17)
PN1  =  0.001334 (24)
PM4  =  4.37E-9 (11)
PN2  =  7.80E-6 (14)
PN3  =  4.73E-7 (12)

K =  0.473 (7)
L =  0.0531 (7)
M =  0.00892 (13)
N =  0.001343 (24)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.1

Log ft value (ec)    =  9.47 (22)
with log f           =  2.007 (10)
and log partial T1/2 =  7.46 (22)

