--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 3441.50 (20) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 1522 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11055 (20)
PL2/PK =  0.0011367 (16)
PM1/PK =  0.01856 (11)
PM2/PK =  1.833E-4 (6)
PN1/PK =  0.002809 (33)
PN2/PK =  1.626E-5 (17)

L/K =  0.11169 (20)
M/K =  0.01875 (11)
N/K =  0.002825 (34)


------------------------------
Relative capture probabilities

PK  =  0.88241 (27)
PL1 =  0.09755 (15)
PL2 =  0.0010030 (18)
PM1 =  0.01638 (9)
PM2 =  1.6171E-4 (47)
PN1 =  0.002478 (29)
PN2 =  1.435E-5 (15)

K =  0.88241 (27)
L =  0.09855 (15)
M =  0.01654 (10)
N =  0.002493 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  13.1 (10)
L1/b+ =  1.45 (11)
L2/b+ =  0.0149 (12)
M1/b+ =  0.243 (17)
M2/b+ =  0.00240 (18)
N1/b+ =  0.0367 (27)
N2/b+ =  2.13E-4 (15)

K/b+ =  13.1 (10)
L/b+ =  1.46 (11)
M/b+ =  0.245 (17)
N/b+ =  0.0370 (27)

EC/b+ =  14.8 (11)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0960 (30) %   Iec =   0.090 (30) %   Ib+ =   0.0060 (20) %
Iec      =   0.090 (30) % (input data kept)
Ib+      =   0.0060 (20) % (input data kept)
Iec tot. =   0.096 (30) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8266 (40)
PL1  =  0.09139 (46)
PL2  =  9.396E-4 (48)
PM1  =  0.01535 (12)
PM2  =  1.515E-4 (9)
PN1  =  0.002322 (29)
PN2  =  1.344E-5 (15)

K =  0.8266 (40)
L =  0.09233 (47)
M =  0.01550 (12)
N =  0.002335 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.

Log ft value (ec)    =  7.98 (15)
with log f           =  0.173 (9)
and log partial T1/2 =  7.81 (14)

