--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 3913.0 (10) keV
Calculation of the allowed transition from the electron capture decay of Br-76

Transition energy: 1050 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11127 (21)
PL2/PK =  0.0011365 (17)
PM1/PK =  0.01870 (12)
PM2/PK =  1.834E-4 (6)
PN1/PK =  0.002830 (34)
PN2/PK =  1.627E-5 (18)

L/K =  0.11240 (21)
M/K =  0.01888 (12)
N/K =  0.002846 (34)


------------------------------
Relative capture probabilities

PK  =  0.88173 (28)
PL1 =  0.09811 (16)
PL2 =  0.0010021 (17)
PM1 =  0.01649 (10)
PM2 =  1.6168E-4 (47)
PN1 =  0.002495 (29)
PN2 =  1.435E-5 (15)

K =  0.88173 (28)
L =  0.09911 (15)
M =  0.01665 (10)
N =  0.002509 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0.4E7 (30)
L1/b+ =  0.5E6 (33)
L2/b+ =  0.5E4 (34)
M1/b+ =  0E5 (6)
M2/b+ =  0E3 (5)
N1/b+ =  1E4 (8)
N2/b+ =  0.7E2 (48)

K/b+ =  0.4E7 (30)
L/b+ =  0.5E6 (33)
M/b+ =  0E5 (6)
N/b+ =  1E4 (8)

EC/b+ =  0.5E7 (34)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.133 (15) %   Iec =   0.133 (15) %   Ib+ =   0. %
Iec      =   0.133 (15) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.133 (15) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88173 (28)
PL1  =  0.09811 (16)
PL2  =  0.0010021 (17)
PM1  =  0.01649 (10)
PM2  =  1.6168E-4 (47)
PN1  =  0.002495 (29)
PN2  =  1.435E-5 (15)

K =  0.88173 (28)
L =  0.09911 (15)
M =  0.01665 (10)
N =  0.002509 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.5

Log ft value (ec)    =  7.49 (5)
with log f           =  -0.152 (11)
and log partial T1/2 =  7.640 (49)

