--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 4199.60 (40) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 763 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11215 (23)
PL2/PK =  0.0011410 (19)
PM1/PK =  0.01887 (12)
PM2/PK =  1.843E-4 (6)
PN1/PK =  0.002855 (35)
PN2/PK =  1.635E-5 (18)

L/K =  0.11329 (23)
M/K =  0.01905 (12)
N/K =  0.002872 (35)


------------------------------
Relative capture probabilities

PK  =  0.88089 (30)
PL1 =  0.09879 (17)
PL2 =  0.0010051 (19)
PM1 =  0.01662 (10)
PM2 =  1.623E-4 (5)
PN1 =  0.002515 (30)
PN2 =  1.440E-5 (15)

K =  0.88089 (30)
L =  0.09980 (17)
M =  0.01678 (10)
N =  0.002530 (30)


------------------------------
Capture branch from input data

Iec =   0.360 (40) %


---------------------
Capture probabilities

PK  =  0.88089 (30)
PL1  =  0.09879 (17)
PL2  =  0.0010051 (19)
PM1  =  0.01662 (10)
PM2  =  1.623E-4 (5)
PN1  =  0.002515 (30)
PN2  =  1.440E-5 (15)

K =  0.88089 (30)
L =  0.09980 (17)
M =  0.01678 (10)
N =  0.002530 (30)


------------------------------------------------------------
Input log ft value (ec): 6.8

Log ft value (ec)    =  6.77 (5)
with log f           =  -0.433 (14)
and log partial T1/2 =  7.207 (49)

