--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 4084.30 (20) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 879 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11172 (22)
PL2/PK =  0.0011385 (18)
PM1/PK =  0.01879 (12)
PM2/PK =  1.838E-4 (6)
PN1/PK =  0.002843 (34)
PN2/PK =  1.631E-5 (18)

L/K =  0.11286 (22)
M/K =  0.01897 (12)
N/K =  0.002859 (35)


------------------------------
Relative capture probabilities

PK  =  0.88130 (29)
PL1 =  0.09846 (16)
PL2 =  0.0010033 (18)
PM1 =  0.01656 (10)
PM2 =  1.6196E-4 (48)
PN1 =  0.002505 (30)
PN2 =  1.437E-5 (15)

K =  0.88130 (29)
L =  0.09946 (16)
M =  0.01672 (10)
N =  0.002520 (30)


------------------------------
Capture branch from input data

Iec =   0.500 (40) %


---------------------
Capture probabilities

PK  =  0.88130 (29)
PL1  =  0.09846 (16)
PL2  =  0.0010033 (18)
PM1  =  0.01656 (10)
PM2  =  1.6196E-4 (48)
PN1  =  0.002505 (30)
PN2  =  1.437E-5 (15)

K =  0.88130 (29)
L =  0.09946 (16)
M =  0.01672 (10)
N =  0.002520 (30)


------------------------------------------------------------
Input log ft value (ec): 6.7

Log ft value (ec)    =  6.755 (37)
with log f           =  -0.309 (13)
and log partial T1/2 =  7.064 (35)

