--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [2+] 2127.215 (8) keV
The 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed

Transition energy: 2836 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10982 (19)
PL2/PK =  0.0011499 (17)
PM1/PK =  0.01843 (11)
PM2/PK =  1.852E-4 (6)
PN1/PK =  0.002788 (33)
PN2/PK =  1.644E-5 (18)

L/K =  0.11097 (19)
M/K =  0.01861 (11)
N/K =  0.002804 (33)


------------------------------
Relative capture probabilities

PK  =  0.88309 (26)
PL1 =  0.09698 (14)
PL2 =  0.0010155 (18)
PM1 =  0.01627 (9)
PM2 =  1.6359E-4 (48)
PN1 =  0.002462 (28)
PN2 =  1.451E-5 (15)

K =  0.88309 (26)
L =  0.09800 (14)
M =  0.01643 (9)
N =  0.002476 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1756 (42)
L1/b+ =  0.01928 (43)
L2/b+ =  2.02E-4 (5)
M1/b+ =  0.00324 (6)
M2/b+ =  3.25E-5 (7)
N1/b+ =  4.89E-4 (9)
N2/b+ =  2.89E-6 (5)

K/b+ =  0.1756 (42)
L/b+ =  0.01949 (43)
M/b+ =  0.00327 (6)
N/b+ =  4.92E-4 (9)

EC/b+ =  0.1988 (47)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.23 (11) %   Iec =   0.040 (20) %   Ib+ =   0.19 (11) %
Iec      =   0.040 (20) % (input data kept)
Ib+      =   0.19 (11) % (input data kept)
Iec tot. =   0.23 (11) % (input data kept)


---------------------
Capture probabilities

PK  =  0.1465 (29)
PL1  =  0.01609 (32)
PL2  =  1.684E-4 (33)
PM1  =  0.00270 (6)
PM2  =  2.71E-5 (5)
PN1  =  4.08E-4 (9)
PN2  =  2.41E-6 (5)

K =  0.1465 (29)
L =  0.01625 (32)
M =  0.00273 (6)
N =  4.11E-4 (9)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.9

Log ft value (ec)    =  8.88 (22)
with log f           =  0.719 (6)
and log partial T1/2 =  8.16 (22)

