--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4416.0 (20) keV
Calculation of the allowed transition from the electron capture decay of Br-76

Transition energy: 547 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11344 (28)
PL2/PK =  0.0011507 (23)
PM1/PK =  0.01911 (13)
PM2/PK =  1.861E-4 (7)
PN1/PK =  0.002893 (37)
PN2/PK =  1.652E-5 (19)

L/K =  0.11459 (27)
M/K =  0.01930 (13)
N/K =  0.002909 (37)


------------------------------
Relative capture probabilities

PK  =  0.87966 (34)
PL1 =  0.09979 (20)
PL2 =  0.0010123 (22)
PM1 =  0.01681 (11)
PM2 =  1.637E-4 (6)
PN1 =  0.002545 (31)
PN2 =  1.453E-5 (16)

K =  0.87966 (34)
L =  0.10080 (20)
M =  0.01697 (11)
N =  0.002559 (31)


------------------------------
Capture branch from input data

Iec =   0.26 (7) %


---------------------
Capture probabilities

PK  =  0.87966 (34)
PL1  =  0.09979 (20)
PL2  =  0.0010123 (22)
PM1  =  0.01681 (11)
PM2  =  1.637E-4 (6)
PN1  =  0.002545 (31)
PN2  =  1.453E-5 (16)

K =  0.87966 (34)
L =  0.10080 (20)
M =  0.01697 (11)
N =  0.002559 (31)


------------------------------------------------------------
Input log ft value (ec): 6.6

Log ft value (ec)    =  6.62 (12)
with log f           =  -0.728 (19)
and log partial T1/2 =  7.35 (12)

