--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 48-Cd-109 [5/2+] g.s.  -->  Daughter nucleus: 47-Ag-109 [7/2+] 88.034 keV
Calculation of the allowed transition from the electron capture decay of Cd-109

Transition energy: 127.5 (18) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1747 (13)
PL2/PK =  0.00360 (11)
PM1/PK =  0.03869 (44)
PM2/PK =  8.45E-4 (29)
PN1/PK =  0.00846 (13)
PN2/PK =  1.68E-4 (7)
PO1/PK =  5.35E-4 (15)

L/K =  0.1783 (14)
M/K =  0.03954 (47)
N/K =  0.00863 (14)
O/K =  5.35E-4 (15)


------------------------------
Relative capture probabilities

PK  =  0.8150 (14)
PL1 =  0.1424 (8)
PL2 =  0.00293 (9)
PM1 =  0.03154 (31)
PM2 =  6.89E-4 (23)
PN1 =  0.00690 (10)
PN2 =  1.37E-4 (5)
PO1 =  4.36E-4 (12)

K =  0.8150 (14)
L =  0.1453 (9)
M =  0.03222 (33)
N =  0.00703 (10)
O =  4.36E-4 (12)


------------------------------
Capture branch from input data

Iec =   100. %


---------------------
Capture probabilities

PK  =  0.8150 (14)
PL1  =  0.1424 (8)
PL2  =  0.00293 (9)
PM1  =  0.03154 (31)
PM2  =  6.89E-4 (23)
PN1  =  0.00690 (10)
PN2  =  1.37E-4 (5)
PO1  =  4.36E-4 (12)

K =  0.8150 (14)
L =  0.1453 (9)
M =  0.03222 (33)
N =  0.00703 (10)
O =  4.36E-4 (12)


------------------------------------------------------------
Input log ft value (ec): 6.

Log ft value (ec)    =  6.013 (25)
with log f           =  -1.588 (25)
and log partial T1/2 =  7.60106 (38)

