mcnp6 i=input_0keV.mcn r=run/run_0keV.r o=output/output_0keV.o
mcnp6 i=input_1keV.mcn r=run/run_1keV.r o=output/output_1keV.o
mcnp6 i=input_2keV.mcn r=run/run_2keV.r o=output/output_2keV.o
mcnp6 i=input_3keV.mcn r=run/run_3keV.r o=output/output_3keV.o
mcnp6 i=input_4keV.mcn r=run/run_4keV.r o=output/output_4keV.o
mcnp6 i=input_5keV.mcn r=run/run_5keV.r o=output/output_5keV.o
mcnp6 i=input_6keV.mcn r=run/run_6keV.r o=output/output_6keV.o
mcnp6 i=input_7keV.mcn r=run/run_7keV.r o=output/output_7keV.o
mcnp6 i=input_8keV.mcn r=run/run_8keV.r o=output/output_8keV.o
mcnp6 i=input_9keV.mcn r=run/run_9keV.r o=output/output_9keV.o
mcnp6 i=input_10keV.mcn r=run/run_10keV.r o=output/output_10keV.o
mcnp6 i=input_11keV.mcn r=run/run_11keV.r o=output/output_11keV.o
mcnp6 i=input_12keV.mcn r=run/run_12keV.r o=output/output_12keV.o
mcnp6 i=input_13keV.mcn r=run/run_13keV.r o=output/output_13keV.o
mcnp6 i=input_14keV.mcn r=run/run_14keV.r o=output/output_14keV.o
mcnp6 i=input_15keV.mcn r=run/run_15keV.r o=output/output_15keV.o
mcnp6 i=input_16keV.mcn r=run/run_16keV.r o=output/output_16keV.o
mcnp6 i=input_17keV.mcn r=run/run_17keV.r o=output/output_17keV.o
mcnp6 i=input_18keV.mcn r=run/run_18keV.r o=output/output_18keV.o
mcnp6 i=input_20keV.mcn r=run/run_20keV.r o=output/output_20keV.o
