--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-75 [5/2+] g.s.  -->  Daughter nucleus: 33-As-75 [7/2-] 821.60 (20) keV
The 1st forbidden non-unique transition from the electron capture decay of Se-75 is calculated as allowed

Transition energy: 42.0 (8) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1932 (29)
PL2/PK =  0.001840 (34)
PM1/PK =  0.0333 (6)
PM2/PK =  2.97E-4 (5)
PN1/PK =  0.00489 (12)
PN2/PK =  2.37E-5 (5)

L/K =  0.1951 (30)
M/K =  0.0336 (6)
N/K =  0.00491 (12)


------------------------------
Relative capture probabilities

PK  =  0.8106 (24)
PL1 =  0.1567 (19)
PL2 =  0.001492 (24)
PM1 =  0.02699 (40)
PM2 =  2.409E-4 (37)
PN1 =  0.00396 (9)
PN2 =  1.921E-5 (37)

K =  0.8106 (24)
L =  0.1581 (19)
M =  0.02723 (41)
N =  0.00398 (9)


------------------------------
Capture branch from input data

Iec =   0.00734 (18) %


---------------------
Capture probabilities

PK  =  0.8106 (24)
PL1  =  0.1567 (19)
PL2  =  0.001492 (24)
PM1  =  0.02699 (40)
PM2  =  2.409E-4 (37)
PN1  =  0.00396 (9)
PN2  =  1.921E-5 (37)

K =  0.8106 (24)
L =  0.1581 (19)
M =  0.02723 (41)
N =  0.00398 (9)


------------------------------------------------------------
Input log ft value (ec): 7.9

Log ft value (ec)    =  7.919 (28)
with log f           =  -3.230 (26)
and log partial T1/2 =  11.149 (11)

