--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-75 [5/2+] g.s.  -->  Daughter nucleus: 33-As-75 [3/2-] 264.6581 (10) keV
The 1st forbidden non-unique transition from the electron capture decay of Se-75 is calculated as allowed

Transition energy: 598.9 (8) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11216 (13)
PL2/PK =  0.0010691 (45)
PM1/PK =  0.018225 (48)
PM2/PK =  1.6366E-4 (37)
PN1/PK =  0.002654 (24)
PN2/PK =  1.297E-5 (9)

L/K =  0.11323 (13)
M/K =  0.018389 (47)
N/K =  0.002667 (24)


------------------------------
Relative capture probabilities

PK  =  0.88162 (15)
PL1 =  0.09888 (10)
PL2 =  9.425E-4 (41)
PM1 =  0.016067 (39)
PM2 =  1.4428E-4 (35)
PN1 =  0.002340 (21)
PN2 =  1.144E-5 (8)

K =  0.88162 (15)
L =  0.09982 (9)
M =  0.016212 (39)
N =  0.002351 (21)


------------------------------
Capture branch from input data

Iec =   1.40 (20) %


---------------------
Capture probabilities

PK  =  0.88162 (15)
PL1  =  0.09888 (10)
PL2  =  9.425E-4 (41)
PM1  =  0.016067 (39)
PM2  =  1.4428E-4 (35)
PN1  =  0.002340 (21)
PN2  =  1.144E-5 (8)

K =  0.88162 (15)
L =  0.09982 (9)
M =  0.016212 (39)
N =  0.002351 (21)


------------------------------------------------------------
Input log ft value (ec): 8.2

Log ft value (ec)    =  8.18 (6)
with log f           =  -0.6926 (44)
and log partial T1/2 =  8.87 (6)

