--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-75 [5/2+] g.s.  -->  Daughter nucleus: 33-As-75 [5/2-] 572.22 (24) keV
The 1st forbidden non-unique transition from the electron capture decay of Se-75 is calculated as allowed

Transition energy: 291.4 (8) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11640 (16)
PL2/PK =  0.0011051 (48)
PM1/PK =  0.01900 (5)
PM2/PK =  1.6989E-4 (42)
PN1/PK =  0.002768 (26)
PN2/PK =  1.347E-5 (9)

L/K =  0.11750 (15)
M/K =  0.01917 (5)
N/K =  0.002782 (26)


------------------------------
Relative capture probabilities

PK  =  0.87761 (18)
PL1 =  0.10215 (12)
PL2 =  9.699E-4 (44)
PM1 =  0.016675 (43)
PM2 =  1.4910E-4 (39)
PN1 =  0.002430 (22)
PN2 =  1.182E-5 (8)

K =  0.87761 (18)
L =  0.10312 (11)
M =  0.016824 (43)
N =  0.002441 (22)


------------------------------
Capture branch from input data

Iec =   0.03484 (35) %


---------------------
Capture probabilities

PK  =  0.87761 (18)
PL1  =  0.10215 (12)
PL2  =  9.699E-4 (44)
PM1  =  0.016675 (43)
PM2  =  1.4910E-4 (39)
PN1  =  0.002430 (22)
PN2  =  1.182E-5 (8)

K =  0.87761 (18)
L =  0.10312 (11)
M =  0.016824 (43)
N =  0.002441 (22)


------------------------------------------------------------
Input log ft value (ec): 9.1

Log ft value (ec)    =  9.138 (7)
with log f           =  -1.335 (6)
and log partial T1/2 =  10.4728 (44)

