--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-75 [5/2+] g.s.  -->  Daughter nucleus: 33-As-75 [5/2+] 400.6585 (8) keV
Calculation of the allowed transition from the electron capture decay of Se-75

Transition energy: 462.9 (8) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11331 (14)
PL2/PK =  0.0010781 (46)
PM1/PK =  0.018436 (49)
PM2/PK =  1.6523E-4 (38)
PN1/PK =  0.002685 (25)
PN2/PK =  1.310E-5 (9)

L/K =  0.11439 (13)
M/K =  0.018601 (49)
N/K =  0.002698 (25)


------------------------------
Relative capture probabilities

PK  =  0.88052 (16)
PL1 =  0.09977 (10)
PL2 =  9.493E-4 (42)
PM1 =  0.016233 (40)
PM2 =  1.4549E-4 (36)
PN1 =  0.002364 (21)
PN2 =  1.153E-5 (8)

K =  0.88052 (16)
L =  0.10072 (10)
M =  0.016379 (40)
N =  0.002376 (21)


------------------------------
Capture branch from input data

Iec =   94.5 (21) %


---------------------
Capture probabilities

PK  =  0.88052 (16)
PL1  =  0.09977 (10)
PL2  =  9.493E-4 (42)
PM1  =  0.016233 (40)
PM2  =  1.4549E-4 (36)
PN1  =  0.002364 (21)
PN2  =  1.153E-5 (8)

K =  0.88052 (16)
L =  0.10072 (10)
M =  0.016379 (40)
N =  0.002376 (21)


------------------------------------------------------------
Input log ft value (ec): 6.1

Log ft value (ec)    =  6.119 (11)
with log f           =  -0.9209 (47)
and log partial T1/2 =  7.039 (10)

