--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-75 [5/2+] g.s.  -->  Daughter nucleus: 33-As-75 [5/2-] 279.5428 (11) keV
The 1st forbidden non-unique transition from the electron capture decay of Se-75 is calculated as allowed

Transition energy: 584.1 (8) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11226 (13)
PL2/PK =  0.0010698 (45)
PM1/PK =  0.018243 (48)
PM2/PK =  1.6378E-4 (37)
PN1/PK =  0.002657 (24)
PN2/PK =  1.298E-5 (9)

L/K =  0.11333 (13)
M/K =  0.018407 (48)
N/K =  0.002669 (24)


------------------------------
Relative capture probabilities

PK  =  0.88152 (15)
PL1 =  0.09896 (10)
PL2 =  9.430E-4 (41)
PM1 =  0.016082 (39)
PM2 =  1.4438E-4 (35)
PN1 =  0.002342 (21)
PN2 =  1.145E-5 (8)

K =  0.88152 (15)
L =  0.09990 (9)
M =  0.016226 (39)
N =  0.002353 (21)


------------------------------
Capture branch from input data

Iec =   2.1 (14) %


---------------------
Capture probabilities

PK  =  0.88152 (15)
PL1  =  0.09896 (10)
PL2  =  9.430E-4 (41)
PM1  =  0.016082 (39)
PM2  =  1.4438E-4 (35)
PN1  =  0.002342 (21)
PN2  =  1.145E-5 (8)

K =  0.88152 (15)
L =  0.09990 (9)
M =  0.016226 (39)
N =  0.002353 (21)


------------------------------------------------------------
Input log ft value (ec): 8.

Log ft value (ec)    =  7.98 (29)
with log f           =  -0.7149 (44)
and log partial T1/2 =  8.69 (29)

