--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-75 [5/2+] g.s.  -->  Daughter nucleus: 33-As-75 [3/2-] g.s.
The 1st forbidden non-unique transition from the electron capture decay of Se-75 is calculated as allowed

Transition energy: 863.6 (8) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11097 (13)
PL2/PK =  0.0010617 (44)
PM1/PK =  0.018009 (47)
PM2/PK =  1.6233E-4 (36)
PN1/PK =  0.002622 (24)
PN2/PK =  1.287E-5 (9)

L/K =  0.11204 (12)
M/K =  0.018171 (46)
N/K =  0.002635 (24)


------------------------------
Relative capture probabilities

PK  =  0.88274 (15)
PL1 =  0.09796 (10)
PL2 =  9.372E-4 (40)
PM1 =  0.015897 (39)
PM2 =  1.4329E-4 (34)
PN1 =  0.002314 (21)
PN2 =  1.136E-5 (8)

K =  0.88274 (15)
L =  0.09890 (9)
M =  0.016040 (38)
N =  0.002326 (21)


------------------------------
Capture branch from input data

Iec =   1.42 (22) %


---------------------
Capture probabilities

PK  =  0.88274 (15)
PL1  =  0.09796 (10)
PL2  =  9.372E-4 (40)
PM1  =  0.015897 (39)
PM2  =  1.4329E-4 (34)
PN1  =  0.002314 (21)
PN2  =  1.136E-5 (8)

K =  0.88274 (15)
L =  0.09890 (9)
M =  0.016040 (38)
N =  0.002326 (21)


------------------------------------------------------------
Input log ft value (ec): 8.5

Log ft value (ec)    =  8.49 (7)
with log f           =  -0.3699 (40)
and log partial T1/2 =  8.86 (7)

