--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 93-Np-236m [1+] 6E1 (5) keV  -->  Daughter nucleus: 92-U-236 [1-] 687.60 (5) keV
The 1st forbidden non-unique transition from the electron capture decay of Np-236 is calculated as allowed

Transition energy: 3.0E2 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.40 (18)
PL2/PK =  0.044 (21)
PM1/PK =  0.11 (6)
PM2/PK =  0.014 (8)
PN1/PK =  0.034 (18)
PN2/PK =  0.0042 (24)
PO1/PK =  0.010 (5)
PO2/PK =  0.0012 (7)
PP1/PK =  0.0027 (15)
PP2/PK =  2.7E-4 (17)
PQ1/PK =  2.0E-4 (11)

L/K =  0.44 (20)
M/K =  0.13 (6)
N/K =  0.038 (20)
O/K =  0.011 (6)
P/K =  0.0029 (17)
Q/K =  2.0E-4 (11)


------------------------------
Relative capture probabilities

PK  =  0.62 (9)
PL1 =  0.25 (6)
PL2 =  0.027 (7)
PM1 =  0.069 (19)
PM2 =  0.0086 (26)
PN1 =  0.021 (6)
PN2 =  0.0026 (8)
PO1 =  0.0059 (18)
PO2 =  7.1E-4 (23)
PP1 =  0.0016 (5)
PP2 =  1.7E-4 (6)
PQ1 =  1.24E-4 (40)

K =  0.62 (9)
L =  0.27 (6)
M =  0.077 (21)
N =  0.023 (7)
O =  0.0066 (20)
P =  0.0018 (6)
Q =  1.24E-4 (40)


------------------------------
Capture branch from input data

Iec =   1.64 (9) %


---------------------
Capture probabilities

PK  =  0.62 (9)
PL1  =  0.25 (6)
PL2  =  0.027 (7)
PM1  =  0.069 (19)
PM2  =  0.0086 (26)
PN1  =  0.021 (6)
PN2  =  0.0026 (8)
PO1  =  0.0059 (18)
PO2  =  7.1E-4 (23)
PP1  =  0.0016 (5)
PP2  =  1.7E-4 (6)
PQ1  =  1.24E-4 (40)

K =  0.62 (9)
L =  0.27 (6)
M =  0.077 (21)
N =  0.023 (7)
O =  0.0066 (20)
P =  0.0018 (6)
Q =  1.24E-4 (40)


------------------------------------------------------------
Input log ft value (ec): 7.3

Log ft value (ec)    =  7.30 (34)
with log f           =  0.61 (34)
and log partial T1/2 =  6.694 (25)

