--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-57 [7/2-] g.s.  -->  Daughter nucleus: 26-Fe-57 [5/2-] 706.420 (20) keV
Calculation of the allowed transition from the electron capture decay of Co-57

Transition energy: 129.8 (5) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12235 (34)
PL2/PK =  6.588E-4 (35)
PM1/PK =  0.01943 (12)
PM2/PK =  9.93E-5 (9)
PN1/PK =  0.001267 (9)

L/K =  0.12300 (35)
M/K =  0.01953 (12)
N/K =  0.001267 (9)


------------------------------
Relative capture probabilities

PK  =  0.87428 (37)
PL1 =  0.10696 (25)
PL2 =  5.760E-4 (29)
PM1 =  0.01699 (10)
PM2 =  8.68E-5 (8)
PN1 =  0.001108 (8)

K =  0.87428 (37)
L =  0.10754 (26)
M =  0.01707 (10)
N =  0.001108 (8)


------------------------------
Capture branch from input data

Iec =   0.183 (7) %


---------------------
Capture probabilities

PK  =  0.87428 (37)
PL1  =  0.10696 (25)
PL2  =  5.760E-4 (29)
PM1  =  0.01699 (10)
PM2  =  8.68E-5 (8)
PN1  =  0.001108 (8)

K =  0.87428 (37)
L =  0.10754 (26)
M =  0.01707 (10)
N =  0.001108 (8)


------------------------------------------------------------
Input log ft value (ec): 7.692

Log ft value (ec)    =  7.692 (18)
with log f           =  -2.416 (6)
and log partial T1/2 =  10.108 (17)

