--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-57 [7/2-] g.s.  -->  Daughter nucleus: 26-Fe-57 [3/2-] 14.41950 (31) keV
The 2nd forbidden non-unique transition from the electron capture decay of Co-57 is calculated as 1st forbidden unique

Transition energy: 821.8 (5) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11435 (28)
PL2/PK =  6.173E-4 (31)
PL3/PK =  7.86E-4 (5)
PM1/PK =  0.01802 (11)
PM2/PK =  9.24E-5 (8)
PM3/PK =  1.054E-4 (12)
PN1/PK =  0.001174 (8)
PM4/PK =  1.656E-8 (21)

L/K =  0.11575 (29)
M/K =  0.01822 (11)
N/K =  0.001174 (8)


------------------------------
Relative capture probabilities

PK  =  0.88095 (31)
PL1 =  0.10073 (21)
PL2 =  5.438E-4 (25)
PL3 =  6.921E-4 (44)
PM1 =  0.01587 (9)
PM2 =  8.14E-5 (7)
PM3 =  9.29E-5 (10)
PN1 =  0.001034 (7)
PM4 =  1.459E-8 (18)

K =  0.88095 (31)
L =  0.10197 (22)
M =  0.01605 (9)
N =  0.001034 (7)


------------------------------
Capture branch from input data

Iec =   3.0000E-4 %


---------------------
Capture probabilities

PK  =  0.88095 (31)
PL1  =  0.10073 (21)
PL2  =  5.438E-4 (25)
PL3  =  6.921E-4 (44)
PM1  =  0.01587 (9)
PM2  =  8.14E-5 (7)
PM3  =  9.29E-5 (10)
PN1  =  0.001034 (7)
PM4  =  1.459E-8 (18)

K =  0.88095 (31)
L =  0.10197 (22)
M =  0.01605 (9)
N =  0.001034 (7)


------------------------------------------------------------
Input log ft value (ec): 12.524

Log ft value (ec)    =  12.5235 (34)
with log f           =  -0.3701 (34)
and log partial T1/2 =  12.89366 (6)

