--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-57 [7/2-] g.s.  -->  Daughter nucleus: 26-Fe-57 [3/2-] 366.740 (30) keV
The 2nd forbidden non-unique transition from the electron capture decay of Co-57 is calculated as 1st forbidden unique

Transition energy: 469.5 (5) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11698 (29)
PL2/PK =  6.292E-4 (32)
PL3/PK =  0.002457 (19)
PM1/PK =  0.01848 (11)
PM2/PK =  9.44E-5 (8)
PM3/PK =  3.301E-4 (40)
PN1/PK =  0.001205 (9)
PM4/PK =  5.19E-8 (7)

L/K =  0.12006 (31)
M/K =  0.01891 (12)
N/K =  0.001205 (9)


------------------------------
Relative capture probabilities

PK  =  0.87706 (33)
PL1 =  0.10260 (21)
PL2 =  5.519E-4 (26)
PL3 =  0.002155 (16)
PM1 =  0.01621 (9)
PM2 =  8.28E-5 (7)
PM3 =  2.895E-4 (34)
PN1 =  0.001057 (7)
PM4 =  4.55E-8 (6)

K =  0.87706 (33)
L =  0.10530 (23)
M =  0.01658 (9)
N =  0.001057 (7)


------------------------------
Capture branch from input data

Iec =   0.002 %


---------------------
Capture probabilities

PK  =  0.87706 (33)
PL1  =  0.10260 (21)
PL2  =  5.519E-4 (26)
PL3  =  0.002155 (16)
PM1  =  0.01621 (9)
PM2  =  8.28E-5 (7)
PM3  =  2.895E-4 (34)
PN1  =  0.001057 (7)
PM4  =  4.55E-8 (6)

K =  0.87706 (33)
L =  0.10530 (23)
M =  0.01658 (9)
N =  0.001057 (7)


------------------------------------------------------------
Input log ft value (ec): 10.718

Log ft value (ec)    =  10.7176 (42)
with log f           =  -1.3522 (42)
and log partial T1/2 =  12.06975 (6)

