--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-68 [1+] g.s.  -->  Daughter nucleus: 30-Zn-68 [0+] 1655.87 (14) keV
Calculation of the allowed transition from the electron capture decay of Ga-68

Transition energy: 1265.2 (12) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11163 (16)
PL2/PK =  8.36E-4 (31)
PM1/PK =  0.01849 (7)
PM2/PK =  1.35E-4 (5)
PN1/PK =  0.001482 (32)

L/K =  0.11247 (19)
M/K =  0.01862 (7)
N/K =  0.001482 (32)


------------------------------
Relative capture probabilities

PK  =  0.88295 (23)
PL1 =  0.09857 (12)
PL2 =  7.38E-4 (27)
PM1 =  0.01632 (6)
PM2 =  1.196E-4 (47)
PN1 =  0.001309 (28)

K =  0.88295 (23)
L =  0.09930 (14)
M =  0.01644 (6)
N =  0.001309 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  112 (5)
L1/b+ =  12.5 (6)
L2/b+ =  0.0936 (25)
M1/b+ =  2.07 (9)
M2/b+ =  0.01517 (45)
N1/b+ =  0.1660 (46)

K/b+ =  112 (5)
L/b+ =  12.6 (6)
M/b+ =  2.09 (9)
N/b+ =  0.1660 (46)

EC/b+ =  127 (6)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0338 (23) %   Iec =   0.0335 (23) %   Ib+ =   2.60E-4 (20) %
Iec      =   0.0335 (23) % (input data kept)
Ib+      =   2.60E-4 (20) % (input data kept)
Iec tot. =   0.0338 (23) % (input data kept)


---------------------
Capture probabilities

PK  =  0.87604 (40)
PL1  =  0.09780 (12)
PL2  =  7.32E-4 (27)
PM1  =  0.01619 (6)
PM2  =  1.186E-4 (47)
PN1  =  0.001299 (28)

K =  0.87604 (40)
L =  0.09853 (15)
M =  0.01631 (6)
N =  0.001299 (28)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.9

Log ft value (ec)    =  6.894 (33)
with log f           =  -0.190 (13)
and log partial T1/2 =  7.085 (30)

