--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-68 [1+] g.s.  -->  Daughter nucleus: 30-Zn-68 [2+] 2821.79 (14) keV
Calculation of the allowed transition from the electron capture decay of Ga-68

Transition energy: 99.3 (12) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13153 (49)
PL2/PK =  9.70E-4 (39)
PM1/PK =  0.02220 (14)
PM2/PK =  1.60E-4 (7)
PN1/PK =  0.001784 (43)

L/K =  0.1325 (5)
M/K =  0.02236 (15)
N/K =  0.001784 (43)


------------------------------
Relative capture probabilities

PK  =  0.8646 (5)
PL1 =  0.11371 (35)
PL2 =  8.39E-4 (33)
PM1 =  0.01919 (11)
PM2 =  1.38E-4 (6)
PN1 =  0.001543 (37)

K =  0.8646 (5)
L =  0.11455 (39)
M =  0.01933 (11)
N =  0.001543 (37)


------------------------------
Capture branch from input data

Iec =   0.0104 (5) %


---------------------
Capture probabilities

PK  =  0.8646 (5)
PL1  =  0.11371 (35)
PL2  =  8.39E-4 (33)
PM1  =  0.01919 (11)
PM2  =  1.38E-4 (6)
PN1  =  0.001543 (37)

K =  0.8646 (5)
L =  0.11455 (39)
M =  0.01933 (11)
N =  0.001543 (37)


------------------------------------------------------------
Input log ft value (ec): 5.1

Log ft value (ec)    =  5.120 (32)
with log f           =  -2.473 (24)
and log partial T1/2 =  7.593 (21)

