[Inputs]
nE_electron = 1000
nE_alpha = 1000
sp_model = tan_xia
chou_param = 0
ls_cocktail = Ultima Gold
solvantType = Water
solvantConc_mol_L = 0.0
density = 0.98
Z = 3.251556
A = 5.944938
pH = 0.569971
pC = 0.390337
pN = 0.000933
pO = 0.035279
pP = 0.002551
pS = 0.000463
pNa = 0.000465
pCl = 0.000000
micCorr = False
diam_micelle = 2
sigma_micelle = 1
fAq = 0.0
effQuantum = 0.25, 0.25, 0.25
opticalTransport = False
tau = 50
extDT = 30.0
measTime = 60
depthSpline = 5
Einterp_a = 100
Einterp_e = 1.5

