[Inputs]
nE_electron = 1000
nE_alpha = 1000
sp_model = tan_xia
chou_param = 0
ls_cocktail = False
solvantType = HCl
solvantConc = 0.1
density = 0.96
Z = 5.2
A = 11.04
pH = 0.578772
pC = 0.338741
pN = 0.000302
pO = 0.082022
pP = 0.000092
pS = 0.000000
pNa = 0.000000
pCl = 0.000071
micCorr = False
diam_micelle = 2
sigma_micelle = 1
fAq = 0.1
effQuantum = 0.1, 0.1, 0.1
optionModel = poisson
diffP = 1.0
PMTspace = 0.1
tau = 50
extDT = 10.0
measTime = 20
depthSpline = 5
Einterp_a = 100
Einterp_e = 1.5

