--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52m [2+] 377.749 (5) keV  -->  Daughter nucleus: 24-Cr-52 [2+] 3161.73 (6) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 1928.0 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11015 (29)
PL2/PK =  5.06E-4 (14)
PM1/PK =  0.01712 (10)
PM2/PK =  7.38E-5 (24)
PN1/PK =  0.001307 (25)

L/K =  0.11066 (30)
M/K =  0.01720 (10)
N/K =  0.001307 (25)


------------------------------
Relative capture probabilities

PK  =  0.88561 (34)
PL1 =  0.09755 (22)
PL2 =  4.48E-4 (12)
PM1 =  0.01517 (8)
PM2 =  6.53E-5 (21)
PN1 =  0.001157 (22)

K =  0.88561 (34)
L =  0.09800 (23)
M =  0.01523 (9)
N =  0.001157 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  0.3755 (44)
L1/b+ =  0.0414 (6)
L2/b+ =  1.90E-4 (8)
M1/b+ =  0.00643 (11)
M2/b+ =  2.77E-5 (12)
N1/b+ =  4.91E-4 (15)

K/b+ =  0.3755 (44)
L/b+ =  0.0416 (6)
M/b+ =  0.00646 (12)
N/b+ =  4.91E-4 (15)

EC/b+ =  0.424 (5)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.238 (11) %   Iec =   0.071 (8) %   Ib+ =   0.167 (8) %
Iec      =   0.071 (8) % (input data kept)
Ib+      =   0.167 (8) % (input data kept)
Iec tot. =   0.238 (11) % (input data kept)


---------------------
Capture probabilities

PK  =  0.2637 (22)
PL1  =  0.02905 (26)
PL2  =  1.335E-4 (38)
PM1  =  0.004516 (46)
PM2  =  1.95E-5 (6)
PN1  =  3.45E-4 (7)

K =  0.2637 (22)
L =  0.02918 (26)
M =  0.004535 (46)
N =  3.45E-4 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.082

Log ft value (ec)    =  6.073 (49)
with log f           =  -0.1783 (31)
and log partial T1/2 =  6.251 (49)

