--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52m [2+] 377.749 (5) keV  -->  Daughter nucleus: 24-Cr-52 [2+] 3771.69 (15) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 1318.1 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11043 (29)
PL2/PK =  5.03E-4 (14)
PM1/PK =  0.01717 (10)
PM2/PK =  7.33E-5 (24)
PN1/PK =  0.001310 (25)

L/K =  0.11093 (30)
M/K =  0.01725 (10)
N/K =  0.001310 (25)


------------------------------
Relative capture probabilities

PK  =  0.88536 (34)
PL1 =  0.09777 (22)
PL2 =  4.45E-4 (12)
PM1 =  0.01520 (8)
PM2 =  6.49E-5 (21)
PN1 =  0.001160 (22)

K =  0.88536 (34)
L =  0.09821 (23)
M =  0.01527 (9)
N =  0.001160 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  18.7 (6)
L1/b+ =  2.07 (7)
L2/b+ =  0.0094 (6)
M1/b+ =  0.322 (11)
M2/b+ =  0.00137 (9)
N1/b+ =  0.0246 (12)

K/b+ =  18.7 (6)
L/b+ =  2.08 (7)
M/b+ =  0.323 (12)
N/b+ =  0.0246 (12)

EC/b+ =  21.2 (6)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0087 (11) %   Iec =   0.0083 (11) %   Ib+ =   3.9E-4 (5) %
Iec      =   0.0083 (11) % (input data kept)
Ib+      =   3.9E-4 (5) % (input data kept)
Iec tot. =   0.0087 (11) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8454 (12)
PL1  =  0.09336 (24)
PL2  =  4.25E-4 (12)
PM1  =  0.01452 (8)
PM2  =  6.20E-5 (20)
PN1  =  0.001108 (21)

K =  0.8454 (12)
L =  0.09378 (25)
M =  0.01458 (8)
N =  0.001108 (21)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.67

Log ft value (ec)    =  6.67 (6)
with log f           =  -0.5104 (35)
and log partial T1/2 =  7.18 (6)

