--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52m [2+] 377.749 (5) keV  -->  Daughter nucleus: 24-Cr-52 [2+] 3951.2 (10) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 1138.5 (21) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11057 (29)
PL2/PK =  5.02E-4 (14)
PM1/PK =  0.01720 (10)
PM2/PK =  7.32E-5 (24)
PN1/PK =  0.001312 (25)

L/K =  0.11107 (30)
M/K =  0.01727 (10)
N/K =  0.001312 (25)


------------------------------
Relative capture probabilities

PK  =  0.88523 (34)
PL1 =  0.09788 (22)
PL2 =  4.44E-4 (12)
PM1 =  0.01522 (8)
PM2 =  6.48E-5 (21)
PN1 =  0.001162 (22)

K =  0.88523 (34)
L =  0.09832 (23)
M =  0.01529 (9)
N =  0.001162 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  7.4E2 (6)
L1/b+ =  82 (7)
L2/b+ =  0.371 (44)
M1/b+ =  12.7 (12)
M2/b+ =  0.054 (7)
N1/b+ =  0.97 (11)

K/b+ =  7.4E2 (6)
L/b+ =  82 (7)
M/b+ =  12.8 (12)
N/b+ =  0.97 (11)

EC/b+ =  8.3E2 (7)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   6.90E-4 (30) %   Iec =   6.9E-4 (30) %   Ib+ =   8.3E-7 (37) %
Iec      =   6.9E-4 (30) % (input data kept)
Ib+      =   8.3E-7 (37) % (input data kept)
Iec tot. =   6.9E-4 (30) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88417 (35)
PL1  =  0.09776 (22)
PL2  =  4.44E-4 (12)
PM1  =  0.01520 (8)
PM2  =  6.47E-5 (21)
PN1  =  0.001160 (22)

K =  0.88417 (35)
L =  0.09820 (23)
M =  0.01527 (9)
N =  0.001160 (22)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.63

Log ft value (ec)    =  7.63 (19)
with log f           =  -0.6383 (39)
and log partial T1/2 =  8.26 (19)

