--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52m [2+] 377.749 (5) keV  -->  Daughter nucleus: 24-Cr-52 [4+] 2369.6 (10) keV
The 2nd forbidden non-unique transition from the electron capture decay of Mn-52 is calculated as 1st forbidden unique

Transition energy: 2720.1 (21) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11040 (29)
PL2/PK =  5.11E-4 (14)
PL3/PK =  6.04E-5 (18)
PM1/PK =  0.01717 (10)
PM2/PK =  7.45E-5 (24)
PM3/PK =  7.81E-6 (27)
PN1/PK =  0.001310 (25)
PM4/PK =  8.39E-10 (7)

L/K =  0.11097 (30)
M/K =  0.01725 (10)
N/K =  0.001310 (25)


------------------------------
Relative capture probabilities

PK  =  0.88532 (34)
PL1 =  0.09774 (22)
PL2 =  4.53E-4 (12)
PL3 =  5.35E-5 (16)
PM1 =  0.01520 (8)
PM2 =  6.60E-5 (21)
PM3 =  6.91E-6 (24)
PN1 =  0.001160 (22)
PM4 =  7.43E-10 (6)

K =  0.88532 (34)
L =  0.09825 (23)
M =  0.01527 (9)
N =  0.001160 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1569 (15)
L1/b+ =  0.01733 (21)
L2/b+ =  8.02E-5 (30)
L3/b+ =  9.48E-6 (38)
M1/b+ =  0.002694 (41)
M2/b+ =  1.169E-5 (49)
M3/b+ =  1.22E-6 (6)
N1/b+ =  2.06E-4 (6)
M4/b+ =  1.317E-10 (24)

K/b+ =  0.1569 (15)
L/b+ =  0.01742 (21)
M/b+ =  0.002707 (42)
N/b+ =  2.06E-4 (6)

EC/b+ =  0.1773 (17)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.020 (9) %   Iec =   0.0030 (47) %   Ib+ =   0.017 (8) %
Iec      =   0.0030 (47) % (input data kept)
Ib+      =   0.017 (8) % (input data kept)
Iec tot. =   0.020 (9) % (input data kept)


---------------------
Capture probabilities

PK  =  0.1333 (11)
PL1  =  0.01472 (13)
PL2  =  6.81E-5 (19)
PL3  =  8.05E-6 (25)
PM1  =  0.002289 (23)
PM2  =  9.93E-6 (32)
PM3  =  1.041E-6 (37)
PN1  =  1.746E-4 (36)
PM4  =  1.119E-10 (13)

K =  0.1333 (11)
L =  0.01479 (13)
M =  0.002300 (23)
N =  1.746E-4 (36)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.21

Log ft value (ec)    =  9.2 (7)
with log f           =  1.5732 (36)
and log partial T1/2 =  7.6 (7)

