--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52m [2+] 377.749 (5) keV  -->  Daughter nucleus: 24-Cr-52 [2+] 4815.69 (9) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 274.1 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11384 (33)
PL2/PK =  5.10E-4 (15)
PM1/PK =  0.01776 (11)
PM2/PK =  7.46E-5 (25)
PN1/PK =  0.001356 (27)

L/K =  0.11435 (34)
M/K =  0.01784 (11)
N/K =  0.001356 (27)


------------------------------
Relative capture probabilities

PK  =  0.88219 (37)
PL1 =  0.10043 (24)
PL2 =  4.50E-4 (13)
PM1 =  0.01567 (9)
PM2 =  6.58E-5 (22)
PN1 =  0.001196 (23)

K =  0.88219 (37)
L =  0.10088 (26)
M =  0.01574 (9)
N =  0.001196 (23)


------------------------------
Capture branch from input data

Iec =   0.0049 (9) %


---------------------
Capture probabilities

PK  =  0.88219 (37)
PL1  =  0.10043 (24)
PL2  =  4.50E-4 (13)
PM1  =  0.01567 (9)
PM2  =  6.58E-5 (22)
PN1  =  0.001196 (23)

K =  0.88219 (37)
L =  0.10088 (26)
M =  0.01574 (9)
N =  0.001196 (23)


------------------------------------------------------------
Input log ft value (ec): 5.52

Log ft value (ec)    =  5.52 (8)
with log f           =  -1.888 (8)
and log partial T1/2 =  7.41 (8)

