--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52m [2+] 377.749 (5) keV  -->  Daughter nucleus: 24-Cr-52 [2+] 2964.777 (15) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 2125.0 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11010 (29)
PL2/PK =  5.07E-4 (14)
PM1/PK =  0.01712 (10)
PM2/PK =  7.39E-5 (24)
PN1/PK =  0.001306 (25)

L/K =  0.11061 (30)
M/K =  0.01719 (10)
N/K =  0.001306 (25)


------------------------------
Relative capture probabilities

PK  =  0.88566 (34)
PL1 =  0.09751 (22)
PL2 =  4.49E-4 (12)
PM1 =  0.01516 (8)
PM2 =  6.55E-5 (21)
PN1 =  0.001157 (22)

K =  0.88566 (34)
L =  0.09796 (23)
M =  0.01522 (9)
N =  0.001157 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1985 (21)
L1/b+ =  0.02186 (28)
L2/b+ =  1.007E-4 (39)
M1/b+ =  0.00340 (6)
M2/b+ =  1.47E-5 (6)
N1/b+ =  2.59E-4 (8)

K/b+ =  0.1985 (21)
L/b+ =  0.02196 (29)
M/b+ =  0.00341 (6)
N/b+ =  2.59E-4 (8)

EC/b+ =  0.2242 (24)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0466 (21) %   Iec =   0.0085 (12) %   Ib+ =   0.0381 (17) %
Iec      =   0.0085 (12) % (input data kept)
Ib+      =   0.0381 (17) % (input data kept)
Iec tot. =   0.0466 (21) % (input data kept)


---------------------
Capture probabilities

PK  =  0.1622 (14)
PL1  =  0.01786 (16)
PL2  =  8.23E-5 (24)
PM1  =  0.002776 (29)
PM2  =  1.199E-5 (40)
PN1  =  2.118E-4 (44)

K =  0.1622 (14)
L =  0.01794 (16)
M =  0.002788 (29)
N =  2.118E-4 (44)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.088

Log ft value (ec)    =  7.08 (6)
with log f           =  -0.0934 (30)
and log partial T1/2 =  7.17 (6)

