--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52m [2+] 377.749 (5) keV  -->  Daughter nucleus: 24-Cr-52 [3+] 3472.10 (20) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 1617.6 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11027 (29)
PL2/PK =  5.04E-4 (14)
PM1/PK =  0.01714 (10)
PM2/PK =  7.35E-5 (24)
PN1/PK =  0.001308 (25)

L/K =  0.11077 (30)
M/K =  0.01722 (10)
N/K =  0.001308 (25)


------------------------------
Relative capture probabilities

PK  =  0.88551 (34)
PL1 =  0.09764 (22)
PL2 =  4.47E-4 (12)
PM1 =  0.01518 (8)
PM2 =  6.51E-5 (21)
PN1 =  0.001158 (22)

K =  0.88551 (34)
L =  0.09809 (23)
M =  0.01525 (9)
N =  0.001158 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  1.532 (24)
L1/b+ =  0.1689 (31)
L2/b+ =  7.73E-4 (35)
M1/b+ =  0.0263 (6)
M2/b+ =  1.13E-4 (6)
N1/b+ =  0.00200 (7)

K/b+ =  1.532 (24)
L/b+ =  0.1697 (32)
M/b+ =  0.0264 (6)
N/b+ =  0.00200 (7)

EC/b+ =  1.730 (28)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.036 (9) %   Iec =   0.023 (8) %   Ib+ =   0.0132 (33) %
Iec      =   0.023 (8) % (input data kept)
Ib+      =   0.0132 (33) % (input data kept)
Iec tot. =   0.036 (9) % (input data kept)


---------------------
Capture probabilities

PK  =  0.5611 (34)
PL1  =  0.06188 (40)
PL2  =  2.83E-4 (8)
PM1  =  0.00962 (8)
PM2  =  4.12E-5 (13)
PN1  =  7.34E-4 (15)

K =  0.5611 (34)
L =  0.06216 (40)
M =  0.00966 (8)
N =  7.34E-4 (15)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.42

Log ft value (ec)    =  6.41 (15)
with log f           =  -0.3316 (33)
and log partial T1/2 =  6.74 (15)

