--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 28-Ni-57 [3/2-] g.s.  -->  Daughter nucleus: 27-Co-57 [3/2-] 1377.650 (30) keV
Calculation of the allowed transition from the electron capture decay of Ni-57

Transition energy: 1886.5 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11269 (25)
PL2/PK =  6.786E-4 (30)
PM1/PK =  0.01779 (10)
PM2/PK =  1.021E-4 (8)
PN1/PK =  0.001085 (7)

L/K =  0.11337 (26)
M/K =  0.01789 (10)
N/K =  0.001085 (7)


------------------------------
Relative capture probabilities

PK  =  0.88312 (28)
PL1 =  0.09952 (19)
PL2 =  5.993E-4 (25)
PM1 =  0.01571 (8)
PM2 =  9.02E-5 (7)
PN1 =  9.59E-4 (6)

K =  0.88312 (28)
L =  0.10012 (19)
M =  0.01580 (8)
N =  9.59E-4 (6)


--------------------------
Capture-to-positron ratios

K/b+ =  0.741 (11)
L1/b+ =  0.0836 (11)
L2/b+ =  5.03E-4 (5)
M1/b+ =  0.01319 (14)
M2/b+ =  7.57E-5 (10)
N1/b+ =  8.05E-4 (9)

K/b+ =  0.741 (11)
L/b+ =  0.0841 (11)
M/b+ =  0.01327 (14)
N/b+ =  8.05E-4 (9)

EC/b+ =  0.840 (13)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   64.6 (7) %   Iec =   29.3 (5) %   Ib+ =   35.3 (5) %
Iec      =   29.3 (5) % (input data kept)
Ib+      =   35.3 (5) % (input data kept)
Iec tot. =   64.6 (7) % (input data kept)


---------------------
Capture probabilities

PK  =  0.4031 (33)
PL1  =  0.04542 (38)
PL2  =  2.735E-4 (25)
PM1  =  0.00717 (7)
PM2  =  4.115E-5 (46)
PN1  =  4.375E-4 (44)

K =  0.4031 (33)
L =  0.04569 (38)
M =  0.00721 (7)
N =  4.375E-4 (44)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.6

Log ft value (ec)    =  5.650 (11)
with log f           =  0.0057 (33)
and log partial T1/2 =  5.645 (10)

