--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 28-Ni-57 [3/2-] g.s.  -->  Daughter nucleus: 27-Co-57 [5/2-] 2133.06 (5) keV
Calculation of the allowed transition from the electron capture decay of Ni-57

Transition energy: 1131.1 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11322 (26)
PL2/PK =  6.743E-4 (31)
PM1/PK =  0.01788 (10)
PM2/PK =  1.015E-4 (8)
PN1/PK =  0.001091 (7)

L/K =  0.11390 (26)
M/K =  0.01798 (10)
N/K =  0.001091 (7)


------------------------------
Relative capture probabilities

PK  =  0.88263 (28)
PL1 =  0.09994 (19)
PL2 =  5.952E-4 (25)
PM1 =  0.01578 (8)
PM2 =  8.96E-5 (7)
PN1 =  9.63E-4 (6)

K =  0.88263 (28)
L =  0.10053 (20)
M =  0.01587 (8)
N =  9.63E-4 (6)


--------------------------
Capture-to-positron ratios

K/b+ =  1.84E3 (21)
L1/b+ =  209 (23)
L2/b+ =  1.24 (14)
M1/b+ =  33.0 (36)
M2/b+ =  0.187 (21)
N1/b+ =  2.01 (22)

K/b+ =  1.84E3 (21)
L/b+ =  210 (23)
M/b+ =  33.1 (36)
N/b+ =  2.01 (22)

EC/b+ =  2.09E3 (24)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.039 (5) %   Iec =   0.039 (5) %   Ib+ =   0. %
Iec      =   0.039 (5) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.039 (5) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88221 (29)
PL1  =  0.09989 (19)
PL2  =  5.949E-4 (25)
PM1  =  0.01578 (8)
PM2  =  8.96E-5 (7)
PN1  =  9.63E-4 (6)

K =  0.88221 (29)
L =  0.10048 (20)
M =  0.01587 (8)
N =  9.63E-4 (6)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.1

Log ft value (ec)    =  8.08 (6)
with log f           =  -0.4414 (41)
and log partial T1/2 =  8.52 (6)

