--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 28-Ni-57 [3/2-] g.s.  -->  Daughter nucleus: 27-Co-57 [3/2-] 2730.83 (14) keV
Calculation of the allowed transition from the electron capture decay of Ni-57

Transition energy: 533.4 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11475 (27)
PL2/PK =  6.775E-4 (32)
PM1/PK =  0.01815 (10)
PM2/PK =  1.021E-4 (8)
PN1/PK =  0.001108 (7)

L/K =  0.11542 (27)
M/K =  0.01825 (10)
N/K =  0.001108 (7)


------------------------------
Relative capture probabilities

PK  =  0.88122 (30)
PL1 =  0.10112 (21)
PL2 =  5.970E-4 (26)
PM1 =  0.01600 (8)
PM2 =  9.00E-5 (7)
PN1 =  9.76E-4 (6)

K =  0.88122 (30)
L =  0.10171 (21)
M =  0.01609 (8)
N =  9.76E-4 (6)


------------------------------
Capture branch from input data

Iec =   0.0200 (30) %


---------------------
Capture probabilities

PK  =  0.88122 (30)
PL1  =  0.10112 (21)
PL2  =  5.970E-4 (26)
PM1  =  0.01600 (8)
PM2  =  9.00E-5 (7)
PN1  =  9.76E-4 (6)

K =  0.88122 (30)
L =  0.10171 (21)
M =  0.01609 (8)
N =  9.76E-4 (6)


------------------------------------------------------------
Input log ft value (ec): 7.7

Log ft value (ec)    =  7.71 (7)
with log f           =  -1.101 (6)
and log partial T1/2 =  8.81 (7)

