--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 28-Ni-57 [3/2-] g.s.  -->  Daughter nucleus: 27-Co-57 [3/2-] 2804.18 (6) keV
Calculation of the allowed transition from the electron capture decay of Ni-57

Transition energy: 460.0 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11521 (28)
PL2/PK =  6.796E-4 (32)
PM1/PK =  0.01823 (10)
PM2/PK =  1.025E-4 (8)
PN1/PK =  0.001113 (7)

L/K =  0.11589 (28)
M/K =  0.01834 (10)
N/K =  0.001113 (7)


------------------------------
Relative capture probabilities

PK  =  0.88079 (30)
PL1 =  0.10148 (21)
PL2 =  5.986E-4 (26)
PM1 =  0.01606 (8)
PM2 =  9.03E-5 (7)
PN1 =  9.80E-4 (6)

K =  0.88079 (30)
L =  0.10208 (21)
M =  0.01615 (9)
N =  9.80E-4 (6)


------------------------------
Capture branch from input data

Iec =   0.308 (23) %


---------------------
Capture probabilities

PK  =  0.88079 (30)
PL1  =  0.10148 (21)
PL2  =  5.986E-4 (26)
PM1  =  0.01606 (8)
PM2  =  9.03E-5 (7)
PN1  =  9.80E-4 (6)

K =  0.88079 (30)
L =  0.10208 (21)
M =  0.01615 (9)
N =  9.80E-4 (6)


------------------------------------------------------------
Input log ft value (ec): 6.4

Log ft value (ec)    =  6.392 (34)
with log f           =  -1.231 (7)
and log partial T1/2 =  7.623 (33)

