--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 28-Ni-57 [3/2-] g.s.  -->  Daughter nucleus: 27-Co-57 [1/2-] 1504.820 (30) keV
Calculation of the allowed transition from the electron capture decay of Ni-57

Transition energy: 1759.4 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11275 (25)
PL2/PK =  6.777E-4 (30)
PM1/PK =  0.01780 (10)
PM2/PK =  1.020E-4 (8)
PN1/PK =  0.001086 (7)

L/K =  0.11342 (26)
M/K =  0.01790 (10)
N/K =  0.001086 (7)


------------------------------
Relative capture probabilities

PK  =  0.88307 (28)
PL1 =  0.09956 (19)
PL2 =  5.984E-4 (25)
PM1 =  0.01572 (8)
PM2 =  9.01E-5 (7)
PN1 =  9.59E-4 (6)

K =  0.88307 (28)
L =  0.10016 (20)
M =  0.01581 (8)
N =  9.59E-4 (6)


--------------------------
Capture-to-positron ratios

K/b+ =  1.263 (22)
L1/b+ =  0.1424 (21)
L2/b+ =  8.56E-4 (11)
M1/b+ =  0.02248 (27)
M2/b+ =  1.288E-4 (19)
N1/b+ =  0.001372 (18)

K/b+ =  1.263 (22)
L/b+ =  0.1432 (21)
M/b+ =  0.02261 (28)
N/b+ =  0.001372 (18)

EC/b+ =  1.430 (24)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   16.4 (5) %   Iec =   9.60 (40) %   Ib+ =   6.80 (30) %
Iec      =   9.60 (40) % (input data kept)
Ib+      =   6.80 (30) % (input data kept)
Iec tot. =   16.4 (5) % (input data kept)


---------------------
Capture probabilities

PK  =  0.5197 (36)
PL1  =  0.05859 (42)
PL2  =  3.522E-4 (29)
PM1  =  0.00925 (8)
PM2  =  5.30E-5 (6)
PN1  =  5.64E-4 (5)

K =  0.5197 (36)
L =  0.05894 (42)
M =  0.00930 (8)
N =  5.64E-4 (5)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.1

Log ft value (ec)    =  6.074 (20)
with log f           =  -0.0553 (34)
and log partial T1/2 =  6.129 (19)

