--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 28-Ni-57 [3/2-] g.s.  -->  Daughter nucleus: 27-Co-57 [5/2-] 3177.31 (5) keV
Calculation of the allowed transition from the electron capture decay of Ni-57

Transition energy: 86.9 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1315 (10)
PL2/PK =  7.73E-4 (8)
PM1/PK =  0.02112 (24)
PM2/PK =  1.181E-4 (17)
PN1/PK =  0.001291 (16)

L/K =  0.1322 (10)
M/K =  0.02124 (24)
N/K =  0.001291 (16)


------------------------------
Relative capture probabilities

PK  =  0.8660 (9)
PL1 =  0.1138 (7)
PL2 =  6.69E-4 (6)
PM1 =  0.01829 (19)
PM2 =  1.023E-4 (13)
PN1 =  0.001118 (13)

K =  0.8660 (9)
L =  0.1145 (7)
M =  0.01839 (19)
N =  0.001118 (13)


------------------------------
Capture branch from input data

Iec =   0.025 (5) %


---------------------
Capture probabilities

PK  =  0.8660 (9)
PL1  =  0.1138 (7)
PL2  =  6.69E-4 (6)
PM1  =  0.01829 (19)
PM2  =  1.023E-4 (13)
PN1  =  0.001118 (13)

K =  0.8660 (9)
L =  0.1145 (7)
M =  0.01839 (19)
N =  0.001118 (13)


------------------------------------------------------------
Input log ft value (ec): 6.

Log ft value (ec)    =  5.98 (9)
with log f           =  -2.736 (31)
and log partial T1/2 =  8.71 (9)

