--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 28-Ni-57 [3/2-] g.s.  -->  Daughter nucleus: 27-Co-57 [3/2-] 3108.140 (40) keV
Calculation of the allowed transition from the electron capture decay of Ni-57

Transition energy: 156.1 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12215 (46)
PL2/PK =  7.180E-4 (44)
PM1/PK =  0.01946 (14)
PM2/PK =  1.089E-4 (11)
PN1/PK =  0.001189 (10)

L/K =  0.12287 (47)
M/K =  0.01957 (14)
N/K =  0.001189 (10)


------------------------------
Relative capture probabilities

PK  =  0.87441 (47)
PL1 =  0.10681 (35)
PL2 =  6.278E-4 (35)
PM1 =  0.01702 (11)
PM2 =  9.53E-5 (9)
PN1 =  0.001040 (8)

K =  0.87441 (47)
L =  0.10744 (35)
M =  0.01711 (11)
N =  0.001040 (8)


------------------------------
Capture branch from input data

Iec =   0.0630 (40) %


---------------------
Capture probabilities

PK  =  0.87441 (47)
PL1  =  0.10681 (35)
PL2  =  6.278E-4 (35)
PM1  =  0.01702 (11)
PM2  =  9.53E-5 (9)
PN1  =  0.001040 (8)

K =  0.87441 (47)
L =  0.10744 (35)
M =  0.01711 (11)
N =  0.001040 (8)


------------------------------------------------------------
Input log ft value (ec): 6.1

Log ft value (ec)    =  6.117 (33)
with log f           =  -2.195 (17)
and log partial T1/2 =  8.312 (28)

