--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 28-Ni-57 [3/2-] g.s.  -->  Daughter nucleus: 27-Co-57 [5/2-] 1919.470 (40) keV
Calculation of the allowed transition from the electron capture decay of Ni-57

Transition energy: 1344.7 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11301 (26)
PL2/PK =  6.752E-4 (31)
PM1/PK =  0.01785 (10)
PM2/PK =  1.016E-4 (8)
PN1/PK =  0.001089 (7)

L/K =  0.11369 (26)
M/K =  0.01795 (10)
N/K =  0.001089 (7)


------------------------------
Relative capture probabilities

PK  =  0.88283 (28)
PL1 =  0.09977 (19)
PL2 =  5.961E-4 (25)
PM1 =  0.01575 (8)
PM2 =  8.97E-5 (7)
PN1 =  9.61E-4 (6)

K =  0.88283 (28)
L =  0.10037 (20)
M =  0.01584 (8)
N =  9.61E-4 (6)


--------------------------
Capture-to-positron ratios

K/b+ =  23.9 (9)
L1/b+ =  2.70 (9)
L2/b+ =  0.0161 (5)
M1/b+ =  0.427 (13)
M2/b+ =  0.00243 (8)
N1/b+ =  0.0260 (8)

K/b+ =  23.9 (9)
L/b+ =  2.72 (9)
M/b+ =  0.429 (13)
N/b+ =  0.0260 (8)

EC/b+ =  27.1 (10)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   12.5 (6) %   Iec =   12.1 (6) %   Ib+ =   0.450 (30) %
Iec      =   12.1 (6) % (input data kept)
Ib+      =   0.450 (30) % (input data kept)
Iec tot. =   12.5 (6) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8514 (11)
PL1  =  0.09622 (22)
PL2  =  5.748E-4 (25)
PM1  =  0.01519 (8)
PM2  =  8.65E-5 (7)
PN1  =  9.27E-4 (6)

K =  0.8514 (11)
L =  0.09679 (23)
M =  0.01528 (8)
N =  9.27E-4 (6)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.7

Log ft value (ec)    =  5.739 (23)
with log f           =  -0.2902 (38)
and log partial T1/2 =  6.029 (23)

