--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 26-Fe-52 [0+] g.s.  -->  Daughter nucleus: 25-Mn-52 [1+] 546.438 (6) keV
Calculation of the allowed transition from the electron capture decay of Fe-52

Transition energy: 1829 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11079 (29)
PL2/PK =  5.581E-4 (30)
PM1/PK =  0.01730 (12)
PM2/PK =  8.24E-5 (8)
PN1/PK =  0.001211 (10)

L/K =  0.11135 (29)
M/K =  0.01738 (12)
N/K =  0.001211 (10)


------------------------------
Relative capture probabilities

PK  =  0.88500 (33)
PL1 =  0.09805 (22)
PL2 =  4.939E-4 (25)
PM1 =  0.01531 (10)
PM2 =  7.29E-5 (7)
PN1 =  0.001072 (8)

K =  0.88500 (33)
L =  0.09854 (22)
M =  0.01538 (10)
N =  0.001072 (8)


--------------------------
Capture-to-positron ratios

K/b+ =  0.692 (22)
L1/b+ =  0.0766 (22)
L2/b+ =  3.86E-4 (10)
M1/b+ =  0.01196 (31)
M2/b+ =  5.70E-5 (16)
N1/b+ =  8.38E-4 (22)

K/b+ =  0.692 (22)
L/b+ =  0.0770 (22)
M/b+ =  0.01202 (31)
N/b+ =  8.38E-4 (22)

EC/b+ =  0.782 (24)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   99.9 (15) %   Iec =   43.8 (13) %   Ib+ =   56.1 (7) %
Iec      =   43.8 (13) % (input data kept)
Ib+      =   56.1 (7) % (input data kept)
Iec tot. =   99.9 (15) % (input data kept)


---------------------
Capture probabilities

PK  =  0.388 (7)
PL1  =  0.0430 (8)
PL2  =  2.167E-4 (39)
PM1  =  0.00672 (12)
PM2  =  3.20E-5 (6)
PN1  =  4.70E-4 (9)

K =  0.388 (7)
L =  0.0432 (8)
M =  0.00675 (13)
N =  4.70E-4 (9)


------------------------------------------------------------
Input log ft value (ec & beta +): 4.7

Log ft value (ec)    =  4.698 (14)
with log f           =  -0.135 (5)
and log partial T1/2 =  4.832 (13)

