--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 26-Fe-52 [0+] g.s.  -->  Daughter nucleus: 25-Mn-52 [**] 1417.688 (18) keV
Calculation of the allowed transition from the electron capture decay of Fe-52

Transition energy: 957 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11142 (30)
PL2/PK =  5.539E-4 (30)
PM1/PK =  0.01741 (12)
PM2/PK =  8.18E-5 (8)
PN1/PK =  0.001219 (10)

L/K =  0.11197 (30)
M/K =  0.01749 (12)
N/K =  0.001219 (10)


------------------------------
Relative capture probabilities

PK  =  0.88442 (34)
PL1 =  0.09854 (23)
PL2 =  4.899E-4 (25)
PM1 =  0.01539 (10)
PM2 =  7.23E-5 (7)
PN1 =  0.001078 (8)

K =  0.88442 (34)
L =  0.09903 (23)
M =  0.01547 (10)
N =  0.001078 (8)


------------------------------
Capture branch from input data

Iec =   0.0950 (40) %


---------------------
Capture probabilities

PK  =  0.88442 (34)
PL1  =  0.09854 (23)
PL2  =  4.899E-4 (25)
PM1  =  0.01539 (10)
PM2  =  7.23E-5 (7)
PN1  =  0.001078 (8)

K =  0.88442 (34)
L =  0.09903 (23)
M =  0.01547 (10)
N =  0.001078 (8)


------------------------------------------------------------
Input log ft value (ec): 5.8

Log ft value (ec)    =  6.796 (20)
with log f           =  -0.700 (8)
and log partial T1/2 =  7.496 (18)

