--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 40-Zr-89 [9/2+] g.s.  -->  Daughter nucleus: 39-Y-89 [5/2-] 1744.74 (18) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of Zr-89

Transition energy: 1088.1 (28) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12128 (22)
PL2/PK =  0.001625 (10)
PL3/PK =  0.001004 (12)
PM1/PK =  0.02375 (13)
PM2/PK =  3.341E-4 (34)
PM3/PK =  1.899E-4 (30)
PN1/PK =  0.004201 (48)
PM4/PK =  2.125E-7 (47)
PN2/PK =  4.98E-5 (9)
PN3/PK =  2.44E-5 (6)
PO1/PK =  4.34E-4 (7)
PN4/PK =  3.05E-9 (5)

L/K =  0.12391 (24)
M/K =  0.02427 (14)
N/K =  0.004275 (49)
O/K =  4.34E-4 (7)


------------------------------
Relative capture probabilities

PK  =  0.86739 (32)
PL1 =  0.10519 (15)
PL2 =  0.001409 (8)
PL3 =  8.70E-4 (10)
PM1 =  0.02060 (11)
PM2 =  2.898E-4 (28)
PM3 =  1.647E-4 (26)
PN1 =  0.003644 (40)
PM4 =  1.843E-7 (41)
PN2 =  4.32E-5 (7)
PN3 =  2.11E-5 (5)
PO1 =  3.76E-4 (6)
PN4 =  2.645E-9 (44)

K =  0.86739 (32)
L =  0.10747 (17)
M =  0.02105 (11)
N =  0.003708 (41)
O =  3.76E-4 (6)


--------------------------
Capture-to-positron ratios

K/b+ =  3.1E6 (8)
L1/b+ =  3.7E5 (10)
L2/b+ =  5.0E3 (13)
L3/b+ =  3.1E3 (8)
M1/b+ =  7.3E4 (20)
M2/b+ =  1.03E3 (27)
M3/b+ =  5.9E2 (16)
N1/b+ =  1.30E4 (35)
M4/b+ =  0.66 (19)
N2/b+ =  154 (42)
N3/b+ =  75 (21)
O1/b+ =  1.34E3 (37)
N4/b+ =  0.0094 (26)

K/b+ =  3.1E6 (8)
L/b+ =  3.8E5 (10)
M/b+ =  7.5E4 (20)
N/b+ =  1.32E4 (35)
O/b+ =  1.34E3 (37)

EC/b+ =  3.6E6 (10)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.1230 (40) %   Iec =   0.1230 (40) %   Ib+ =   0. %
Iec      =   0.1230 (40) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.1230 (40) % (input data kept)


---------------------
Capture probabilities

PK  =  0.86739 (32)
PL1  =  0.10519 (15)
PL2  =  0.001409 (8)
PL3  =  8.70E-4 (10)
PM1  =  0.02060 (11)
PM2  =  2.898E-4 (28)
PM3  =  1.647E-4 (26)
PN1  =  0.003644 (40)
PM4  =  1.843E-7 (41)
PN2  =  4.32E-5 (7)
PN3  =  2.11E-5 (5)
PO1  =  3.76E-4 (6)
PN4  =  2.645E-9 (44)

K =  0.86739 (32)
L =  0.10747 (17)
M =  0.02105 (11)
N =  0.003708 (41)
O =  3.76E-4 (6)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.09

Log ft value (ec)    =  9.105 (16)
with log f           =  0.744 (8)
and log partial T1/2 =  8.361 (14)

