--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 40-Zr-89 [9/2+] g.s.  -->  Daughter nucleus: 39-Y-89 [9/2+] 908.970 (30) keV
Calculation of the allowed transition from the electron capture decay of Zr-89

Transition energy: 1923.8 (28) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11669 (19)
PL2/PK =  0.001588 (10)
PM1/PK =  0.02273 (12)
PM2/PK =  3.250E-4 (32)
PN1/PK =  0.004018 (45)
PN2/PK =  4.85E-5 (8)
PO1/PK =  4.15E-4 (6)

L/K =  0.11828 (20)
M/K =  0.02306 (12)
N/K =  0.004066 (46)
O/K =  4.15E-4 (6)


------------------------------
Relative capture probabilities

PK  =  0.87274 (29)
PL1 =  0.10184 (14)
PL2 =  0.001386 (8)
PM1 =  0.01984 (10)
PM2 =  2.837E-4 (27)
PN1 =  0.003507 (38)
PN2 =  4.23E-5 (7)
PO1 =  3.62E-4 (5)

K =  0.87274 (29)
L =  0.10323 (14)
M =  0.02012 (10)
N =  0.003549 (39)
O =  3.62E-4 (5)


--------------------------
Capture-to-positron ratios

K/b+ =  2.97 (6)
L1/b+ =  0.346 (6)
L2/b+ =  0.00471 (6)
M1/b+ =  0.0675 (10)
M2/b+ =  9.64E-4 (11)
N1/b+ =  0.01192 (15)
N2/b+ =  1.438E-4 (26)
O1/b+ =  0.001231 (21)

K/b+ =  2.97 (6)
L/b+ =  0.351 (6)
M/b+ =  0.0684 (10)
N/b+ =  0.01207 (15)
O/b+ =  0.001231 (21)

EC/b+ =  3.40 (7)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   99.00 (42) %   Iec =   76.20 (30) %   Ib+ =   22.80 (30) %
Iec      =   76.20 (30) % (input data kept)
Ib+      =   22.80 (30) % (input data kept)
Iec tot. =   99.00 (42) % (input data kept)


---------------------
Capture probabilities

PK  =  0.6744 (30)
PL1  =  0.07870 (36)
PL2  =  0.001071 (8)
PM1  =  0.01533 (10)
PM2  =  2.192E-4 (23)
PN1  =  0.002710 (32)
PN2  =  3.27E-5 (6)
PO1  =  2.797E-4 (44)

K =  0.6744 (30)
L =  0.07977 (37)
M =  0.01555 (10)
N =  0.002742 (32)
O =  2.797E-4 (44)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.152

Log ft value (ec)    =  6.169 (5)
with log f           =  0.600 (5)
and log partial T1/2 =  5.5688 (19)

