--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 40-Zr-89 [9/2+] g.s.  -->  Daughter nucleus: 39-Y-89 [7/2+] 2529.80 (20) keV
Calculation of the allowed transition from the electron capture decay of Zr-89

Transition energy: 303.0 (28) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12685 (33)
PL2/PK =  0.001692 (12)
PM1/PK =  0.02498 (16)
PM2/PK =  3.498E-4 (39)
PN1/PK =  0.00442 (5)
PN2/PK =  5.22E-5 (9)
PO1/PK =  4.57E-4 (8)

L/K =  0.12855 (34)
M/K =  0.02533 (16)
N/K =  0.00448 (6)
O/K =  4.57E-4 (8)


------------------------------
Relative capture probabilities

PK  =  0.86296 (42)
PL1 =  0.10947 (23)
PL2 =  0.001460 (10)
PM1 =  0.02156 (13)
PM2 =  3.018E-4 (32)
PN1 =  0.003817 (45)
PN2 =  4.51E-5 (8)
PO1 =  3.94E-4 (6)

K =  0.86296 (42)
L =  0.11093 (24)
M =  0.02186 (13)
N =  0.003862 (46)
O =  3.94E-4 (6)


------------------------------
Capture branch from input data

Iec =   0.074 (5) %


---------------------
Capture probabilities

PK  =  0.86296 (42)
PL1  =  0.10947 (23)
PL2  =  0.001460 (10)
PM1  =  0.02156 (13)
PM2  =  3.018E-4 (32)
PN1  =  0.003817 (45)
PN2  =  4.51E-5 (8)
PO1  =  3.94E-4 (6)

K =  0.86296 (42)
L =  0.11093 (24)
M =  0.02186 (13)
N =  0.003862 (46)
O =  3.94E-4 (6)


------------------------------------------------------------
Input log ft value (ec): 7.52

Log ft value (ec)    =  7.538 (32)
with log f           =  -1.044 (12)
and log partial T1/2 =  8.581 (29)

