--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [2+] 1956.797 (20) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 2446.2 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11279 (20)
PL2/PK =  0.001290 (12)
PM1/PK =  0.02178 (17)
PM2/PK =  2.565E-4 (6)
PN1/PK =  0.003119 (36)
PN2/PK =  2.558E-5 (16)

L/K =  0.11408 (19)
M/K =  0.02204 (17)
N/K =  0.003144 (37)


------------------------------
Relative capture probabilities

PK  =  0.87777 (30)
PL1 =  0.09900 (14)
PL2 =  0.001132 (11)
PM1 =  0.01912 (14)
PM2 =  2.251E-4 (6)
PN1 =  0.002737 (31)
PN2 =  2.245E-5 (13)

K =  0.87777 (30)
L =  0.10013 (13)
M =  0.01934 (14)
N =  0.002760 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  0.464 (6)
L1/b+ =  0.0524 (6)
L2/b+ =  5.99E-4 (13)
M1/b+ =  0.01011 (8)
M2/b+ =  1.190E-4 (18)
N1/b+ =  0.001448 (17)
N2/b+ =  1.187E-5 (8)

K/b+ =  0.464 (6)
L/b+ =  0.0530 (6)
M/b+ =  0.01023 (8)
N/b+ =  0.001459 (17)

EC/b+ =  0.529 (7)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0136 (8) %   Iec =   0.0047 (8) %   Ib+ =   0.00890 (14) %
Iec      =   0.0047 (8) % (input data kept)
Ib+      =   0.00890 (14) % (input data kept)
Iec tot. =   0.0136 (8) % (input data kept)


---------------------
Capture probabilities

PK  =  0.3036 (25)
PL1  =  0.03424 (29)
PL2  =  3.916E-4 (49)
PM1  =  0.00661 (7)
PM2  =  7.79E-5 (7)
PN1  =  9.47E-4 (13)
PN2  =  7.77E-6 (8)

K =  0.3036 (25)
L =  0.03464 (29)
M =  0.00669 (7)
N =  9.55E-4 (13)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.7

Log ft value (ec)    =  6.88 (7)
with log f           =  0.6721 (37)
and log partial T1/2 =  6.21 (7)

