--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 3911.1 (10) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 491.9 (32) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11744 (25)
PL2/PK =  0.001308 (13)
PM1/PK =  0.02280 (19)
PM2/PK =  2.614E-4 (8)
PN1/PK =  0.003267 (39)
PN2/PK =  2.609E-5 (16)

L/K =  0.11875 (23)
M/K =  0.02306 (18)
N/K =  0.003293 (40)


------------------------------
Relative capture probabilities

PK  =  0.87328 (35)
PL1 =  0.10256 (17)
PL2 =  0.001142 (11)
PM1 =  0.01991 (15)
PM2 =  2.283E-4 (8)
PN1 =  0.002853 (33)
PN2 =  2.278E-5 (13)

K =  0.87328 (35)
L =  0.10370 (16)
M =  0.02014 (15)
N =  0.002876 (33)


------------------------------
Capture branch from input data

Iec =   1.00E-4 (20) %


---------------------
Capture probabilities

PK  =  0.87328 (35)
PL1  =  0.10256 (17)
PL2  =  0.001142 (11)
PM1  =  0.01991 (15)
PM2  =  2.283E-4 (8)
PN1  =  0.002853 (33)
PN2  =  2.278E-5 (13)

K =  0.87328 (35)
L =  0.10370 (16)
M =  0.02014 (15)
N =  0.002876 (33)


------------------------------------------------------------
Input log ft value (ec): 7.1

Log ft value (ec)    =  7.14 (9)
with log f           =  -0.741 (8)
and log partial T1/2 =  7.88 (9)

