--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [0+] 2450.09 (9) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 1952.9 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11307 (20)
PL2/PK =  0.001284 (12)
PM1/PK =  0.02184 (17)
PM2/PK =  2.555E-4 (6)
PN1/PK =  0.003128 (37)
PN2/PK =  2.548E-5 (15)

L/K =  0.11436 (19)
M/K =  0.02210 (17)
N/K =  0.003153 (37)


------------------------------
Relative capture probabilities

PK  =  0.87749 (30)
PL1 =  0.09922 (14)
PL2 =  0.001127 (11)
PM1 =  0.01917 (14)
PM2 =  2.242E-4 (6)
PN1 =  0.002744 (31)
PN2 =  2.236E-5 (13)

K =  0.87749 (30)
L =  0.10035 (13)
M =  0.01939 (14)
N =  0.002767 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  1.861 (32)
L1/b+ =  0.2104 (33)
L2/b+ =  0.00239 (6)
M1/b+ =  0.0406 (5)
M2/b+ =  4.75E-4 (9)
N1/b+ =  0.00582 (9)
N2/b+ =  4.74E-5 (5)

K/b+ =  1.861 (32)
L/b+ =  0.2128 (33)
M/b+ =  0.0411 (5)
N/b+ =  0.00587 (9)

EC/b+ =  2.121 (36)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0155 (9) %   Iec =   0.0105 (8) %   Ib+ =   0.00500 (40) %
Iec      =   0.0105 (8) % (input data kept)
Ib+      =   0.00500 (40) % (input data kept)
Iec tot. =   0.0155 (9) % (input data kept)


---------------------
Capture probabilities

PK  =  0.5963 (32)
PL1  =  0.06743 (38)
PL2  =  7.66E-4 (8)
PM1  =  0.01303 (12)
PM2  =  1.524E-4 (9)
PN1  =  0.001865 (23)
PN2  =  1.520E-5 (12)

K =  0.5963 (32)
L =  0.06819 (38)
M =  0.01318 (12)
N =  0.001880 (24)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.3

Log ft value (ec)    =  6.334 (33)
with log f           =  0.4747 (40)
and log partial T1/2 =  5.859 (33)

