--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 2479.720 (30) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 1923.3 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11309 (20)
PL2/PK =  0.001284 (12)
PM1/PK =  0.02185 (17)
PM2/PK =  2.555E-4 (6)
PN1/PK =  0.003128 (37)
PN2/PK =  2.548E-5 (15)

L/K =  0.11438 (19)
M/K =  0.02210 (17)
N/K =  0.003154 (37)


------------------------------
Relative capture probabilities

PK  =  0.87747 (30)
PL1 =  0.09924 (14)
PL2 =  0.001127 (11)
PM1 =  0.01917 (14)
PM2 =  2.242E-4 (6)
PN1 =  0.002745 (31)
PN2 =  2.236E-5 (13)

K =  0.87747 (30)
L =  0.10036 (13)
M =  0.01939 (14)
N =  0.002767 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  2.075 (37)
L1/b+ =  0.2346 (37)
L2/b+ =  0.00266 (7)
M1/b+ =  0.0453 (6)
M2/b+ =  5.30E-4 (11)
N1/b+ =  0.00649 (11)
N2/b+ =  5.29E-5 (6)

K/b+ =  2.075 (37)
L/b+ =  0.2373 (38)
M/b+ =  0.0459 (6)
N/b+ =  0.00654 (11)

EC/b+ =  2.364 (41)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0970 (16) %   Iec =   0.0682 (14) %   Ib+ =   0.0288 (7) %
Iec      =   0.0682 (14) % (input data kept)
Ib+      =   0.0288 (7) % (input data kept)
Iec tot. =   0.0970 (16) % (input data kept)


---------------------
Capture probabilities

PK  =  0.6167 (32)
PL1  =  0.06974 (37)
PL2  =  7.92E-4 (9)
PM1  =  0.01347 (12)
PM2  =  1.575E-4 (9)
PN1  =  0.001929 (24)
PN2  =  1.571E-5 (12)

K =  0.6167 (32)
L =  0.07053 (37)
M =  0.01363 (12)
N =  0.001945 (24)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.5

Log ft value (ec)    =  5.508 (10)
with log f           =  0.4612 (40)
and log partial T1/2 =  5.047 (9)

