--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [0+] 1487.62 (7) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 2915.4 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11260 (20)
PL2/PK =  0.001296 (12)
PM1/PK =  0.02174 (17)
PM2/PK =  2.576E-4 (6)
PN1/PK =  0.003113 (36)
PN2/PK =  2.569E-5 (16)

L/K =  0.11390 (19)
M/K =  0.02200 (17)
N/K =  0.003138 (37)


------------------------------
Relative capture probabilities

PK  =  0.87793 (30)
PL1 =  0.09886 (14)
PL2 =  0.001138 (11)
PM1 =  0.01909 (14)
PM2 =  2.262E-4 (6)
PN1 =  0.002733 (31)
PN2 =  2.256E-5 (13)

K =  0.87793 (30)
L =  0.10000 (13)
M =  0.01931 (14)
N =  0.002755 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1900 (21)
L1/b+ =  0.02139 (20)
L2/b+ =  2.461E-4 (49)
M1/b+ =  0.004130 (26)
M2/b+ =  4.89E-5 (7)
N1/b+ =  5.91E-4 (6)
N2/b+ =  4.879E-6 (25)

K/b+ =  0.1900 (21)
L/b+ =  0.02164 (21)
M/b+ =  0.004179 (26)
N/b+ =  5.96E-4 (6)

EC/b+ =  0.2164 (24)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0540 (42) %   Iec =   0.0096 (9) %   Ib+ =   0.0444 (41) %
Iec      =   0.0096 (9) % (input data kept)
Ib+      =   0.0444 (41) % (input data kept)
Iec tot. =   0.0540 (42) % (input data kept)


---------------------
Capture probabilities

PK  =  0.1562 (14)
PL1  =  0.01759 (16)
PL2  =  2.024E-4 (26)
PM1  =  0.003395 (39)
PM2  =  4.023E-5 (38)
PN1  =  4.86E-4 (7)
PN2  =  4.012E-6 (43)

K =  0.1562 (14)
L =  0.01779 (16)
M =  0.003435 (40)
N =  4.90E-4 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.7

Log ft value (ec)    =  6.724 (41)
with log f           =  0.8260 (35)
and log partial T1/2 =  5.898 (41)

