--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [**] 2509.0 (5) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 1894.0 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11312 (20)
PL2/PK =  0.001284 (12)
PM1/PK =  0.02185 (17)
PM2/PK =  2.554E-4 (6)
PN1/PK =  0.003129 (37)
PN2/PK =  2.547E-5 (15)

L/K =  0.11440 (19)
M/K =  0.02211 (17)
N/K =  0.003154 (37)


------------------------------
Relative capture probabilities

PK  =  0.87745 (30)
PL1 =  0.09925 (14)
PL2 =  0.001127 (11)
PM1 =  0.01917 (14)
PM2 =  2.241E-4 (6)
PN1 =  0.002746 (31)
PN2 =  2.235E-5 (13)

K =  0.87745 (30)
L =  0.10038 (13)
M =  0.01940 (14)
N =  0.002768 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  2.319 (42)
L1/b+ =  0.2623 (43)
L2/b+ =  0.00298 (8)
M1/b+ =  0.0507 (7)
M2/b+ =  5.92E-4 (12)
N1/b+ =  0.00726 (13)
N2/b+ =  5.91E-5 (7)

K/b+ =  2.319 (42)
L/b+ =  0.2653 (44)
M/b+ =  0.0513 (7)
N/b+ =  0.00732 (13)

EC/b+ =  2.643 (47)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0015 (6) %   Iec =   0.0011 (6) %   Ib+ =   4.1E-4 (25) %
Iec      =   0.0011 (6) % (input data kept)
Ib+      =   4.1E-4 (25) % (input data kept)
Iec tot. =   0.0015 (7) % (input data kept)


---------------------
Capture probabilities

PK  =  0.6366 (31)
PL1  =  0.07201 (37)
PL2  =  8.17E-4 (9)
PM1  =  0.01391 (12)
PM2  =  1.626E-4 (9)
PN1  =  0.001992 (25)
PN2  =  1.622E-5 (12)

K =  0.6366 (31)
L =  0.07283 (37)
M =  0.01407 (12)
N =  0.002008 (25)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.4

Log ft value (ec)    =  7.29 (24)
with log f           =  0.4478 (40)
and log partial T1/2 =  6.84 (24)

