--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [0+] 3186.82 (5) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 1216.2 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11394 (21)
PL2/PK =  0.001281 (12)
PM1/PK =  0.02203 (17)
PM2/PK =  2.551E-4 (7)
PN1/PK =  0.003155 (37)
PN2/PK =  2.545E-5 (15)

L/K =  0.11522 (19)
M/K =  0.02229 (17)
N/K =  0.003181 (37)


------------------------------
Relative capture probabilities

PK  =  0.87666 (31)
PL1 =  0.09989 (15)
PL2 =  0.001123 (11)
PM1 =  0.01932 (14)
PM2 =  2.237E-4 (7)
PN1 =  0.002766 (31)
PN2 =  2.231E-5 (12)

K =  0.87666 (31)
L =  0.10101 (13)
M =  0.01954 (14)
N =  0.002788 (32)


--------------------------
Capture-to-positron ratios

K/b+ =  668 (49)
L1/b+ =  76 (5)
L2/b+ =  0.86 (7)
M1/b+ =  14.7 (10)
M2/b+ =  0.170 (13)
N1/b+ =  2.11 (15)
N2/b+ =  0.0170 (12)

K/b+ =  668 (49)
L/b+ =  77 (6)
M/b+ =  14.9 (10)
N/b+ =  2.13 (16)

EC/b+ =  7.6E2 (6)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0265 (15) %   Iec =   0.0265 (15) %   Ib+ =   0. %
Iec      =   0.0265 (15) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.0265 (15) % (input data kept)


---------------------
Capture probabilities

PK  =  0.87551 (32)
PL1  =  0.09976 (15)
PL2  =  0.001122 (11)
PM1  =  0.01929 (14)
PM2  =  2.234E-4 (7)
PN1  =  0.002762 (31)
PN2  =  2.228E-5 (12)

K =  0.87551 (32)
L =  0.10088 (13)
M =  0.01951 (14)
N =  0.002785 (32)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.5

Log ft value (ec)    =  5.516 (25)
with log f           =  0.0591 (48)
and log partial T1/2 =  5.457 (25)

