--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [**] 3741.96 (8) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 661.0 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11592 (22)
PL2/PK =  0.001294 (12)
PM1/PK =  0.02246 (18)
PM2/PK =  2.582E-4 (7)
PN1/PK =  0.003218 (38)
PN2/PK =  2.576E-5 (16)

L/K =  0.11721 (21)
M/K =  0.02272 (18)
N/K =  0.003244 (38)


------------------------------
Relative capture probabilities

PK  =  0.87476 (33)
PL1 =  0.10140 (16)
PL2 =  0.001132 (11)
PM1 =  0.01965 (15)
PM2 =  2.258E-4 (7)
PN1 =  0.002815 (32)
PN2 =  2.253E-5 (13)

K =  0.87476 (33)
L =  0.10253 (15)
M =  0.01988 (15)
N =  0.002838 (32)


------------------------------
Capture branch from input data

Iec =   0.0036 (6) %


---------------------
Capture probabilities

PK  =  0.87476 (33)
PL1  =  0.10140 (16)
PL2  =  0.001132 (11)
PM1  =  0.01965 (15)
PM2  =  2.258E-4 (7)
PN1  =  0.002815 (32)
PN2  =  2.253E-5 (13)

K =  0.87476 (33)
L =  0.10253 (15)
M =  0.01988 (15)
N =  0.002838 (32)


------------------------------------------------------------
Input log ft value (ec): 5.9

Log ft value (ec)    =  5.85 (7)
with log f           =  -0.478 (7)
and log partial T1/2 =  6.32 (7)

