--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 3881.1 (5) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 521.9 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11710 (24)
PL2/PK =  0.001305 (12)
PM1/PK =  0.02272 (18)
PM2/PK =  2.606E-4 (8)
PN1/PK =  0.003256 (39)
PN2/PK =  2.601E-5 (16)

L/K =  0.11840 (23)
M/K =  0.02298 (18)
N/K =  0.003282 (39)


------------------------------
Relative capture probabilities

PK  =  0.87362 (34)
PL1 =  0.10230 (17)
PL2 =  0.001140 (11)
PM1 =  0.01985 (15)
PM2 =  2.277E-4 (7)
PN1 =  0.002844 (33)
PN2 =  2.272E-5 (13)

K =  0.87362 (34)
L =  0.10344 (16)
M =  0.02008 (15)
N =  0.002867 (33)


------------------------------
Capture branch from input data

Iec =   2.4E-4 (5) %


---------------------
Capture probabilities

PK  =  0.87362 (34)
PL1  =  0.10230 (17)
PL2  =  0.001140 (11)
PM1  =  0.01985 (15)
PM2  =  2.277E-4 (7)
PN1  =  0.002844 (33)
PN2  =  2.272E-5 (13)

K =  0.87362 (34)
L =  0.10344 (16)
M =  0.02008 (15)
N =  0.002867 (33)


------------------------------------------------------------
Input log ft value (ec): 6.8

Log ft value (ec)    =  6.81 (9)
with log f           =  -0.688 (8)
and log partial T1/2 =  7.50 (9)

