--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 3835.8 (5) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 567.2 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11665 (23)
PL2/PK =  0.001301 (12)
PM1/PK =  0.02262 (18)
PM2/PK =  2.597E-4 (7)
PN1/PK =  0.003241 (39)
PN2/PK =  2.591E-5 (16)

L/K =  0.11795 (22)
M/K =  0.02288 (18)
N/K =  0.003267 (39)


------------------------------
Relative capture probabilities

PK  =  0.87405 (34)
PL1 =  0.10196 (16)
PL2 =  0.001137 (11)
PM1 =  0.01977 (15)
PM2 =  2.270E-4 (7)
PN1 =  0.002833 (33)
PN2 =  2.265E-5 (13)

K =  0.87405 (34)
L =  0.10309 (15)
M =  0.02000 (15)
N =  0.002856 (33)


------------------------------
Capture branch from input data

Iec =   8.9E-4 (5) %


---------------------
Capture probabilities

PK  =  0.87405 (34)
PL1  =  0.10196 (16)
PL2  =  0.001137 (11)
PM1  =  0.01977 (15)
PM2  =  2.270E-4 (7)
PN1  =  0.002833 (33)
PN2  =  2.265E-5 (13)

K =  0.87405 (34)
L =  0.10309 (15)
M =  0.02000 (15)
N =  0.002856 (33)


------------------------------------------------------------
Input log ft value (ec): 6.3

Log ft value (ec)    =  6.317 (26)
with log f           =  -0.614 (7)
and log partial T1/2 =  6.931 (24)

