--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [2+] 776.522 (10) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 3626.5 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11242 (20)
PL2/PK =  0.001306 (12)
PM1/PK =  0.02170 (17)
PM2/PK =  2.596E-4 (6)
PN1/PK =  0.003107 (36)
PN2/PK =  2.589E-5 (16)

L/K =  0.11373 (19)
M/K =  0.02196 (17)
N/K =  0.003133 (36)


------------------------------
Relative capture probabilities

PK  =  0.87810 (30)
PL1 =  0.09872 (14)
PL2 =  0.001147 (11)
PM1 =  0.01906 (14)
PM2 =  2.279E-4 (6)
PN1 =  0.002728 (31)
PN2 =  2.273E-5 (13)

K =  0.87810 (30)
L =  0.09986 (13)
M =  0.01928 (14)
N =  0.002751 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  0.0718 (7)
L1/b+ =  0.00807 (7)
L2/b+ =  9.37E-5 (17)
M1/b+ =  0.001557 (7)
M2/b+ =  1.862E-5 (22)
N1/b+ =  2.229E-4 (19)
N2/b+ =  1.857E-6 (7)

K/b+ =  0.0718 (7)
L/b+ =  0.00816 (7)
M/b+ =  0.001576 (7)
N/b+ =  2.248E-4 (20)

EC/b+ =  0.0817 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   14.16 (19) %   Iec =   1.060 (20) %   Ib+ =   13.10 (19) %
Iec      =   1.060 (20) % (input data kept)
Ib+      =   13.10 (19) % (input data kept)
Iec tot. =   14.16 (19) % (input data kept)


---------------------
Capture probabilities

PK  =  0.0663 (6)
PL1  =  0.00746 (7)
PL2  =  8.66E-5 (11)
PM1  =  0.001439 (17)
PM2  =  1.722E-5 (16)
PN1  =  2.061E-4 (30)
PN2  =  1.717E-6 (18)

K =  0.0663 (6)
L =  0.00754 (7)
M =  0.001457 (17)
N =  2.078E-4 (30)


------------------------------------------------------------
Input log ft value (ec & beta +): 4.8

Log ft value (ec)    =  4.873 (9)
with log f           =  1.0178 (34)
and log partial T1/2 =  3.855 (8)

