--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [0+] g.s.
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 4403.0 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11229 (20)
PL2/PK =  0.001317 (12)
PM1/PK =  0.02167 (17)
PM2/PK =  2.618E-4 (6)
PN1/PK =  0.003103 (36)
PN2/PK =  2.611E-5 (16)

L/K =  0.11360 (19)
M/K =  0.02193 (17)
N/K =  0.003129 (36)


------------------------------
Relative capture probabilities

PK  =  0.87822 (30)
PL1 =  0.09861 (14)
PL2 =  0.001157 (11)
PM1 =  0.01903 (14)
PM2 =  2.299E-4 (6)
PN1 =  0.002725 (31)
PN2 =  2.293E-5 (14)

K =  0.87822 (30)
L =  0.09977 (13)
M =  0.01926 (14)
N =  0.002748 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  0.03288 (29)
L1/b+ =  0.003692 (27)
L2/b+ =  4.33E-5 (8)
M1/b+ =  7.126E-4 (28)
M2/b+ =  8.61E-6 (10)
N1/b+ =  1.020E-4 (8)
N2/b+ =  8.582E-7 (24)

K/b+ =  0.03288 (29)
L/b+ =  0.003735 (27)
M/b+ =  7.212E-4 (28)
N/b+ =  1.029E-4 (8)

EC/b+ =  0.03744 (32)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   84.82 (24) %   Iec =   3.010 (30) %   Ib+ =   81.81 (24) %
Iec      =   3.010 (30) % (input data kept)
Ib+      =   81.81 (24) % (input data kept)
Iec tot. =   84.82 (24) % (input data kept)


---------------------
Capture probabilities

PK  =  0.03169 (26)
PL1  =  0.003559 (30)
PL2  =  4.18E-5 (5)
PM1  =  6.87E-4 (8)
PM2  =  8.30E-6 (7)
PN1  =  9.83E-5 (14)
PN2  =  8.28E-7 (8)

K =  0.03169 (26)
L =  0.003601 (30)
M =  6.95E-4 (8)
N =  9.92E-5 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 4.6

Log ft value (ec)    =  4.591 (6)
with log f           =  1.1889 (32)
and log partial T1/2 =  3.4017 (46)

