--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [2+] 2944.140 (40) keV
Calculation of the allowed transition from the electron capture decay of Rb-82

Transition energy: 1458.9 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11356 (20)
PL2/PK =  0.001281 (12)
PM1/PK =  0.02195 (17)
PM2/PK =  2.550E-4 (7)
PN1/PK =  0.003143 (37)
PN2/PK =  2.544E-5 (15)

L/K =  0.11484 (19)
M/K =  0.02220 (17)
N/K =  0.003168 (37)


------------------------------
Relative capture probabilities

PK  =  0.87703 (31)
PL1 =  0.09959 (14)
PL2 =  0.001124 (11)
PM1 =  0.01925 (14)
PM2 =  2.237E-4 (6)
PN1 =  0.002756 (31)
PN2 =  2.231E-5 (13)

K =  0.87703 (31)
L =  0.10072 (13)
M =  0.01947 (14)
N =  0.002779 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  27.0 (9)
L1/b+ =  3.07 (9)
L2/b+ =  0.0346 (14)
M1/b+ =  0.593 (16)
M2/b+ =  0.00689 (24)
N1/b+ =  0.0849 (27)
N2/b+ =  6.87E-4 (18)

K/b+ =  27.0 (9)
L/b+ =  3.10 (10)
M/b+ =  0.600 (16)
N/b+ =  0.0856 (27)

EC/b+ =  30.8 (10)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0500 (19) %   Iec =   0.0500 (19) %   Ib+ =   0. %
Iec      =   0.0500 (19) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.0500 (19) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8494 (9)
PL1  =  0.09646 (17)
PL2  =  0.001088 (10)
PM1  =  0.01864 (14)
PM2  =  2.166E-4 (7)
PN1  =  0.002670 (30)
PN2  =  2.161E-5 (12)

K =  0.8494 (9)
L =  0.09755 (16)
M =  0.01886 (14)
N =  0.002691 (31)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.4

Log ft value (ec)    =  5.400 (17)
with log f           =  0.2189 (44)
and log partial T1/2 =  5.181 (17)

