--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-73 [9/2+] g.s.  -->  Daughter nucleus: 33-As-73 [7/2+] 2180.66 (10) keV
Calculation of the allowed transition from the electron capture decay of Se-73

Transition energy: 544 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11255 (18)
PL2/PK =  0.0010720 (49)
PM1/PK =  0.01830 (6)
PM2/PK =  1.6417E-4 (44)
PN1/PK =  0.002664 (26)
PN2/PK =  1.301E-5 (9)

L/K =  0.11362 (18)
M/K =  0.01846 (6)
N/K =  0.002677 (26)


------------------------------
Relative capture probabilities

PK  =  0.88124 (20)
PL1 =  0.09918 (14)
PL2 =  9.447E-4 (44)
PM1 =  0.016124 (47)
PM2 =  1.4467E-4 (41)
PN1 =  0.002348 (22)
PN2 =  1.147E-5 (8)

K =  0.88124 (20)
L =  0.10013 (13)
M =  0.016268 (46)
N =  0.002359 (22)


------------------------------
Capture branch from input data

Iec =   0.030 (8) %


---------------------
Capture probabilities

PK  =  0.88124 (20)
PL1  =  0.09918 (14)
PL2  =  9.447E-4 (44)
PM1  =  0.016124 (47)
PM2  =  1.4467E-4 (41)
PN1  =  0.002348 (22)
PN2  =  1.147E-5 (8)

K =  0.88124 (20)
L =  0.10013 (13)
M =  0.016268 (46)
N =  0.002359 (22)


------------------------------------------------------------
Input log ft value (ec): 7.1

Log ft value (ec)    =  7.15 (12)
with log f           =  -0.777 (15)
and log partial T1/2 =  7.93 (12)

