--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-73 [9/2+] g.s.  -->  Daughter nucleus: 33-As-73 [11/2+] 2476.10 (20) keV
Calculation of the allowed transition from the electron capture decay of Se-73

Transition energy: 249 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11786 (43)
PL2/PK =  0.001119 (7)
PM1/PK =  0.01927 (10)
PM2/PK =  1.722E-4 (9)
PN1/PK =  0.002808 (34)
PN2/PK =  1.366E-5 (13)

L/K =  0.11898 (43)
M/K =  0.01944 (10)
N/K =  0.002822 (34)


------------------------------
Relative capture probabilities

PK  =  0.87623 (43)
PL1 =  0.10328 (32)
PL2 =  9.80E-4 (6)
PM1 =  0.01688 (8)
PM2 =  1.509E-4 (7)
PN1 =  0.002461 (28)
PN2 =  1.197E-5 (11)

K =  0.87623 (43)
L =  0.10426 (32)
M =  0.01704 (8)
N =  0.002473 (28)


------------------------------
Capture branch from input data

Iec =   0.0029 (10) %


---------------------
Capture probabilities

PK  =  0.87623 (43)
PL1  =  0.10328 (32)
PL2  =  9.80E-4 (6)
PM1  =  0.01688 (8)
PM2  =  1.509E-4 (7)
PN1  =  0.002461 (28)
PN2  =  1.197E-5 (11)

K =  0.87623 (43)
L =  0.10426 (32)
M =  0.01704 (8)
N =  0.002473 (28)


------------------------------------------------------------
Input log ft value (ec): 7.5

Log ft value (ec)    =  7.47 (15)
with log f           =  -1.477 (29)
and log partial T1/2 =  8.95 (15)

