--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-73 [9/2+] g.s.  -->  Daughter nucleus: 33-As-73 [9/2+] 1850.59 (5) keV
Calculation of the allowed transition from the electron capture decay of Se-73

Transition energy: 874 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11094 (15)
PL2/PK =  0.0010615 (45)
PM1/PK =  0.01800 (5)
PM2/PK =  1.6230E-4 (38)
PN1/PK =  0.002621 (24)
PN2/PK =  1.286E-5 (9)

L/K =  0.11200 (14)
M/K =  0.01817 (5)
N/K =  0.002634 (24)


------------------------------
Relative capture probabilities

PK  =  0.88277 (17)
PL1 =  0.09793 (11)
PL2 =  9.371E-4 (41)
PM1 =  0.015892 (41)
PM2 =  1.4327E-4 (35)
PN1 =  0.002314 (21)
PN2 =  1.136E-5 (8)

K =  0.88277 (17)
L =  0.09887 (11)
M =  0.016036 (41)
N =  0.002325 (21)


------------------------------
Capture branch from input data

Iec =   0.433 (11) %


---------------------
Capture probabilities

PK  =  0.88277 (17)
PL1  =  0.09793 (11)
PL2  =  9.371E-4 (41)
PM1  =  0.015892 (41)
PM2  =  1.4327E-4 (35)
PN1  =  0.002314 (21)
PN2  =  1.136E-5 (8)

K =  0.88277 (17)
L =  0.09887 (11)
M =  0.016036 (41)
N =  0.002325 (21)


------------------------------------------------------------
Input log ft value (ec): 6.4

Log ft value (ec)    =  6.412 (16)
with log f           =  -0.359 (10)
and log partial T1/2 =  6.771 (12)

