--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-73 [9/2+] g.s.  -->  Daughter nucleus: 33-As-73 [9/2+] 1910.13 (12) keV
Calculation of the allowed transition from the electron capture decay of Se-73

Transition energy: 815 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11113 (15)
PL2/PK =  0.0010625 (45)
PM1/PK =  0.01804 (5)
PM2/PK =  1.6248E-4 (38)
PN1/PK =  0.002626 (24)
PN2/PK =  1.288E-5 (9)

L/K =  0.11220 (15)
M/K =  0.01820 (5)
N/K =  0.002639 (25)


------------------------------
Relative capture probabilities

PK  =  0.88259 (17)
PL1 =  0.09808 (11)
PL2 =  9.377E-4 (41)
PM1 =  0.015920 (42)
PM2 =  1.4340E-4 (36)
PN1 =  0.002318 (21)
PN2 =  1.137E-5 (8)

K =  0.88259 (17)
L =  0.09902 (11)
M =  0.016063 (41)
N =  0.002329 (21)


------------------------------
Capture branch from input data

Iec =   0.060 (7) %


---------------------
Capture probabilities

PK  =  0.88259 (17)
PL1  =  0.09808 (11)
PL2  =  9.377E-4 (41)
PM1  =  0.015920 (42)
PM2  =  1.4340E-4 (36)
PN1  =  0.002318 (21)
PN2  =  1.137E-5 (8)

K =  0.88259 (17)
L =  0.09902 (11)
M =  0.016063 (41)
N =  0.002329 (21)


------------------------------------------------------------
Input log ft value (ec): 7.2

Log ft value (ec)    =  7.21 (5)
with log f           =  -0.421 (11)
and log partial T1/2 =  7.63 (5)

