--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-73 [9/2+] g.s.  -->  Daughter nucleus: 33-As-73 [5/2-] 67.039 (8) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of Se-73

Transition energy: 2658 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11005 (13)
PL2/PK =  0.0010757 (44)
PL3/PK =  1.207E-4 (11)
PM1/PK =  0.017840 (47)
PM2/PK =  1.6431E-4 (36)
PM3/PK =  1.633E-5 (12)
PN1/PK =  0.002597 (24)
PM4/PK =  6.09E-9 (11)
PN2/PK =  1.302E-5 (9)
PN3/PK =  4.66E-7 (7)

L/K =  0.11125 (12)
M/K =  0.018021 (46)
N/K =  0.002610 (24)


------------------------------
Relative capture probabilities

PK  =  0.88349 (15)
PL1 =  0.09723 (10)
PL2 =  9.504E-4 (41)
PL3 =  1.066E-4 (10)
PM1 =  0.015761 (38)
PM2 =  1.4517E-4 (34)
PM3 =  1.443E-5 (11)
PN1 =  0.002294 (20)
PM4 =  5.38E-9 (9)
PN2 =  1.150E-5 (8)
PN3 =  4.12E-7 (6)

K =  0.88349 (15)
L =  0.09828 (9)
M =  0.015921 (38)
N =  0.002306 (21)


--------------------------
Capture-to-positron ratios

K/b+ =  0.682 (16)
L1/b+ =  0.0750 (16)
L2/b+ =  7.33E-4 (20)
L3/b+ =  8.22E-5 (26)
M1/b+ =  0.01216 (25)
M2/b+ =  1.120E-4 (28)
M3/b+ =  1.113E-5 (34)
N1/b+ =  0.001770 (30)
M4/b+ =  4.15E-9 (11)
N2/b+ =  8.87E-6 (14)
N3/b+ =  3.17E-7 (8)

K/b+ =  0.682 (16)
L/b+ =  0.0758 (17)
M/b+ =  0.01228 (25)
N/b+ =  0.001779 (30)

EC/b+ =  0.772 (18)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.20 (14) %   Iec =   0.51 (9) %   Ib+ =   0.69 (11) %
Iec      =   0.51 (9) % (input data kept)
Ib+      =   0.69 (11) % (input data kept)
Iec tot. =   1.20 (14) % (input data kept)


---------------------
Capture probabilities

PK  =  0.385 (5)
PL1  =  0.0423 (5)
PL2  =  4.14E-4 (6)
PL3  =  4.64E-5 (7)
PM1  =  0.00686 (9)
PM2  =  6.32E-5 (8)
PM3  =  6.28E-6 (9)
PN1  =  9.99E-4 (16)
PM4  =  2.34E-9 (5)
PN2  =  5.01E-6 (7)
PN3  =  1.792E-7 (36)

K =  0.385 (5)
L =  0.0428 (6)
M =  0.00693 (9)
N =  0.001004 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.7

Log ft value (ec)    =  8.74 (8)
with log f           =  2.045 (8)
and log partial T1/2 =  6.70 (8)

