--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-73 [9/2+] g.s.  -->  Daughter nucleus: 33-As-73 [7/2+] 2482.87 (23) keV
Calculation of the allowed transition from the electron capture decay of Se-73

Transition energy: 242 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11815 (45)
PL2/PK =  0.001121 (8)
PM1/PK =  0.01932 (11)
PM2/PK =  1.726E-4 (9)
PN1/PK =  0.002816 (34)
PN2/PK =  1.369E-5 (13)

L/K =  0.11927 (45)
M/K =  0.01949 (11)
N/K =  0.002830 (34)


------------------------------
Relative capture probabilities

PK  =  0.87597 (45)
PL1 =  0.10350 (34)
PL2 =  9.82E-4 (6)
PM1 =  0.01693 (9)
PM2 =  1.512E-4 (8)
PN1 =  0.002467 (29)
PN2 =  1.200E-5 (11)

K =  0.87597 (45)
L =  0.10448 (34)
M =  0.01708 (9)
N =  0.002479 (29)


------------------------------
Capture branch from input data

Iec =   0.0087 (20) %


---------------------
Capture probabilities

PK  =  0.87597 (45)
PL1  =  0.10350 (34)
PL2  =  9.82E-4 (6)
PM1  =  0.01693 (9)
PM2  =  1.512E-4 (8)
PN1  =  0.002467 (29)
PN2  =  1.200E-5 (11)

K =  0.87597 (45)
L =  0.10448 (34)
M =  0.01708 (9)
N =  0.002479 (29)


------------------------------------------------------------
Input log ft value (ec): 7.

Log ft value (ec)    =  6.97 (10)
with log f           =  -1.502 (30)
and log partial T1/2 =  8.47 (10)

