--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-73 [9/2+] g.s.  -->  Daughter nucleus: 33-As-73 [7/2+] 1328.89 (5) keV
Calculation of the allowed transition from the electron capture decay of Se-73

Transition energy: 1396 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10997 (13)
PL2/PK =  0.0010600 (44)
PM1/PK =  0.017825 (47)
PM2/PK =  1.6191E-4 (36)
PN1/PK =  0.002595 (24)
PN2/PK =  1.283E-5 (9)

L/K =  0.11103 (13)
M/K =  0.017987 (47)
N/K =  0.002608 (24)


------------------------------
Relative capture probabilities

PK  =  0.88369 (15)
PL1 =  0.09718 (10)
PL2 =  9.367E-4 (40)
PM1 =  0.015752 (39)
PM2 =  1.4307E-4 (34)
PN1 =  0.002293 (21)
PN2 =  1.134E-5 (8)

K =  0.88369 (15)
L =  0.09811 (10)
M =  0.015895 (39)
N =  0.002304 (21)


--------------------------
Capture-to-positron ratios

K/b+ =  33.5 (27)
L1/b+ =  3.69 (30)
L2/b+ =  0.0355 (30)
M1/b+ =  0.597 (47)
M2/b+ =  0.00543 (45)
N1/b+ =  0.087 (7)
N2/b+ =  4.30E-4 (32)

K/b+ =  33.5 (27)
L/b+ =  3.72 (30)
M/b+ =  0.603 (48)
N/b+ =  0.087 (7)

EC/b+ =  37.9 (31)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.13240 (30) %   Iec =   0.1290 (30) %   Ib+ =   0.00340 (20) %
Iec      =   0.1290 (30) % (input data kept)
Ib+      =   0.00340 (20) % (input data kept)
Iec tot. =   0.1324 (30) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8610 (18)
PL1  =  0.09468 (22)
PL2  =  9.127E-4 (44)
PM1  =  0.01535 (5)
PM2  =  1.3940E-4 (44)
PN1  =  0.002234 (21)
PN2  =  1.105E-5 (8)

K =  0.8610 (18)
L =  0.09559 (22)
M =  0.01549 (5)
N =  0.002245 (21)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.3

Log ft value (ec)    =  7.349 (14)
with log f           =  0.052 (8)
and log partial T1/2 =  7.297 (11)

