--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 34-Se-73 [9/2+] g.s.  -->  Daughter nucleus: 33-As-73 [7/2-] 2584.09 (11) keV
The 1st forbidden non-unique transition from the electron capture decay of Se-73 is calculated as allowed

Transition energy: 141 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1261 (12)
PL2/PK =  0.001196 (15)
PM1/PK =  0.02078 (25)
PM2/PK =  1.855E-4 (21)
PN1/PK =  0.00303 (6)
PN2/PK =  1.472E-5 (24)

L/K =  0.1273 (12)
M/K =  0.02097 (25)
N/K =  0.00305 (6)


------------------------------
Relative capture probabilities

PK  =  0.8686 (11)
PL1 =  0.1095 (9)
PL2 =  0.001039 (12)
PM1 =  0.01805 (19)
PM2 =  1.611E-4 (17)
PN1 =  0.002634 (46)
PN2 =  1.279E-5 (19)

K =  0.8686 (11)
L =  0.1106 (9)
M =  0.01821 (19)
N =  0.002646 (46)


------------------------------
Capture branch from input data

Iec =   0.0155 (20) %


---------------------
Capture probabilities

PK  =  0.8686 (11)
PL1  =  0.1095 (9)
PL2  =  0.001039 (12)
PM1  =  0.01805 (19)
PM2  =  1.611E-4 (17)
PN1  =  0.002634 (46)
PN2  =  1.279E-5 (19)

K =  0.8686 (11)
L =  0.1106 (9)
M =  0.01821 (19)
N =  0.002646 (46)


------------------------------------------------------------
Input log ft value (ec): 6.2

Log ft value (ec)    =  6.22 (8)
with log f           =  -2.00 (5)
and log partial T1/2 =  8.22 (6)

