--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-61 [3/2-] g.s.  -->  Daughter nucleus: 28-Ni-61 [5/2-] 1132.332 (17) keV
Calculation of the allowed transition from the electron capture decay of Cu-61

Transition energy: 1105.2 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11263 (20)
PL2/PK =  7.19E-4 (10)
PM1/PK =  0.01810 (8)
PM2/PK =  1.110E-4 (19)
PN1/PK =  3.423E-4 (36)

L/K =  0.11335 (21)
M/K =  0.01821 (8)
N/K =  3.423E-4 (36)


------------------------------
Relative capture probabilities

PK  =  0.88347 (23)
PL1 =  0.09950 (15)
PL2 =  6.36E-4 (9)
PM1 =  0.01599 (7)
PM2 =  9.80E-5 (16)
PN1 =  3.024E-4 (31)

K =  0.88347 (23)
L =  0.10014 (16)
M =  0.01609 (7)
N =  3.024E-4 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  7.24E3 (49)
L1/b+ =  8.1E2 (5)
L2/b+ =  5.21 (30)
M1/b+ =  131 (8)
M2/b+ =  0.803 (48)
N1/b+ =  2.48 (14)

K/b+ =  7.24E3 (49)
L/b+ =  8.2E2 (5)
M/b+ =  132 (8)
N/b+ =  2.48 (14)

EC/b+ =  8.2E3 (6)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.154 (17) %   Iec =   0.154 (17) %   Ib+ =   0. %
Iec      =   0.154 (17) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.154 (17) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88336 (23)
PL1  =  0.09949 (15)
PL2  =  6.36E-4 (9)
PM1  =  0.01599 (7)
PM2  =  9.80E-5 (16)
PN1  =  3.023E-4 (31)

K =  0.88336 (23)
L =  0.10013 (16)
M =  0.01609 (7)
N =  3.023E-4 (31)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.5

Log ft value (ec)    =  6.487 (49)
with log f           =  -0.409 (6)
and log partial T1/2 =  6.896 (48)

