--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-61 [3/2-] g.s.  -->  Daughter nucleus: 28-Ni-61 [5/2-] 1609.639 (21) keV
Calculation of the allowed transition from the electron capture decay of Cu-61

Transition energy: 627.9 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11376 (20)
PL2/PK =  7.22E-4 (10)
PM1/PK =  0.01830 (8)
PM2/PK =  1.114E-4 (19)
PN1/PK =  3.462E-4 (37)

L/K =  0.11448 (21)
M/K =  0.01841 (8)
N/K =  3.462E-4 (37)


------------------------------
Relative capture probabilities

PK  =  0.88243 (23)
PL1 =  0.10038 (15)
PL2 =  6.37E-4 (9)
PM1 =  0.01615 (7)
PM2 =  9.83E-5 (17)
PN1 =  3.055E-4 (32)

K =  0.88243 (23)
L =  0.10102 (16)
M =  0.01625 (7)
N =  3.055E-4 (32)


------------------------------
Capture branch from input data

Iec =   0.063 (7) %


---------------------
Capture probabilities

PK  =  0.88243 (23)
PL1  =  0.10038 (15)
PL2  =  6.37E-4 (9)
PM1  =  0.01615 (7)
PM2  =  9.83E-5 (17)
PN1  =  3.055E-4 (32)

K =  0.88243 (23)
L =  0.10102 (16)
M =  0.01625 (7)
N =  3.055E-4 (32)


------------------------------------------------------------
Input log ft value (ec): 6.5

Log ft value (ec)    =  6.379 (49)
with log f           =  -0.905 (7)
and log partial T1/2 =  7.284 (48)

