--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-61 [3/2-] g.s.  -->  Daughter nucleus: 28-Ni-61 [7/2-] 1014.80 (40) keV
The 2nd forbidden non-unique transition from the electron capture decay of Cu-61 is calculated as 1st forbidden unique

Transition energy: 1222.7 (11) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11382 (20)
PL2/PK =  7.24E-4 (10)
PL3/PK =  4.07E-4 (7)
PM1/PK =  0.01831 (8)
PM2/PK =  1.117E-4 (19)
PM3/PK =  5.69E-5 (11)
PN1/PK =  3.464E-4 (37)
PM4/PK =  9.69E-9 (17)

L/K =  0.11495 (22)
M/K =  0.01848 (8)
N/K =  3.464E-4 (37)


------------------------------
Relative capture probabilities

PK  =  0.88201 (24)
PL1 =  0.10039 (15)
PL2 =  6.38E-4 (9)
PL3 =  3.59E-4 (6)
PM1 =  0.01615 (7)
PM2 =  9.86E-5 (17)
PM3 =  5.02E-5 (10)
PN1 =  3.055E-4 (32)
PM4 =  8.55E-9 (15)

K =  0.88201 (24)
L =  0.10139 (16)
M =  0.01630 (7)
N =  3.055E-4 (32)


--------------------------
Capture-to-positron ratios

K/b+ =  2.19E3 (8)
L1/b+ =  249 (9)
L2/b+ =  1.584 (43)
L3/b+ =  0.891 (26)
M1/b+ =  40.1 (14)
M2/b+ =  0.245 (7)
M3/b+ =  0.1246 (41)
N1/b+ =  0.758 (21)
M4/b+ =  2.12E-5 (7)

K/b+ =  2.19E3 (8)
L/b+ =  252 (9)
M/b+ =  40.5 (14)
N/b+ =  0.758 (21)

EC/b+ =  2.48E3 (9)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.006 (6) %   Iec =   0.006 (6) %   Ib+ =   3.2E-5 (32) %
Iec      =   0.006 (6) % (input data kept)
Ib+      =   3.2E-5 (32) % (input data kept)
Iec tot. =   0.006 (6) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88165 (24)
PL1  =  0.10035 (15)
PL2  =  6.38E-4 (9)
PL3  =  3.59E-4 (6)
PM1  =  0.01615 (7)
PM2  =  9.85E-5 (17)
PM3  =  5.02E-5 (10)
PN1  =  3.054E-4 (32)
PM4  =  8.55E-9 (15)

K =  0.88165 (24)
L =  0.10135 (16)
M =  0.01629 (7)
N =  3.054E-4 (32)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.8

Log ft value (ec)    =  8.74 (43)
with log f           =  0.432 (7)
and log partial T1/2 =  8.31 (43)

