--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-61 [3/2-] g.s.  -->  Daughter nucleus: 28-Ni-61 [5/2-] 908.620 (11) keV
Calculation of the allowed transition from the electron capture decay of Cu-61

Transition energy: 1328.9 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11238 (20)
PL2/PK =  7.20E-4 (10)
PM1/PK =  0.01805 (8)
PM2/PK =  1.111E-4 (19)
PN1/PK =  3.414E-4 (36)

L/K =  0.11310 (21)
M/K =  0.01816 (8)
N/K =  3.414E-4 (36)


------------------------------
Relative capture probabilities

PK  =  0.88370 (23)
PL1 =  0.09931 (15)
PL2 =  6.36E-4 (9)
PM1 =  0.01595 (7)
PM2 =  9.81E-5 (16)
PN1 =  3.017E-4 (31)

K =  0.88370 (23)
L =  0.09994 (16)
M =  0.01605 (7)
N =  3.017E-4 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  33.8 (8)
L1/b+ =  3.80 (9)
L2/b+ =  0.02433 (34)
M1/b+ =  0.610 (13)
M2/b+ =  0.00375 (6)
N1/b+ =  0.01153 (17)

K/b+ =  33.8 (8)
L/b+ =  3.82 (9)
M/b+ =  0.614 (13)
N/b+ =  0.01153 (17)

EC/b+ =  38.2 (9)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.35 (15) %   Iec =   1.32 (15) %   Ib+ =   0.0347 (40) %
Iec      =   1.32 (15) % (input data kept)
Ib+      =   0.0347 (40) % (input data kept)
Iec tot. =   1.35 (15) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8612 (6)
PL1  =  0.09678 (16)
PL2  =  6.20E-4 (9)
PM1  =  0.01555 (6)
PM2  =  9.56E-5 (16)
PN1  =  2.940E-4 (31)

K =  0.8612 (6)
L =  0.09740 (16)
M =  0.01564 (7)
N =  2.940E-4 (31)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.7

Log ft value (ec)    =  5.72 (5)
with log f           =  -0.248 (6)
and log partial T1/2 =  5.96 (5)

