--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-61 [3/2-] g.s.  -->  Daughter nucleus: 28-Ni-61 [1/2-] 656.0120 (30) keV
Calculation of the allowed transition from the electron capture decay of Cu-61

Transition energy: 1581.5 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11218 (20)
PL2/PK =  7.22E-4 (10)
PM1/PK =  0.01802 (8)
PM2/PK =  1.113E-4 (19)
PN1/PK =  3.407E-4 (36)

L/K =  0.11290 (21)
M/K =  0.01813 (8)
N/K =  3.407E-4 (36)


------------------------------
Relative capture probabilities

PK  =  0.88388 (23)
PL1 =  0.09916 (15)
PL2 =  6.38E-4 (9)
PM1 =  0.01593 (7)
PM2 =  9.83E-5 (16)
PN1 =  3.012E-4 (31)

K =  0.88388 (23)
L =  0.09979 (16)
M =  0.01602 (7)
N =  3.012E-4 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  3.78 (7)
L1/b+ =  0.424 (7)
L2/b+ =  0.002728 (21)
M1/b+ =  0.0681 (10)
M2/b+ =  4.206E-4 (44)
N1/b+ =  0.001288 (11)

K/b+ =  3.78 (7)
L/b+ =  0.427 (7)
M/b+ =  0.0685 (10)
N/b+ =  0.001288 (11)

EC/b+ =  4.28 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   13.2 (12) %   Iec =   10.7 (12) %   Ib+ =   2.52 (27) %
Iec      =   10.7 (12) % (input data kept)
Ib+      =   2.52 (27) % (input data kept)
Iec tot. =   13.2 (12) % (input data kept)


---------------------
Capture probabilities

PK  =  0.7164 (25)
PL1  =  0.08037 (30)
PL2  =  5.17E-4 (7)
PM1  =  0.01291 (7)
PM2  =  7.97E-5 (14)
PN1  =  2.441E-4 (27)

K =  0.7164 (25)
L =  0.08088 (31)
M =  0.01299 (7)
N =  2.441E-4 (27)


------------------------------------------------------------
Input log ft value (ec & beta +): 4.9

Log ft value (ec)    =  4.959 (49)
with log f           =  -0.096 (6)
and log partial T1/2 =  5.054 (49)

