--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-61 [3/2-] g.s.  -->  Daughter nucleus: 28-Ni-61 [3/2-] g.s.
Calculation of the allowed transition from the electron capture decay of Cu-61

Transition energy: 2237.5 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11188 (20)
PL2/PK =  7.27E-4 (10)
PM1/PK =  0.01796 (8)
PM2/PK =  1.120E-4 (19)
PN1/PK =  3.397E-4 (36)

L/K =  0.11261 (21)
M/K =  0.01808 (8)
N/K =  3.397E-4 (36)


------------------------------
Relative capture probabilities

PK  =  0.88415 (23)
PL1 =  0.09892 (15)
PL2 =  6.43E-4 (9)
PM1 =  0.01588 (6)
PM2 =  9.90E-5 (16)
PN1 =  3.003E-4 (31)

K =  0.88415 (23)
L =  0.09956 (16)
M =  0.01598 (7)
N =  3.003E-4 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  0.2818 (42)
L1/b+ =  0.03153 (42)
L2/b+ =  2.047E-4 (8)
M1/b+ =  0.00506 (5)
M2/b+ =  3.155E-5 (21)
N1/b+ =  9.572E-5 (44)

K/b+ =  0.2818 (42)
L/b+ =  0.03173 (42)
M/b+ =  0.00509 (5)
N/b+ =  9.572E-5 (44)

EC/b+ =  0.3187 (47)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   67.9 (26) %   Iec =   16.3 (8) %   Ib+ =   51.6 (25) %
Iec      =   16.3 (8) % (input data kept)
Ib+      =   51.6 (25) % (input data kept)
Iec tot. =   67.9 (26) % (input data kept)


---------------------
Capture probabilities

PK  =  0.2137 (24)
PL1  =  0.02391 (27)
PL2  =  1.553E-4 (27)
PM1  =  0.003839 (46)
PM2  =  2.393E-5 (48)
PN1  =  7.26E-5 (11)

K =  0.2137 (24)
L =  0.02406 (27)
M =  0.003863 (46)
N =  7.26E-5 (11)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.

Log ft value (ec)    =  5.079 (22)
with log f           =  0.208 (6)
and log partial T1/2 =  4.871 (22)

