--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-61 [3/2-] g.s.  -->  Daughter nucleus: 28-Ni-61 [1/2-] 282.9568 (19) keV
Calculation of the allowed transition from the electron capture decay of Cu-61

Transition energy: 1954.5 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11199 (20)
PL2/PK =  7.24E-4 (10)
PM1/PK =  0.01798 (8)
PM2/PK =  1.117E-4 (19)
PN1/PK =  3.401E-4 (36)

L/K =  0.11271 (21)
M/K =  0.01810 (8)
N/K =  3.401E-4 (36)


------------------------------
Relative capture probabilities

PK  =  0.88406 (23)
PL1 =  0.09900 (15)
PL2 =  6.40E-4 (9)
PM1 =  0.01590 (6)
PM2 =  9.87E-5 (16)
PN1 =  3.006E-4 (31)

K =  0.88406 (23)
L =  0.09964 (16)
M =  0.01600 (7)
N =  3.006E-4 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  0.666 (11)
L1/b+ =  0.0746 (11)
L2/b+ =  4.824E-4 (24)
M1/b+ =  0.01198 (14)
M2/b+ =  7.44E-5 (6)
N1/b+ =  2.265E-4 (12)

K/b+ =  0.666 (11)
L/b+ =  0.0751 (11)
M/b+ =  0.01205 (14)
N/b+ =  2.265E-4 (12)

EC/b+ =  0.753 (12)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   9.4 (11) %   Iec =   4.0 (7) %   Ib+ =   5.4 (9) %
Iec      =   4.0 (7) % (input data kept)
Ib+      =   5.4 (9) % (input data kept)
Iec tot. =   9.4 (11) % (input data kept)


---------------------
Capture probabilities

PK  =  0.3799 (34)
PL1  =  0.04254 (38)
PL2  =  2.752E-4 (45)
PM1  =  0.00683 (7)
PM2  =  4.24E-5 (8)
PN1  =  1.292E-4 (18)

K =  0.3799 (34)
L =  0.04282 (39)
M =  0.00687 (7)
N =  1.292E-4 (18)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.5

Log ft value (ec)    =  5.57 (8)
with log f           =  0.090 (6)
and log partial T1/2 =  5.48 (8)

