--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-61 [3/2-] g.s.  -->  Daughter nucleus: 28-Ni-61 [1/2-] 2124.0 (10) keV
Calculation of the allowed transition from the electron capture decay of Cu-61

Transition energy: 113.5 (14) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12686 (44)
PL2/PK =  8.00E-4 (13)
PM1/PK =  0.02067 (13)
PM2/PK =  1.249E-4 (24)
PN1/PK =  3.92E-4 (5)

L/K =  0.12766 (46)
M/K =  0.02079 (13)
N/K =  3.92E-4 (5)


------------------------------
Relative capture probabilities

PK  =  0.87044 (45)
PL1 =  0.11043 (33)
PL2 =  6.96E-4 (11)
PM1 =  0.01799 (10)
PM2 =  1.087E-4 (20)
PN1 =  3.408E-4 (41)

K =  0.87044 (45)
L =  0.11112 (34)
M =  0.01810 (11)
N =  3.408E-4 (41)


------------------------------
Capture branch from input data

Iec =   0.040 (5) %


---------------------
Capture probabilities

PK  =  0.87044 (45)
PL1  =  0.11043 (33)
PL2  =  6.96E-4 (11)
PM1  =  0.01799 (10)
PM2  =  1.087E-4 (20)
PN1  =  3.408E-4 (41)

K =  0.87044 (45)
L =  0.11112 (34)
M =  0.01810 (11)
N =  3.408E-4 (41)


------------------------------------------------------------
Input log ft value (ec): 5.

Log ft value (ec)    =  5.04 (6)
with log f           =  -2.438 (17)
and log partial T1/2 =  7.48 (5)

