--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-67 [3/2-] g.s.  -->  Daughter nucleus: 30-Zn-67 [5/2-] g.s.
Calculation of the allowed transition from the electron capture decay of Ga-67

Transition energy: 1000.8 (12) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11203 (16)
PL2/PK =  8.35E-4 (31)
PM1/PK =  0.01856 (7)
PM2/PK =  1.35E-4 (5)
PN1/PK =  0.001488 (32)

L/K =  0.11286 (19)
M/K =  0.01869 (7)
N/K =  0.001488 (32)


------------------------------
Relative capture probabilities

PK  =  0.88258 (23)
PL1 =  0.09887 (12)
PL2 =  7.37E-4 (27)
PM1 =  0.01638 (6)
PM2 =  1.195E-4 (47)
PN1 =  0.001314 (28)

K =  0.88258 (23)
L =  0.09961 (14)
M =  0.01650 (6)
N =  0.001314 (28)


------------------------------
Capture branch from input data

Iec =   3.3 (32) %


---------------------
Capture probabilities

PK  =  0.88258 (23)
PL1  =  0.09887 (12)
PL2  =  7.37E-4 (27)
PM1  =  0.01638 (6)
PM2  =  1.195E-4 (47)
PN1  =  0.001314 (28)

K =  0.88258 (23)
L =  0.09961 (14)
M =  0.01650 (6)
N =  0.001314 (28)


------------------------------------------------------------
Input log ft value (ec): 6.532

Log ft value (ec)    =  6.54 (42)
with log f           =  -0.396 (14)
and log partial T1/2 =  6.93 (42)

