--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-67 [3/2-] g.s.  -->  Daughter nucleus: 30-Zn-67 [3/2-] 184.58 keV
Calculation of the allowed transition from the electron capture decay of Ga-67

Transition energy: 816.2 (12) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11245 (16)
PL2/PK =  8.36E-4 (31)
PM1/PK =  0.01864 (7)
PM2/PK =  1.36E-4 (5)
PN1/PK =  0.001495 (32)

L/K =  0.11329 (19)
M/K =  0.01877 (7)
N/K =  0.001495 (32)


------------------------------
Relative capture probabilities

PK  =  0.88218 (23)
PL1 =  0.09920 (12)
PL2 =  7.38E-4 (27)
PM1 =  0.01644 (6)
PM2 =  1.197E-4 (47)
PN1 =  0.001319 (28)

K =  0.88218 (23)
L =  0.09994 (14)
M =  0.01656 (6)
N =  0.001319 (28)


------------------------------
Capture branch from input data

Iec =   22.3 (27) %


---------------------
Capture probabilities

PK  =  0.88218 (23)
PL1  =  0.09920 (12)
PL2  =  7.38E-4 (27)
PM1  =  0.01644 (6)
PM2  =  1.197E-4 (47)
PN1  =  0.001319 (28)

K =  0.88218 (23)
L =  0.09994 (14)
M =  0.01656 (6)
N =  0.001319 (28)


------------------------------------------------------------
Input log ft value (ec): 5.523

Log ft value (ec)    =  5.53 (5)
with log f           =  -0.575 (14)
and log partial T1/2 =  6.10 (5)

