--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-67 [3/2-] g.s.  -->  Daughter nucleus: 30-Zn-67 [3/2-] 393.53 keV
Calculation of the allowed transition from the electron capture decay of Ga-67

Transition energy: 607.3 (12) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11326 (17)
PL2/PK =  8.40E-4 (31)
PM1/PK =  0.01879 (7)
PM2/PK =  1.36E-4 (5)
PN1/PK =  0.001507 (33)

L/K =  0.11410 (20)
M/K =  0.01892 (8)
N/K =  0.001507 (33)


------------------------------
Relative capture probabilities

PK  =  0.88143 (24)
PL1 =  0.09983 (12)
PL2 =  7.40E-4 (27)
PM1 =  0.01656 (6)
PM2 =  1.201E-4 (48)
PN1 =  0.001328 (28)

K =  0.88143 (24)
L =  0.10057 (15)
M =  0.01668 (6)
N =  0.001328 (28)


------------------------------
Capture branch from input data

Iec =   23.60 (47) %


---------------------
Capture probabilities

PK  =  0.88143 (24)
PL1  =  0.09983 (12)
PL2  =  7.40E-4 (27)
PM1  =  0.01656 (6)
PM2  =  1.201E-4 (48)
PN1  =  0.001328 (28)

K =  0.88143 (24)
L =  0.10057 (15)
M =  0.01668 (6)
N =  0.001328 (28)


------------------------------------------------------------
Input log ft value (ec): 5.239

Log ft value (ec)    =  5.242 (17)
with log f           =  -0.835 (14)
and log partial T1/2 =  6.077 (9)

