--------------------------------------------------------------------------------------

BetaShape
Version: 2.3.1 (12/2023)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 13-Al-26 [5+] g.s.  -->  Daughter nucleus: 12-Mg-26 [2+] 2938.33 (4) keV
Calculation of the 2nd forbidden unique transition from the electron capture decay of Al-26

Transition energy: 1066.07 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.07835 (48)
PL2/PK =  5.53E-5 (47)
PL3/PK =  1.61E-4 (14)
PM1/PK =  0.00957 (40)

L/K =  0.0786 (5)
M/K =  0.00957 (40)


------------------------------
Relative capture probabilities

PK  =  0.9190 (8)
PL1 =  0.07200 (38)
PL2 =  5.08E-5 (43)
PL3 =  1.48E-4 (13)
PM1 =  0.00879 (36)

K =  0.9190 (8)
L =  0.0722 (4)
M =  0.00879 (36)


--------------------------
Capture-to-positron ratios

K/b+ =  4.46E6 (33)
L1/b+ =  3.50E5 (24)
L2/b+ =  247 (5)
L3/b+ =  718 (17)
M1/b+ =  4.27E4 (15)

K/b+ =  4.46E6 (33)
L/b+ =  3.51E5 (24)
M/b+ =  4.27E4 (15)

EC/b+ =  4.86E6 (35)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   2.74 (2) %   Iec =   2.74 (2) %   Ib+ =   5.70E-7 (41) %
Iec      =   2.74 (2) %
Ib+      =   5.64E-7 (41) %
Iec tot. =   2.74 (2) %


---------------------
Capture probabilities

PK  =  0.9190 (8)
PL1  =  0.07200 (38)
PL2  =  5.08E-5 (43)
PL3  =  1.48E-4 (13)
PM1  =  0.00879 (36)

K =  0.9190 (8)
L =  0.0722 (4)
M =  0.00879 (36)


------------------------------------------------------------
Input log ft value (ec & beta +): 14.577

Log ft value (ec)    =  14.578 (33)
with log f           =  -0.339 (29)
or f-value           =  0.458 (29)
and log partial T1/2 =  14.916 (16)

