--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-65 [5/2-] g.s.  -->  Daughter nucleus: 29-Cu-65 [5/2-] 1115.5560 (40) keV
Calculation of the allowed transition from the electron capture decay of Zn-65

Transition energy: 236.54 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12146 (24)
PL2/PK =  8.46E-4 (23)
PM1/PK =  0.01936 (8)
PM2/PK =  1.297E-4 (39)
PN1/PK =  0.001077 (18)

L/K =  0.12231 (26)
M/K =  0.01949 (8)
N/K =  0.001077 (18)


------------------------------
Relative capture probabilities

PK  =  0.87499 (28)
PL1 =  0.10628 (17)
PL2 =  7.40E-4 (20)
PM1 =  0.01694 (6)
PM2 =  1.135E-4 (33)
PN1 =  9.42E-4 (15)

K =  0.87499 (28)
L =  0.10702 (19)
M =  0.01705 (7)
N =  9.42E-4 (15)


------------------------------
Capture branch from input data

Iec =   50.23 (11) %


---------------------
Capture probabilities

PK  =  0.87499 (28)
PL1  =  0.10628 (17)
PL2  =  7.40E-4 (20)
PM1  =  0.01694 (6)
PM2  =  1.135E-4 (33)
PN1  =  9.42E-4 (15)

K =  0.87499 (28)
L =  0.10702 (19)
M =  0.01705 (7)
N =  9.42E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 5.89

Log ft value (ec)    =  5.897 (9)
with log f           =  -1.726 (9)
and log partial T1/2 =  7.6229 (10)

