--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 30-Zn-65 [5/2-] g.s.  -->  Daughter nucleus: 29-Cu-65 [3/2-] g.s.
Calculation of the allowed transition from the electron capture decay of Zn-65

Transition energy: 1352.10 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11492 (22)
PL2/PK =  8.13E-4 (21)
PM1/PK =  0.01819 (7)
PM2/PK =  1.238E-4 (36)
PN1/PK =  0.001012 (17)

L/K =  0.11573 (24)
M/K =  0.01832 (8)
N/K =  0.001012 (17)


------------------------------
Relative capture probabilities

PK  =  0.88101 (26)
PL1 =  0.10124 (16)
PL2 =  7.16E-4 (19)
PM1 =  0.01603 (6)
PM2 =  1.091E-4 (32)
PN1 =  8.91E-4 (15)

K =  0.88101 (26)
L =  0.10196 (18)
M =  0.01614 (6)
N =  8.91E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  29.3 (6)
L1/b+ =  3.37 (6)
L2/b+ =  0.02382 (27)
M1/b+ =  0.533 (9)
M2/b+ =  0.00363 (5)
N1/b+ =  0.02965 (15)

K/b+ =  29.3 (6)
L/b+ =  3.39 (6)
M/b+ =  0.537 (9)
N/b+ =  0.02965 (15)

EC/b+ =  33.3 (7)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   49.77 (11) %   Iec =   48.35 (11) %   Ib+ =   1.421 (7) %
Iec      =   48.35 (11) % (input data kept)
Ib+      =   1.421 (7) % (input data kept)
Iec tot. =   49.77 (11) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8553 (6)
PL1  =  0.09829 (17)
PL2  =  6.95E-4 (18)
PM1  =  0.01556 (6)
PM2  =  1.059E-4 (31)
PN1  =  8.65E-4 (14)

K =  0.8553 (6)
L =  0.09898 (18)
M =  0.01567 (6)
N =  8.65E-4 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.46

Log ft value (ec)    =  7.452 (8)
with log f           =  -0.187 (8)
and log partial T1/2 =  7.6395 (10)

