--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 47-Ag-108m [6+] 109.440 (7) keV  -->  Daughter nucleus: 46-Pd-108 [6+] 1771.162 (11) keV
Calculation of the allowed transition from the electron capture decay of Ag-108

Transition energy: 260 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1398 (8)
PL2/PK =  0.002749 (16)
PM1/PK =  0.02985 (27)
PM2/PK =  6.17E-4 (6)
PN1/PK =  0.00653 (8)
PN2/PK =  1.206E-4 (16)

L/K =  0.1426 (8)
M/K =  0.03047 (28)
N/K =  0.00665 (9)


------------------------------
Relative capture probabilities

PK  =  0.8477 (8)
PL1 =  0.1185 (5)
PL2 =  0.002330 (11)
PM1 =  0.02531 (20)
PM2 =  5.228E-4 (44)
PN1 =  0.00553 (7)
PN2 =  1.022E-4 (13)

K =  0.8477 (8)
L =  0.1209 (5)
M =  0.02583 (21)
N =  0.00564 (7)


------------------------------
Capture branch from input data

Iec =   90.9 (6) %


---------------------
Capture probabilities

PK  =  0.8477 (8)
PL1  =  0.1185 (5)
PL2  =  0.002330 (11)
PM1  =  0.02531 (20)
PM2  =  5.228E-4 (44)
PN1  =  0.00553 (7)
PN2  =  1.022E-4 (13)

K =  0.8477 (8)
L =  0.1209 (5)
M =  0.02583 (21)
N =  0.00564 (7)


------------------------------------------------------------
Input log ft value (ec): 9.24

Log ft value (ec)    =  9.264 (25)
with log f           =  -0.918 (23)
and log partial T1/2 =  10.182 (9)

