--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 38-Sr-82 [0+] g.s.  -->  Daughter nucleus: 37-Rb-82 [1+] g.s.
Calculation of the allowed transition from the electron capture decay of Sr-82

Transition energy: 178 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1390 (12)
PL2/PK =  0.00166 (23)
PM1/PK =  0.02660 (36)
PM2/PK =  3.37E-4 (49)
PN1/PK =  0.00398 (8)
PN2/PK =  4.0E-5 (6)
PO1/PK =  4.82E-4 (43)

L/K =  0.1407 (14)
M/K =  0.02693 (41)
N/K =  0.00402 (8)
O/K =  4.82E-4 (43)


------------------------------
Relative capture probabilities

PK  =  0.8531 (14)
PL1 =  0.1186 (8)
PL2 =  0.00142 (19)
PM1 =  0.02269 (27)
PM2 =  2.88E-4 (41)
PN1 =  0.00339 (6)
PN2 =  3.4E-5 (5)
PO1 =  4.11E-4 (36)

K =  0.8531 (14)
L =  0.1200 (10)
M =  0.02298 (31)
N =  0.00343 (6)
O =  4.11E-4 (36)


------------------------------
Capture branch from input data

Iec =   100. %


---------------------
Capture probabilities

PK  =  0.8531 (14)
PL1  =  0.1186 (8)
PL2  =  0.00142 (19)
PM1  =  0.02269 (27)
PM2  =  2.88E-4 (41)
PN1  =  0.00339 (6)
PN2  =  3.4E-5 (5)
PO1  =  4.11E-4 (36)

K =  0.8531 (14)
L =  0.1200 (10)
M =  0.02298 (31)
N =  0.00343 (6)
O =  4.11E-4 (36)


------------------------------------------------------------
Input log ft value (ec): 4.7

Log ft value (ec)    =  4.69 (8)
with log f           =  -1.65 (8)
and log partial T1/2 =  6.34044 (30)

