--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 38-Sr-85 [9/2+] g.s.  -->  Daughter nucleus: 37-Rb-85 [9/2+] 514.01 keV
Calculation of the allowed transition from the electron capture decay of Sr-85

Transition energy: 551.0 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12517 (29)
PL2/PK =  0.00150 (19)
PM1/PK =  0.02363 (15)
PM2/PK =  3.01E-4 (41)
PN1/PK =  0.003528 (41)
PN2/PK =  3.6E-5 (5)
PO1/PK =  4.27E-4 (35)

L/K =  0.12667 (48)
M/K =  0.02393 (19)
N/K =  0.003564 (46)
O/K =  4.27E-4 (35)


------------------------------
Relative capture probabilities

PK  =  0.8661 (6)
PL1 =  0.10841 (18)
PL2 =  0.00130 (17)
PM1 =  0.02047 (12)
PM2 =  2.61E-4 (35)
PN1 =  0.003056 (33)
PN2 =  3.08E-5 (45)
PO1 =  3.70E-4 (30)

K =  0.8661 (6)
L =  0.10971 (34)
M =  0.02073 (15)
N =  0.003087 (38)
O =  3.70E-4 (30)


------------------------------
Capture branch from input data

Iec =   99.20 (40) %


---------------------
Capture probabilities

PK  =  0.8661 (6)
PL1  =  0.10841 (18)
PL2  =  0.00130 (17)
PM1  =  0.02047 (12)
PM2  =  2.61E-4 (35)
PN1  =  0.003056 (33)
PN2  =  3.08E-5 (45)
PO1  =  3.70E-4 (30)

K =  0.8661 (6)
L =  0.10971 (34)
M =  0.02073 (15)
N =  0.003087 (38)
O =  3.70E-4 (30)


------------------------------------------------------------
Input log ft value (ec): 6.2

Log ft value (ec)    =  6.129 (47)
with log f           =  -0.623 (47)
and log partial T1/2 =  6.7519 (18)

