--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 38-Sr-85 [9/2+] g.s.  -->  Daughter nucleus: 37-Rb-85 [7/2-] 868.98 keV
The 1st forbidden non-unique transition from the electron capture decay of Sr-85 is calculated as allowed

Transition energy: 196.0 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1370 (6)
PL2/PK =  0.00164 (22)
PM1/PK =  0.02616 (22)
PM2/PK =  3.32E-4 (46)
PN1/PK =  0.00391 (5)
PN2/PK =  3.9E-5 (6)
PO1/PK =  4.74E-4 (40)

L/K =  0.1387 (8)
M/K =  0.02649 (27)
N/K =  0.00395 (6)
O/K =  4.74E-4 (40)


------------------------------
Relative capture probabilities

PK  =  0.8550 (9)
PL1 =  0.11715 (38)
PL2 =  0.00140 (18)
PM1 =  0.02237 (17)
PM2 =  2.84E-4 (39)
PN1 =  0.003346 (43)
PN2 =  3.4E-5 (5)
PO1 =  4.05E-4 (33)

K =  0.8550 (9)
L =  0.1185 (6)
M =  0.02265 (21)
N =  0.003379 (48)
O =  4.05E-4 (33)


------------------------------
Capture branch from input data

Iec =   0.01290 (40) %


---------------------
Capture probabilities

PK  =  0.8550 (9)
PL1  =  0.11715 (38)
PL2  =  0.00140 (18)
PM1  =  0.02237 (17)
PM2  =  2.84E-4 (39)
PN1  =  0.003346 (43)
PN2  =  3.4E-5 (5)
PO1  =  4.05E-4 (33)

K =  0.8550 (9)
L =  0.1185 (6)
M =  0.02265 (21)
N =  0.003379 (48)
O =  4.05E-4 (33)


------------------------------------------------------------
Input log ft value (ec): 9.1

Log ft value (ec)    =  9.08 (6)
with log f           =  -1.56 (6)
and log partial T1/2 =  10.638 (13)

