--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 38-Sr-85 [9/2+] g.s.  -->  Daughter nucleus: 37-Rb-85 [5/2-] g.s.
Calculation of the 1st forbidden unique transition from the electron capture decay of Sr-85

Transition energy: 1065.0 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12533 (27)
PL2/PK =  0.00150 (19)
PL3/PK =  0.00100 (14)
PM1/PK =  0.02367 (15)
PM2/PK =  3.02E-4 (41)
PM3/PK =  1.83E-4 (26)
PN1/PK =  0.003534 (40)
PM4/PK =  2.12E-7 (35)
PN2/PK =  3.6E-5 (5)
PN3/PK =  1.79E-5 (28)
PO1/PK =  4.28E-4 (35)

L/K =  0.1278 (6)
M/K =  0.02415 (21)
N/K =  0.003587 (48)
O/K =  4.28E-4 (35)


------------------------------
Relative capture probabilities

PK  =  0.8650 (7)
PL1 =  0.10842 (15)
PL2 =  0.00130 (17)
PL3 =  8.7E-4 (12)
PM1 =  0.02047 (11)
PM2 =  2.61E-4 (35)
PM3 =  1.58E-4 (22)
PN1 =  0.003057 (32)
PM4 =  1.83E-7 (30)
PN2 =  3.08E-5 (45)
PN3 =  1.54E-5 (24)
PO1 =  3.70E-4 (30)

K =  0.8650 (7)
L =  0.11059 (43)
M =  0.02089 (17)
N =  0.003103 (39)
O =  3.70E-4 (30)


--------------------------
Capture-to-positron ratios

K/b+ =  2.2E7 (13)
L1/b+ =  2.7E6 (16)
L2/b+ =  3.3E4 (17)
L3/b+ =  2.2E4 (12)
M1/b+ =  5.1E5 (29)
M2/b+ =  6.5E3 (35)
M3/b+ =  4.0E3 (22)
N1/b+ =  7.7E4 (44)
M4/b+ =  4.6 (27)
N2/b+ =  7.7E2 (43)
N3/b+ =  3.9E2 (22)
O1/b+ =  9.3E3 (47)

K/b+ =  2.2E7 (13)
L/b+ =  2.8E6 (16)
M/b+ =  5.2E5 (30)
N/b+ =  7.8E4 (44)
O/b+ =  9.3E3 (47)

EC/b+ =  2.5E7 (14)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.80 (40) %   Iec =   0.80 (40) %   Ib+ =   0. %
Iec      =   0.80 (40) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.80 (40) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8650 (7)
PL1  =  0.10842 (15)
PL2  =  0.00130 (17)
PL3  =  8.7E-4 (12)
PM1  =  0.02047 (11)
PM2  =  2.61E-4 (35)
PM3  =  1.58E-4 (22)
PN1  =  0.003057 (32)
PM4  =  1.83E-7 (30)
PN2  =  3.08E-5 (45)
PN3  =  1.54E-5 (24)
PO1  =  3.70E-4 (30)

K =  0.8650 (7)
L =  0.11059 (43)
M =  0.02089 (17)
N =  0.003103 (39)
O =  3.70E-4 (30)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.3

Log ft value (ec)    =  9.43 (22)
with log f           =  0.587 (47)
and log partial T1/2 =  8.85 (22)

