--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 22-Ti-44 [0+] g.s.  -->  Daughter nucleus: 21-Sc-44 [0-] 146.220 (30) keV
The 1st forbidden non-unique transition from the electron capture decay of Ti-44 is calculated as allowed

Transition energy: 121.3 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1156 (8)
PL2/PK =  4.006E-4 (30)
PM1/PK =  0.01723 (29)
PM2/PK =  5.34E-5 (11)
PN1/PK =  0.001600 (24)

L/K =  0.1160 (8)
M/K =  0.01728 (29)
N/K =  0.001600 (24)


------------------------------
Relative capture probabilities

PK  =  0.8812 (8)
PL1 =  0.1018 (6)
PL2 =  3.530E-4 (23)
PM1 =  0.01518 (24)
PM2 =  4.71E-5 (9)
PN1 =  0.001410 (19)

K =  0.8812 (8)
L =  0.1022 (6)
M =  0.01523 (24)
N =  0.001410 (19)


------------------------------
Capture branch from input data

Iec =   99.6 (11) %


---------------------
Capture probabilities

PK  =  0.8812 (8)
PL1  =  0.1018 (6)
PL2  =  3.530E-4 (23)
PM1  =  0.01518 (24)
PM2  =  4.71E-5 (9)
PN1  =  0.001410 (19)

K =  0.8812 (8)
L =  0.1022 (6)
M =  0.01523 (24)
N =  0.001410 (19)


------------------------------------------------------------
Input log ft value (ec): 6.5

Log ft value (ec)    =  6.505 (25)
with log f           =  -2.774 (23)
and log partial T1/2 =  9.279 (9)

