--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 22-Ti-44 [0+] g.s.  -->  Daughter nucleus: 21-Sc-44 [1-] 67.8680 (14) keV
The 1st forbidden non-unique transition from the electron capture decay of Ti-44 is calculated as allowed

Transition energy: 199.6 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1126 (7)
PL2/PK =  3.905E-4 (27)
PM1/PK =  0.01674 (26)
PM2/PK =  5.20E-5 (10)
PN1/PK =  0.001554 (22)

L/K =  0.1130 (7)
M/K =  0.01679 (27)
N/K =  0.001554 (22)


------------------------------
Relative capture probabilities

PK  =  0.8839 (7)
PL1 =  0.0995 (5)
PL2 =  3.452E-4 (21)
PM1 =  0.01480 (22)
PM2 =  4.59E-5 (8)
PN1 =  0.001374 (18)

K =  0.8839 (7)
L =  0.0999 (5)
M =  0.01484 (22)
N =  0.001374 (18)


------------------------------
Capture branch from input data

Iec =   0.4 (11) %


---------------------
Capture probabilities

PK  =  0.8839 (7)
PL1  =  0.0995 (5)
PL2  =  3.452E-4 (21)
PM1  =  0.01480 (22)
PM2  =  4.59E-5 (8)
PN1  =  0.001374 (18)

K =  0.8839 (7)
L =  0.0999 (5)
M =  0.01484 (22)
N =  0.001374 (18)


------------------------------------------------------------
Input log ft value (ec): 9.3

Log ft value (ec)    =  9.3 (12)
with log f           =  -2.330 (17)
and log partial T1/2 =  11.7 (12)

