--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 47-Ag-108 [1+] g.s.  -->  Daughter nucleus: 46-Pd-108 [2+] 1441.16 (5) keV
Calculation of the allowed transition from the electron capture decay of Ag-108

Transition energy: 481 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12926 (31)
PL2/PK =  0.002545 (7)
PM1/PK =  0.02731 (15)
PM2/PK =  5.656E-4 (33)
PN1/PK =  0.00596 (6)
PN2/PK =  1.104E-4 (11)

L/K =  0.13180 (32)
M/K =  0.02788 (16)
N/K =  0.00607 (6)


------------------------------
Relative capture probabilities

PK  =  0.85781 (39)
PL1 =  0.11088 (22)
PL2 =  0.0021835 (47)
PM1 =  0.02343 (12)
PM2 =  4.852E-4 (26)
PN1 =  0.005114 (46)
PN2 =  9.47E-5 (9)

K =  0.85781 (39)
L =  0.11306 (22)
M =  0.02392 (12)
N =  0.005209 (46)


------------------------------
Capture branch from input data

Iec =   0.0170 (21) %


---------------------
Capture probabilities

PK  =  0.85781 (39)
PL1  =  0.11088 (22)
PL2  =  0.0021835 (47)
PM1  =  0.02343 (12)
PM2  =  4.852E-4 (26)
PN1  =  0.005114 (46)
PN2  =  9.47E-5 (9)

K =  0.85781 (39)
L =  0.11306 (22)
M =  0.02392 (12)
N =  0.005209 (46)


------------------------------------------------------------
Input log ft value (ec): 5.46

Log ft value (ec)    =  5.57 (6)
with log f           =  -0.351 (12)
and log partial T1/2 =  5.92 (5)

