--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 47-Ag-108 [1+] g.s.  -->  Daughter nucleus: 46-Pd-108 [0+] g.s.
Calculation of the allowed transition from the electron capture decay of Ag-108

Transition energy: 1922 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12097 (16)
PL2/PK =  0.0024225 (36)
PM1/PK =  0.02533 (11)
PM2/PK =  5.337E-4 (25)
PN1/PK =  0.005520 (45)
PN2/PK =  1.040E-4 (9)

L/K =  0.12339 (16)
M/K =  0.02587 (11)
N/K =  0.005624 (46)


------------------------------
Relative capture probabilities

PK  =  0.86589 (24)
PL1 =  0.10474 (11)
PL2 =  0.0020976 (26)
PM1 =  0.02194 (9)
PM2 =  4.621E-4 (20)
PN1 =  0.004780 (37)
PN2 =  9.01E-5 (7)

K =  0.86589 (24)
L =  0.10684 (11)
M =  0.02240 (9)
N =  0.004870 (38)


--------------------------
Capture-to-positron ratios

K/b+ =  6.28 (16)
L1/b+ =  0.760 (20)
L2/b+ =  0.01522 (41)
M1/b+ =  0.1592 (48)
M2/b+ =  0.00335 (10)
N1/b+ =  0.0347 (12)
N2/b+ =  6.53E-4 (22)

K/b+ =  6.28 (16)
L/b+ =  0.775 (21)
M/b+ =  0.1625 (49)
N/b+ =  0.0353 (12)

EC/b+ =  7.26 (19)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   2.01 (12) %   Iec =   1.73 (12) %   Ib+ =   0.280 (20) %
Iec      =   1.73 (12) % (input data kept)
Ib+      =   0.280 (20) % (input data kept)
Iec tot. =   2.01 (12) % (input data kept)


---------------------
Capture probabilities

PK  =  0.7610 (24)
PL1  =  0.09206 (30)
PL2  =  0.001844 (6)
PM1  =  0.01928 (10)
PM2  =  4.061E-4 (22)
PN1  =  0.004201 (35)
PN2  =  7.92E-5 (7)

K =  0.7610 (24)
L =  0.09390 (31)
M =  0.01968 (10)
N =  0.004280 (36)


------------------------------------------------------------
Input log ft value (ec & beta +): 4.7

Log ft value (ec)    =  4.801 (30)
with log f           =  0.8836 (37)
and log partial T1/2 =  3.917 (30)

