--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 47-Ag-108 [1+] g.s.  -->  Daughter nucleus: 46-Pd-108 [0+] 1314.20 (10) keV
Calculation of the allowed transition from the electron capture decay of Ag-108

Transition energy: 608 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12685 (25)
PL2/PK =  0.002501 (5)
PM1/PK =  0.02674 (14)
PM2/PK =  5.545E-4 (30)
PN1/PK =  0.00583 (5)
PN2/PK =  1.082E-4 (10)

L/K =  0.12935 (25)
M/K =  0.02729 (14)
N/K =  0.00594 (5)


------------------------------
Relative capture probabilities

PK  =  0.86015 (33)
PL1 =  0.10911 (17)
PL2 =  0.0021517 (39)
PM1 =  0.02300 (11)
PM2 =  4.770E-4 (24)
PN1 =  0.005018 (42)
PN2 =  9.31E-5 (8)

K =  0.86015 (33)
L =  0.11126 (18)
M =  0.02348 (11)
N =  0.005111 (43)


------------------------------
Capture branch from input data

Iec =   0.0038 (6) %


---------------------
Capture probabilities

PK  =  0.86015 (33)
PL1  =  0.10911 (17)
PL2  =  0.0021517 (39)
PM1  =  0.02300 (11)
PM2  =  4.770E-4 (24)
PN1  =  0.005018 (42)
PN2  =  9.31E-5 (8)

K =  0.86015 (33)
L =  0.11126 (18)
M =  0.02348 (11)
N =  0.005111 (43)


------------------------------------------------------------
Input log ft value (ec): 6.37

Log ft value (ec)    =  6.44 (7)
with log f           =  -0.139 (10)
and log partial T1/2 =  6.58 (7)

