--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 47-Ag-108 [1+] g.s.  -->  Daughter nucleus: 46-Pd-108 [0+] 1052.80 (5) keV
Calculation of the allowed transition from the electron capture decay of Ag-108

Transition energy: 869 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12420 (20)
PL2/PK =  0.0024565 (44)
PM1/PK =  0.02611 (12)
PM2/PK =  5.431E-4 (27)
PN1/PK =  0.005693 (48)
PN2/PK =  1.059E-4 (9)

L/K =  0.12666 (20)
M/K =  0.02665 (13)
N/K =  0.005799 (49)


------------------------------
Relative capture probabilities

PK  =  0.86273 (28)
PL1 =  0.10716 (14)
PL2 =  0.0021193 (31)
PM1 =  0.02252 (10)
PM2 =  4.685E-4 (22)
PN1 =  0.004911 (40)
PN2 =  9.14E-5 (8)

K =  0.86273 (28)
L =  0.10927 (14)
M =  0.02299 (10)
N =  0.005003 (41)


------------------------------
Capture branch from input data

Iec =   0.243 (39) %


---------------------
Capture probabilities

PK  =  0.86273 (28)
PL1  =  0.10716 (14)
PL2  =  0.0021193 (31)
PM1  =  0.02252 (10)
PM2  =  4.685E-4 (22)
PN1  =  0.004911 (40)
PN2  =  9.14E-5 (8)

K =  0.86273 (28)
L =  0.10927 (14)
M =  0.02299 (10)
N =  0.005003 (41)


------------------------------------------------------------
Input log ft value (ec): 4.89

Log ft value (ec)    =  4.95 (7)
with log f           =  0.182 (7)
and log partial T1/2 =  4.77 (7)

