--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 47-Ag-108 [1+] g.s.  -->  Daughter nucleus: 46-Pd-108 [1+] 1539.95 (7) keV
Calculation of the allowed transition from the electron capture decay of Ag-108

Transition energy: 382 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13234 (41)
PL2/PK =  0.002604 (9)
PM1/PK =  0.02805 (18)
PM2/PK =  5.803E-4 (39)
PN1/PK =  0.00613 (6)
PN2/PK =  1.133E-4 (12)

L/K =  0.13494 (42)
M/K =  0.02863 (18)
N/K =  0.00624 (6)


------------------------------
Relative capture probabilities

PK  =  0.85484 (49)
PL1 =  0.11313 (29)
PL2 =  0.002226 (6)
PM1 =  0.02398 (14)
PM2 =  4.960E-4 (30)
PN1 =  0.00524 (5)
PN2 =  9.69E-5 (10)

K =  0.85484 (49)
L =  0.11535 (29)
M =  0.02448 (14)
N =  0.00533 (5)


------------------------------
Capture branch from input data

Iec =   0.00224 (27) %


---------------------
Capture probabilities

PK  =  0.85484 (49)
PL1  =  0.11313 (29)
PL2  =  0.002226 (6)
PM1  =  0.02398 (14)
PM2  =  4.960E-4 (30)
PN1  =  0.00524 (5)
PN2  =  9.69E-5 (10)

K =  0.85484 (49)
L =  0.11535 (29)
M =  0.02448 (14)
N =  0.00533 (5)


------------------------------------------------------------
Input log ft value (ec): 6.12

Log ft value (ec)    =  6.24 (5)
with log f           =  -0.561 (16)
and log partial T1/2 =  6.80 (5)

