--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 18-Ar-37 [3/2+] g.s.  -->  Daughter nucleus: 17-Cl-37 [3/2+] g.s.
Calculation of the allowed transition from the electron capture decay of Ar-37

Transition energy: 813.87 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.09243 (45)
PL2/PK =  1.714E-4 (10)
PM1/PK =  0.01368 (17)
PM2/PK =  1.829E-5 (26)

L/K =  0.09260 (45)
M/K =  0.01370 (17)


------------------------------
Relative capture probabilities

PK  =  0.9039 (5)
PL1 =  0.08355 (36)
PL2 =  1.549E-4 (8)
PM1 =  0.01237 (15)
PM2 =  1.653E-5 (23)

K =  0.9039 (5)
L =  0.08371 (36)
M =  0.01239 (15)


------------------------------
Capture branch from input data

Iec =   100. %


---------------------
Capture probabilities

PK  =  0.9039 (5)
PL1  =  0.08355 (36)
PL2  =  1.549E-4 (8)
PM1  =  0.01237 (15)
PM2  =  1.653E-5 (23)

K =  0.9039 (5)
L =  0.08371 (36)
M =  0.01239 (15)


------------------------------------------------------------
Input log ft value (ec): 5.1

Log ft value (ec)    =  5.101 (5)
with log f           =  -1.379 (5)
and log partial T1/2 =  6.48071 (24)

