--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 85-At-211 [9/2-] g.s.  -->  Daughter nucleus: 84-Po-211 [11/2+] 687.2 (7) keV
The 1st forbidden non-unique transition from the electron capture decay of At-211 is calculated as allowed

Transition energy: 98.2 (26) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  3E1 (7)
PL2/PK =  3 (6)
PM1/PK =  10 (22)
PM2/PK =  1.0 (21)
PN1/PK =  3 (7)
PN2/PK =  0.3 (6)
PO1/PK =  0.8 (17)
PO2/PK =  0.07 (15)
PP1/PK =  0.13 (29)
PP2/PK =  0.007 (16)

L/K =  3E1 (7)
M/K =  11 (24)
N/K =  3 (7)
O/K =  0.9 (19)
P/K =  0.14 (31)


------------------------------
Relative capture probabilities

PK  =  0.019 (18)
PL1 =  0.622 (10)
PL2 =  0.0538 (11)
PM1 =  0.200 (5)
PM2 =  0.0190 (5)
PN1 =  0.0606 (18)
PN2 =  0.00569 (15)
PO1 =  0.0153 (5)
PO2 =  0.001323 (42)
PP1 =  0.00256 (11)
PP2 =  1.44E-4 (6)

K =  0.019 (18)
L =  0.676 (11)
M =  0.219 (6)
N =  0.0662 (20)
O =  0.0166 (6)
P =  0.00270 (11)


------------------------------
Capture branch from input data

Iec =   0.258 (13) %


---------------------
Capture probabilities

PK  =  0.019 (18)
PL1  =  0.622 (10)
PL2  =  0.0538 (11)
PM1  =  0.200 (5)
PM2  =  0.0190 (5)
PN1  =  0.0606 (18)
PN2  =  0.00569 (15)
PO1  =  0.0153 (5)
PO2  =  0.001323 (42)
PP1  =  0.00256 (11)
PP2  =  1.44E-4 (6)

K =  0.019 (18)
L =  0.676 (11)
M =  0.219 (6)
N =  0.0662 (20)
O =  0.0166 (6)
P =  0.00270 (11)


------------------------------------------------------------
Input log ft value (ec): 5.77

Log ft value (ec)    =  5.853 (44)
with log f           =  -1.150 (38)
and log partial T1/2 =  7.003 (22)

