--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 39-Y-88 [4-] g.s.  -->  Daughter nucleus: 38-Sr-88 [2+] 1836.090 (8) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of Y-88

Transition energy: 1786.5 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12010 (20)
PL2/PK =  0.001527 (19)
PL3/PK =  3.55E-4 (5)
PM1/PK =  0.02304 (12)
PM2/PK =  3.10E-4 (5)
PM3/PK =  6.62E-5 (12)
PN1/PK =  0.003802 (43)
PM4/PK =  7.69E-8 (20)
PN2/PK =  4.22E-5 (10)
PN3/PK =  7.61E-6 (21)
PO1/PK =  4.16E-4 (8)

L/K =  0.12198 (22)
M/K =  0.02342 (12)
N/K =  0.003852 (44)
O/K =  4.16E-4 (8)


------------------------------
Relative capture probabilities

PK  =  0.86982 (30)
PL1 =  0.10447 (13)
PL2 =  0.001328 (16)
PL3 =  3.088E-4 (43)
PM1 =  0.02004 (9)
PM2 =  2.698E-4 (42)
PM3 =  5.76E-5 (10)
PN1 =  0.003307 (36)
PM4 =  6.69E-8 (17)
PN2 =  3.67E-5 (9)
PN3 =  6.62E-6 (18)
PO1 =  3.62E-4 (7)

K =  0.86982 (30)
L =  0.10610 (15)
M =  0.02037 (10)
N =  0.003351 (37)
O =  3.62E-4 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  22.5 (6)
L1/b+ =  2.70 (6)
L2/b+ =  0.03435 (46)
L3/b+ =  0.00799 (12)
M1/b+ =  0.518 (11)
M2/b+ =  0.00698 (7)
M3/b+ =  0.001490 (17)
N1/b+ =  0.0855 (12)
M4/b+ =  1.730E-6 (28)
N2/b+ =  9.48E-4 (13)
N3/b+ =  1.711E-4 (30)
O1/b+ =  0.00936 (9)

K/b+ =  22.5 (6)
L/b+ =  2.74 (6)
M/b+ =  0.527 (11)
N/b+ =  0.0866 (12)
O/b+ =  0.00936 (9)

EC/b+ =  25.9 (6)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   5.910 (30) %   Iec =   5.70 (30) %   Ib+ =   0.210 (10) %
Iec      =   5.70 (30) % (input data kept)
Ib+      =   0.210 (10) % (input data kept)
Iec tot. =   5.91 (30) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8374 (8)
PL1  =  0.10058 (16)
PL2  =  0.001279 (15)
PL3  =  2.973E-4 (41)
PM1  =  0.01929 (9)
PM2  =  2.598E-4 (41)
PM3  =  5.55E-5 (10)
PN1  =  0.003184 (35)
PM4  =  6.44E-8 (17)
PN2  =  3.53E-5 (8)
PN3  =  6.37E-6 (18)
PO1  =  3.48E-4 (7)

K =  0.8374 (8)
L =  0.10215 (18)
M =  0.01961 (10)
N =  0.003226 (36)
O =  3.48E-4 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.8

Log ft value (ec)    =  9.780 (25)
with log f           =  1.571 (9)
and log partial T1/2 =  8.209 (23)

