--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 39-Y-88 [4-] g.s.  -->  Daughter nucleus: 38-Sr-88 [3-] 2734.137 (8) keV
Calculation of the allowed transition from the electron capture decay of Y-88

Transition energy: 888.5 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12014 (20)
PL2/PK =  0.001517 (19)
PM1/PK =  0.02305 (12)
PM2/PK =  3.08E-4 (5)
PN1/PK =  0.003804 (43)
PN2/PK =  4.19E-5 (10)
PO1/PK =  4.16E-4 (8)

L/K =  0.12165 (22)
M/K =  0.02335 (12)
N/K =  0.003845 (44)
O/K =  4.16E-4 (8)


------------------------------
Relative capture probabilities

PK  =  0.87012 (30)
PL1 =  0.10453 (14)
PL2 =  0.001320 (16)
PM1 =  0.02005 (10)
PM2 =  2.681E-4 (42)
PN1 =  0.003310 (37)
PN2 =  3.64E-5 (9)
PO1 =  3.62E-4 (7)

K =  0.87012 (30)
L =  0.10585 (15)
M =  0.02032 (10)
N =  0.003346 (37)
O =  3.62E-4 (7)


------------------------------
Capture branch from input data

Iec =   94.30 (30) %


---------------------
Capture probabilities

PK  =  0.87012 (30)
PL1  =  0.10453 (14)
PL2  =  0.001320 (16)
PM1  =  0.02005 (10)
PM2  =  2.681E-4 (42)
PN1  =  0.003310 (37)
PN2  =  3.64E-5 (9)
PO1  =  3.62E-4 (7)

K =  0.87012 (30)
L =  0.10585 (15)
M =  0.02032 (10)
N =  0.003346 (37)
O =  3.62E-4 (7)


------------------------------------------------------------
Input log ft value (ec): 6.9

Log ft value (ec)    =  6.866 (9)
with log f           =  -0.124 (9)
and log partial T1/2 =  6.9899 (14)

