--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 39-Y-88 [4-] g.s.  -->  Daughter nucleus: 38-Sr-88 [5-] 3584.784 (19) keV
Calculation of the allowed transition from the electron capture decay of Y-88

Transition energy: 37.8 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.307 (18)
PL2/PK =  0.00387 (28)
PM1/PK =  0.0648 (44)
PM2/PK =  8.6E-4 (7)
PN1/PK =  0.0108 (8)
PN2/PK =  1.18E-4 (11)
PO1/PK =  0.00119 (10)

L/K =  0.311 (18)
M/K =  0.0656 (44)
N/K =  0.0110 (8)
O/K =  0.00119 (10)


------------------------------
Relative capture probabilities

PK  =  0.720 (12)
PL1 =  0.221 (9)
PL2 =  0.00279 (15)
PM1 =  0.0466 (23)
PM2 =  6.19E-4 (38)
PN1 =  0.00781 (44)
PN2 =  8.5E-5 (6)
PO1 =  8.6E-4 (6)

K =  0.720 (12)
L =  0.224 (9)
M =  0.0473 (23)
N =  0.00790 (45)
O =  8.6E-4 (6)


------------------------------
Capture branch from input data

Iec =   0.048 (18) %


---------------------
Capture probabilities

PK  =  0.720 (12)
PL1  =  0.221 (9)
PL2  =  0.00279 (15)
PM1  =  0.0466 (23)
PM2  =  6.19E-4 (38)
PN1  =  0.00781 (44)
PN2  =  8.5E-5 (6)
PO1  =  8.6E-4 (6)

K =  0.720 (12)
L =  0.224 (9)
M =  0.0473 (23)
N =  0.00790 (45)
O =  8.6E-4 (6)


------------------------------------------------------------
Input log ft value (ec): 7.

Log ft value (ec)    =  7.04 (17)
with log f           =  -3.24 (6)
and log partial T1/2 =  10.28 (16)

