--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 1325.5131 (24) keV
The 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed

Transition energy: 1834.1 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13052 (19)
PL2/PK =  0.003412 (8)
PM1/PK =  0.02847 (14)
PM2/PK =  8.196E-4 (10)
PN1/PK =  0.00639 (6)
PN2/PK =  1.728E-4 (11)
PO1/PK =  0.001051 (18)
PO2/PK =  1.771E-5 (26)

L/K =  0.13393 (18)
M/K =  0.02929 (14)
N/K =  0.00657 (6)
O/K =  0.001069 (18)


------------------------------
Relative capture probabilities

PK  =  0.85408 (29)
PL1 =  0.11147 (12)
PL2 =  0.002914 (8)
PM1 =  0.02431 (11)
PM2 =  7.000E-4 (6)
PN1 =  0.00546 (5)
PN2 =  1.476E-4 (9)
PO1 =  8.98E-4 (15)
PO2 =  1.512E-5 (22)

K =  0.85408 (29)
L =  0.11439 (11)
M =  0.02501 (11)
N =  0.00561 (5)
O =  9.13E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  16.20 (27)
L1/b+ =  2.114 (32)
L2/b+ =  0.0553 (10)
M1/b+ =  0.461 (5)
M2/b+ =  0.01327 (20)
N1/b+ =  0.1036 (10)
N2/b+ =  0.002799 (29)
O1/b+ =  0.01702 (29)
O2/b+ =  2.868E-4 (43)

K/b+ =  16.20 (27)
L/b+ =  2.169 (33)
M/b+ =  0.474 (6)
N/b+ =  0.1064 (10)
O/b+ =  0.01731 (29)

EC/b+ =  18.96 (31)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   5.72 (18) %   Iec =   5.43 (18) %   Ib+ =   0.286 (11) %
Iec      =   5.43 (18) %
Ib+      =   0.287 (10) %
Iec tot. =   5.72 (18) %


---------------------
Capture probabilities

PK  =  0.8113 (7)
PL1  =  0.10589 (14)
PL2  =  0.002768 (8)
PM1  =  0.02310 (11)
PM2  =  6.649E-4 (8)
PN1  =  0.00519 (5)
PN2  =  1.402E-4 (8)
PO1  =  8.53E-4 (14)
PO2  =  1.436E-5 (21)

K =  0.8113 (7)
L =  0.10866 (14)
M =  0.02376 (11)
N =  0.00533 (5)
O =  8.67E-4 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.897

Log ft value (ec)    =  7.896 (15)
with log f           =  1.0740 (43)
and log partial T1/2 =  6.822 (14)

