--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [0+] 1657.283 (22) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124

Transition energy: 1502.3 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13617 (20)
PL2/PK =  0.003535 (9)
PL3/PK =  9.243E-4 (43)
PM1/PK =  0.02988 (15)
PM2/PK =  8.542E-4 (11)
PM3/PK =  2.118E-4 (9)
PN1/PK =  0.00672 (7)
PM4/PK =  5.85E-7 (8)
PN2/PK =  1.803E-4 (11)
PN3/PK =  3.977E-5 (39)
PO1/PK =  0.001105 (19)
PN4/PK =  9.48E-8 (20)
PO2/PK =  1.848E-5 (27)
PO3/PK =  2.178E-6 (46)

L/K =  0.14063 (20)
M/K =  0.03095 (15)
N/K =  0.00694 (7)
O/K =  0.001126 (19)


------------------------------
Relative capture probabilities

PK  =  0.84772 (31)
PL1 =  0.11543 (13)
PL2 =  0.002997 (8)
PL3 =  7.835E-4 (39)
PM1 =  0.02533 (12)
PM2 =  7.241E-4 (6)
PM3 =  1.795E-4 (7)
PN1 =  0.00570 (5)
PM4 =  4.96E-7 (7)
PN2 =  1.528E-4 (9)
PN3 =  3.372E-5 (32)
PO1 =  9.37E-4 (16)
PN4 =  8.04E-8 (17)
PO2 =  1.566E-5 (23)
PO3 =  1.847E-6 (38)

K =  0.84772 (31)
L =  0.11921 (12)
M =  0.02623 (12)
N =  0.00588 (6)
O =  9.54E-4 (16)


--------------------------
Capture-to-positron ratios

K/b+ =  741 (19)
L1/b+ =  100.9 (25)
L2/b+ =  2.62 (7)
L3/b+ =  0.685 (21)
M1/b+ =  22.14 (47)
M2/b+ =  0.633 (16)
M3/b+ =  0.1570 (42)
N1/b+ =  4.98 (10)
M4/b+ =  4.33E-4 (10)
N2/b+ =  0.1336 (27)
N3/b+ =  0.0295 (6)
O1/b+ =  0.819 (22)
N4/b+ =  7.02E-5 (22)
O2/b+ =  0.01369 (34)
O3/b+ =  0.00161 (5)

K/b+ =  741 (19)
L/b+ =  104.2 (26)
M/b+ =  22.94 (49)
N/b+ =  5.14 (10)
O/b+ =  0.834 (22)

EC/b+ =  874 (22)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.106 (8) %   Iec =   0.106 (8) %   Ib+ =   1.21E-4 (10) %
Iec      =   0.106 (8) %
Ib+      =   1.21E-4 (10) %
Iec tot. =   0.106 (8) %


---------------------
Capture probabilities

PK  =  0.84675 (31)
PL1  =  0.11530 (13)
PL2  =  0.002994 (8)
PL3  =  7.826E-4 (39)
PM1  =  0.02530 (12)
PM2  =  7.233E-4 (6)
PM3  =  1.793E-4 (7)
PN1  =  0.00569 (5)
PM4  =  4.95E-7 (7)
PN2  =  1.527E-4 (9)
PN3  =  3.368E-5 (32)
PO1  =  9.36E-4 (16)
PN4  =  8.03E-8 (17)
PO2  =  1.564E-5 (23)
PO3  =  1.845E-6 (38)

K =  0.84675 (31)
L =  0.11908 (12)
M =  0.02620 (12)
N =  0.00588 (6)
O =  9.53E-4 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 10.351

Log ft value (ec)    =  10.351 (33)
with log f           =  1.819 (6)
and log partial T1/2 =  8.532 (33)

