--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [0+] 1882.920 (30) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124

Transition energy: 1276.7 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13793 (21)
PL2/PK =  0.003572 (9)
PL3/PK =  0.001294 (7)
PM1/PK =  0.03032 (15)
PM2/PK =  8.644E-4 (11)
PM3/PK =  2.969E-4 (15)
PN1/PK =  0.00682 (7)
PM4/PK =  8.20E-7 (12)
PN2/PK =  1.825E-4 (12)
PN3/PK =  5.58E-5 (6)
PO1/PK =  0.001122 (19)
PN4/PK =  1.329E-7 (29)
PO2/PK =  1.871E-5 (28)
PO3/PK =  3.05E-6 (7)

L/K =  0.14280 (21)
M/K =  0.03148 (16)
N/K =  0.00706 (7)
O/K =  0.001143 (19)


------------------------------
Relative capture probabilities

PK  =  0.84568 (32)
PL1 =  0.11664 (13)
PL2 =  0.003021 (9)
PL3 =  0.001095 (6)
PM1 =  0.02564 (12)
PM2 =  7.310E-4 (6)
PM3 =  2.511E-4 (11)
PN1 =  0.00577 (6)
PM4 =  6.93E-7 (10)
PN2 =  1.544E-4 (9)
PN3 =  4.715E-5 (47)
PO1 =  9.49E-4 (16)
PN4 =  1.124E-7 (24)
PO2 =  1.582E-5 (23)
PO3 =  2.58E-6 (5)

K =  0.84568 (32)
L =  0.12076 (13)
M =  0.02663 (12)
N =  0.00597 (6)
O =  9.67E-4 (16)


--------------------------
Capture-to-positron ratios

K/b+ =  1.45E4 (7)
L1/b+ =  2.00E3 (9)
L2/b+ =  51.7 (25)
L3/b+ =  18.7 (9)
M1/b+ =  439 (18)
M2/b+ =  12.5 (6)
M3/b+ =  4.30 (20)
N1/b+ =  98.7 (39)
M4/b+ =  0.0119 (5)
N2/b+ =  2.64 (10)
N3/b+ =  0.807 (34)
O1/b+ =  16.2 (8)
N4/b+ =  0.00192 (10)
O2/b+ =  0.271 (12)
O3/b+ =  0.0442 (23)

K/b+ =  1.45E4 (7)
L/b+ =  2.07E3 (9)
M/b+ =  456 (19)
N/b+ =  102.2 (40)
O/b+ =  16.5 (8)

EC/b+ =  1.71E4 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.025 (16) %   Iec =   0.025 (16) %   Ib+ =   0. %
Iec      =   0.025 (16) %
Ib+      =   1.5E-6 (9) %
Iec tot. =   0.025 (16) %


---------------------
Capture probabilities

PK  =  0.84563 (32)
PL1  =  0.11664 (13)
PL2  =  0.003020 (9)
PL3  =  0.001095 (6)
PM1  =  0.02564 (12)
PM2  =  7.310E-4 (6)
PM3  =  2.510E-4 (11)
PN1  =  0.00577 (6)
PM4  =  6.93E-7 (10)
PN2  =  1.544E-4 (9)
PN3  =  4.715E-5 (47)
PO1  =  9.49E-4 (16)
PN4  =  1.124E-7 (24)
PO2  =  1.582E-5 (23)
PO3  =  2.58E-6 (5)

K =  0.84563 (32)
L =  0.12075 (13)
M =  0.02662 (12)
N =  0.00597 (6)
O =  9.67E-4 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 10.69

Log ft value (ec)    =  10.69 (28)
with log f           =  1.530 (6)
and log partial T1/2 =  9.16 (28)

