--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [0+] g.s.
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124

Transition energy: 3159.6 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13112 (19)
PL2/PK =  0.003470 (8)
PL3/PK =  2.044E-4 (7)
PM1/PK =  0.02862 (14)
PM2/PK =  8.339E-4 (10)
PM3/PK =  4.672E-5 (14)
PN1/PK =  0.00643 (6)
PM4/PK =  1.289E-7 (17)
PN2/PK =  1.759E-4 (11)
PN3/PK =  8.77E-6 (7)
PO1/PK =  0.001057 (18)
PN4/PK =  2.090E-8 (41)
PO2/PK =  1.802E-5 (27)
PO3/PK =  4.80E-7 (9)

L/K =  0.13480 (18)
M/K =  0.02950 (14)
N/K =  0.00661 (6)
O/K =  0.001075 (18)


------------------------------
Relative capture probabilities

PK  =  0.85325 (29)
PL1 =  0.11188 (12)
PL2 =  0.002961 (8)
PL3 =  1.744E-4 (6)
PM1 =  0.02442 (11)
PM2 =  7.116E-4 (6)
PM3 =  3.986E-5 (11)
PN1 =  0.00549 (5)
PM4 =  1.100E-7 (14)
PN2 =  1.500E-4 (9)
PN3 =  7.48E-6 (6)
PO1 =  9.02E-4 (15)
PN4 =  1.783E-8 (34)
PO2 =  1.537E-5 (22)
PO3 =  4.10E-7 (8)

K =  0.85325 (29)
L =  0.11502 (11)
M =  0.02517 (11)
N =  0.00564 (5)
O =  9.17E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  1.991 (22)
L1/b+ =  0.2611 (26)
L2/b+ =  0.00691 (9)
L3/b+ =  4.07E-4 (6)
M1/b+ =  0.05698 (37)
M2/b+ =  0.001660 (17)
M3/b+ =  9.30E-5 (10)
N1/b+ =  0.01280 (6)
M4/b+ =  2.567E-7 (20)
N2/b+ =  3.501E-4 (18)
N3/b+ =  1.746E-5 (9)
O1/b+ =  0.002104 (25)
N4/b+ =  4.16E-8 (6)
O2/b+ =  3.587E-5 (34)
O3/b+ =  9.56E-7 (14)

K/b+ =  1.991 (22)
L/b+ =  0.2684 (27)
M/b+ =  0.05874 (38)
N/b+ =  0.01317 (6)
O/b+ =  0.002141 (25)

EC/b+ =  2.334 (25)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   34.40 (36) %   Iec =   24.08 (32) %   Ib+ =   10.32 (16) %
Iec      =   24.08 (33) %
Ib+      =   10.32 (13) %
Iec tot. =   34.40 (36) %


---------------------
Capture probabilities

PK  =  0.5973 (20)
PL1  =  0.07832 (27)
PL2  =  0.002072 (9)
PL3  =  1.221E-4 (6)
PM1  =  0.01709 (10)
PM2  =  4.981E-4 (17)
PM3  =  2.791E-5 (12)
PN1  =  0.003840 (39)
PM4  =  7.70E-8 (10)
PN2  =  1.050E-4 (7)
PN3  =  5.238E-6 (46)
PO1  =  6.31E-4 (11)
PN4  =  1.248E-8 (24)
PO2  =  1.076E-5 (16)
PO3  =  2.87E-7 (6)

K =  0.5973 (20)
L =  0.08051 (27)
M =  0.01762 (10)
N =  0.003950 (39)
O =  6.42E-4 (11)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.3095

Log ft value (ec)    =  9.305 (8)
with log f           =  3.1290 (45)
and log partial T1/2 =  6.176 (6)

