--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [4+] 1248.5811 (25) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124

Transition energy: 1911.0 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13408 (20)
PL2/PK =  0.003498 (9)
PL3/PK =  5.644E-4 (23)
PM1/PK =  0.02936 (15)
PM2/PK =  8.433E-4 (10)
PM3/PK =  1.292E-4 (5)
PN1/PK =  0.00660 (7)
PM4/PK =  3.566E-7 (49)
PN2/PK =  1.779E-4 (11)
PN3/PK =  2.426E-5 (22)
PO1/PK =  0.001085 (18)
PN4/PK =  5.78E-8 (12)
PO2/PK =  1.823E-5 (27)
PO3/PK =  1.329E-6 (27)

L/K =  0.13814 (19)
M/K =  0.03033 (15)
N/K =  0.00680 (7)
O/K =  0.001104 (19)


------------------------------
Relative capture probabilities

PK  =  0.85007 (30)
PL1 =  0.11398 (13)
PL2 =  0.002973 (8)
PL3 =  4.797E-4 (21)
PM1 =  0.02496 (11)
PM2 =  7.168E-4 (6)
PM3 =  1.0982E-4 (39)
PN1 =  0.00561 (5)
PM4 =  3.031E-7 (40)
PN2 =  1.513E-4 (9)
PN3 =  2.062E-5 (18)
PO1 =  9.22E-4 (15)
PN4 =  4.91E-8 (10)
PO2 =  1.550E-5 (22)
PO3 =  1.129E-6 (23)

K =  0.85007 (30)
L =  0.11743 (12)
M =  0.02578 (12)
N =  0.00578 (5)
O =  9.39E-4 (16)


--------------------------
Capture-to-positron ratios

K/b+ =  53.5 (9)
L1/b+ =  7.18 (11)
L2/b+ =  0.1873 (36)
L3/b+ =  0.0302 (6)
M1/b+ =  1.572 (19)
M2/b+ =  0.0452 (7)
M3/b+ =  0.00692 (12)
N1/b+ =  0.3534 (37)
M4/b+ =  1.909E-5 (27)
N2/b+ =  0.00953 (10)
N3/b+ =  0.001299 (15)
O1/b+ =  0.0581 (10)
N4/b+ =  3.10E-6 (6)
O2/b+ =  9.76E-4 (15)
O3/b+ =  7.11E-5 (15)

K/b+ =  53.5 (9)
L/b+ =  7.40 (12)
M/b+ =  1.624 (20)
N/b+ =  0.3642 (37)
O/b+ =  0.0591 (10)

EC/b+ =  63.0 (10)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0120 (10) %   Iec =   0.012 (10) %   Ib+ =   1.9E-4 (16) %
Iec      =   0.0118 (10) %
Ib+      =   1.88E-4 (16) %
Iec tot. =   0.0120 (10) %


---------------------
Capture probabilities

PK  =  0.83678 (37)
PL1  =  0.11220 (13)
PL2  =  0.002927 (8)
PL3  =  4.722E-4 (21)
PM1  =  0.02457 (11)
PM2  =  7.056E-4 (6)
PM3  =  1.0811E-4 (38)
PN1  =  0.00552 (5)
PM4  =  2.984E-7 (40)
PN2  =  1.489E-4 (9)
PN3  =  2.030E-5 (18)
PO1  =  9.08E-4 (15)
PN4  =  4.84E-8 (10)
PO2  =  1.526E-5 (22)
PO3  =  1.112E-6 (22)

K =  0.83678 (37)
L =  0.11559 (12)
M =  0.02538 (11)
N =  0.00569 (5)
O =  9.24E-4 (15)


------------------------------------------------------------
Input log ft value (ec & beta +): 11.72

Log ft value (ec)    =  11.729 (37)
with log f           =  2.244 (5)
and log partial T1/2 =  9.485 (37)

