--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [3+] 2039.34 (6) keV
The 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed

Transition energy: 1120.3 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13302 (20)
PL2/PK =  0.003451 (9)
PM1/PK =  0.02909 (15)
PM2/PK =  8.310E-4 (10)
PN1/PK =  0.00654 (7)
PN2/PK =  1.753E-4 (11)
PO1/PK =  0.001075 (18)
PO2/PK =  1.796E-5 (27)

L/K =  0.13647 (19)
M/K =  0.02992 (15)
N/K =  0.00671 (7)
O/K =  0.001093 (19)


------------------------------
Relative capture probabilities

PK  =  0.85165 (31)
PL1 =  0.11328 (13)
PL2 =  0.002939 (8)
PM1 =  0.02477 (11)
PM2 =  7.077E-4 (6)
PN1 =  0.00557 (5)
PN2 =  1.493E-4 (9)
PO1 =  9.15E-4 (15)
PO2 =  1.530E-5 (22)

K =  0.85165 (31)
L =  0.11622 (12)
M =  0.02548 (12)
N =  0.00572 (5)
O =  9.31E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  1.26E5 (14)
L1/b+ =  1.68E4 (18)
L2/b+ =  435 (49)
M1/b+ =  3.67E3 (39)
M2/b+ =  105 (11)
N1/b+ =  8.2E2 (9)
N2/b+ =  22.1 (23)
O1/b+ =  135 (15)
O2/b+ =  2.26 (25)

K/b+ =  1.26E5 (14)
L/b+ =  1.72E4 (19)
M/b+ =  3.77E3 (40)
N/b+ =  8.5E2 (9)
O/b+ =  138 (16)

EC/b+ =  1.48E5 (16)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.026 (16) %   Iec =   0.026 (16) %   Ib+ =   0. %
Iec      =   0.026 (16) %
Ib+      =   1.8E-7 (11) %
Iec tot. =   0.026 (16) %


---------------------
Capture probabilities

PK  =  0.85164 (31)
PL1  =  0.11328 (13)
PL2  =  0.002939 (8)
PM1  =  0.02477 (11)
PM2  =  7.077E-4 (6)
PN1  =  0.00557 (5)
PN2  =  1.493E-4 (9)
PO1  =  9.15E-4 (15)
PO2  =  1.530E-5 (22)

K =  0.85164 (31)
L =  0.11622 (12)
M =  0.02548 (12)
N =  0.00572 (5)
O =  9.31E-4 (15)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.78

Log ft value (ec)    =  9.78 (27)
with log f           =  0.6366 (49)
and log partial T1/2 =  9.14 (27)

