--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1-] 3432.4060 (40) keV
The 1st forbidden non-unique transition from the electron capture decay of Ga-66 is calculated as allowed

Transition energy: 1742.6 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11123 (16)
PL2/PK =  8.38E-4 (31)
PM1/PK =  0.01841 (7)
PM2/PK =  1.36E-4 (5)
PN1/PK =  0.001476 (32)

L/K =  0.11207 (19)
M/K =  0.01855 (7)
N/K =  0.001476 (32)


------------------------------
Relative capture probabilities

PK  =  0.88332 (23)
PL1 =  0.09825 (12)
PL2 =  7.41E-4 (27)
PM1 =  0.01626 (6)
PM2 =  1.200E-4 (47)
PN1 =  0.001304 (28)

K =  0.88332 (23)
L =  0.09899 (14)
M =  0.01638 (6)
N =  0.001304 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  2.07 (9)
L1/b+ =  0.231 (9)
L2/b+ =  0.001738 (36)
M1/b+ =  0.0382 (15)
M2/b+ =  2.82E-4 (7)
N1/b+ =  0.00306 (7)

K/b+ =  2.07 (9)
L/b+ =  0.232 (9)
M/b+ =  0.0384 (15)
N/b+ =  0.00306 (7)

EC/b+ =  2.35 (10)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.550 (45) %   Iec =   0.390 (40) %   Ib+ =   0.160 (20) %
Iec      =   0.390 (40) % (input data kept)
Ib+      =   0.160 (20) % (input data kept)
Iec tot. =   0.550 (45) % (input data kept)


---------------------
Capture probabilities

PK  =  0.619 (8)
PL1  =  0.0689 (9)
PL2  =  5.19E-4 (20)
PM1  =  0.01140 (15)
PM2  =  8.41E-5 (35)
PN1  =  9.14E-4 (23)

K =  0.619 (8)
L =  0.0694 (9)
M =  0.01149 (15)
N =  9.14E-4 (23)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.03

Log ft value (ec)    =  7.032 (47)
with log f           =  0.090 (14)
and log partial T1/2 =  6.942 (45)

