--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 4675.6 (5) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 499.4 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11394 (19)
PL2/PK =  8.43E-4 (31)
PM1/PK =  0.01891 (7)
PM2/PK =  1.37E-4 (6)
PN1/PK =  0.001517 (33)

L/K =  0.11479 (22)
M/K =  0.01905 (8)
N/K =  0.001517 (33)


------------------------------
Relative capture probabilities

PK  =  0.88078 (26)
PL1 =  0.10036 (13)
PL2 =  7.43E-4 (27)
PM1 =  0.01666 (6)
PM2 =  1.207E-4 (48)
PN1 =  0.001336 (29)

K =  0.88078 (26)
L =  0.10110 (16)
M =  0.01678 (7)
N =  0.001336 (29)


------------------------------
Capture branch from input data

Iec =   0.0015 (5) %


---------------------
Capture probabilities

PK  =  0.88078 (26)
PL1  =  0.10036 (13)
PL2  =  7.43E-4 (27)
PM1  =  0.01666 (6)
PM2  =  1.207E-4 (48)
PN1  =  0.001336 (29)

K =  0.88078 (26)
L =  0.10110 (16)
M =  0.01678 (7)
N =  0.001336 (29)


------------------------------------------------------------
Input log ft value (ec): 8.35

Log ft value (ec)    =  8.35 (15)
with log f           =  -1.007 (18)
and log partial T1/2 =  9.36 (14)

