--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 4461.370 (5) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 713.6 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11279 (17)
PL2/PK =  8.37E-4 (31)
PM1/PK =  0.01870 (7)
PM2/PK =  1.36E-4 (5)
PN1/PK =  0.001500 (33)

L/K =  0.11362 (20)
M/K =  0.01884 (8)
N/K =  0.001500 (33)


------------------------------
Relative capture probabilities

PK  =  0.88187 (24)
PL1 =  0.09946 (12)
PL2 =  7.39E-4 (27)
PM1 =  0.01649 (6)
PM2 =  1.198E-4 (48)
PN1 =  0.001323 (28)

K =  0.88187 (24)
L =  0.10020 (15)
M =  0.01661 (6)
N =  0.001323 (28)


------------------------------
Capture branch from input data

Iec =   1.96 (17) %


---------------------
Capture probabilities

PK  =  0.88187 (24)
PL1  =  0.09946 (12)
PL2  =  7.39E-4 (27)
PM1  =  0.01649 (6)
PM2  =  1.198E-4 (48)
PN1  =  0.001323 (28)

K =  0.88187 (24)
L =  0.10020 (15)
M =  0.01661 (6)
N =  0.001323 (28)


------------------------------------------------------------
Input log ft value (ec): 5.54

Log ft value (ec)    =  5.549 (41)
with log f           =  -0.693 (16)
and log partial T1/2 =  6.241 (38)

