--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 3228.8840 (30) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 1946.1 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11112 (16)
PL2/PK =  8.40E-4 (30)
PM1/PK =  0.01839 (7)
PM2/PK =  1.36E-4 (5)
PN1/PK =  0.001475 (32)

L/K =  0.11196 (19)
M/K =  0.01853 (7)
N/K =  0.001475 (32)


------------------------------
Relative capture probabilities

PK  =  0.88342 (23)
PL1 =  0.09816 (12)
PL2 =  7.42E-4 (27)
PM1 =  0.01625 (6)
PM2 =  1.202E-4 (47)
PN1 =  0.001303 (28)

K =  0.88342 (23)
L =  0.09891 (14)
M =  0.01637 (6)
N =  0.001303 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  0.898 (35)
L1/b+ =  0.0998 (38)
L2/b+ =  7.54E-4 (13)
M1/b+ =  0.0165 (6)
M2/b+ =  1.222E-4 (24)
N1/b+ =  0.001324 (25)

K/b+ =  0.898 (35)
L/b+ =  0.1005 (38)
M/b+ =  0.0166 (6)
N/b+ =  0.001324 (25)

EC/b+ =  1.016 (39)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   7.40 (42) %   Iec =   3.70 (30) %   Ib+ =   3.70 (30) %
Iec      =   3.70 (30) % (input data kept)
Ib+      =   3.70 (30) % (input data kept)
Iec tot. =   7.40 (42) % (input data kept)


---------------------
Capture probabilities

PK  =  0.445 (9)
PL1  =  0.0495 (10)
PL2  =  3.74E-4 (15)
PM1  =  0.00819 (16)
PM2  =  6.06E-5 (26)
PN1  =  6.57E-4 (19)

K =  0.445 (9)
L =  0.0499 (10)
M =  0.00825 (16)
N =  6.57E-4 (19)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.14

Log ft value (ec)    =  6.152 (38)
with log f           =  0.186 (14)
and log partial T1/2 =  5.965 (35)

