--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [0+] g.s.
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 5175.0 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11053 (16)
PL2/PK =  8.74E-4 (30)
PM1/PK =  0.01828 (7)
PM2/PK =  1.42E-4 (5)
PN1/PK =  0.001466 (32)

L/K =  0.11140 (19)
M/K =  0.01842 (7)
N/K =  0.001466 (32)


------------------------------
Relative capture probabilities

PK  =  0.88395 (23)
PL1 =  0.09770 (11)
PL2 =  7.73E-4 (27)
PM1 =  0.01616 (6)
PM2 =  1.251E-4 (47)
PN1 =  0.001296 (28)

K =  0.88395 (23)
L =  0.09847 (14)
M =  0.01628 (6)
N =  0.001296 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  0.00864 (26)
L1/b+ =  9.55E-4 (28)
L2/b+ =  7.55E-6 (5)
M1/b+ =  1.579E-4 (42)
M2/b+ =  1.222E-6 (12)
N1/b+ =  1.266E-5 (12)

K/b+ =  0.00864 (26)
L/b+ =  9.62E-4 (28)
M/b+ =  1.592E-4 (42)
N/b+ =  1.266E-5 (12)

EC/b+ =  0.00977 (29)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   50.50 (40) %   Iec =   0.470 (40) %   Ib+ =   50.0 (40) %
Iec      =   0.470 (40) % (input data kept)
Ib+      =   50.0 (40) % (input data kept)
Iec tot. =   50.5 (40) % (input data kept)


---------------------
Capture probabilities

PK  =  0.00856 (25)
PL1  =  9.46E-4 (28)
PL2  =  7.48E-6 (34)
PM1  =  1.564E-4 (47)
PM2  =  1.21E-6 (6)
PN1  =  1.254E-5 (46)

K =  0.00856 (25)
L =  9.53E-4 (28)
M =  1.576E-4 (47)
N =  1.254E-5 (46)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.88

Log ft value (ec)    =  7.907 (39)
with log f           =  1.046 (13)
and log partial T1/2 =  6.861 (37)

