--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 4638.24 (14) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 536.8 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11367 (18)
PL2/PK =  8.42E-4 (31)
PM1/PK =  0.01886 (7)
PM2/PK =  1.37E-4 (6)
PN1/PK =  0.001513 (33)

L/K =  0.11451 (21)
M/K =  0.01900 (8)
N/K =  0.001513 (33)


------------------------------
Relative capture probabilities

PK  =  0.88103 (25)
PL1 =  0.10015 (13)
PL2 =  7.42E-4 (27)
PM1 =  0.01662 (6)
PM2 =  1.205E-4 (48)
PN1 =  0.001333 (29)

K =  0.88103 (25)
L =  0.10089 (16)
M =  0.01674 (6)
N =  0.001333 (29)


------------------------------
Capture branch from input data

Iec =   0.0042 (10) %


---------------------
Capture probabilities

PK  =  0.88103 (25)
PL1  =  0.10015 (13)
PL2  =  7.42E-4 (27)
PM1  =  0.01662 (6)
PM2  =  1.205E-4 (48)
PN1  =  0.001333 (29)

K =  0.88103 (25)
L =  0.10089 (16)
M =  0.01674 (6)
N =  0.001333 (29)


------------------------------------------------------------
Input log ft value (ec): 7.96

Log ft value (ec)    =  7.97 (10)
with log f           =  -0.943 (18)
and log partial T1/2 =  8.91 (10)

