--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 4958.20 (40) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 216.8 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11919 (31)
PL2/PK =  8.79E-4 (34)
PM1/PK =  0.01989 (10)
PM2/PK =  1.44E-4 (6)
PN1/PK =  0.001597 (37)

L/K =  0.12007 (34)
M/K =  0.02004 (11)
N/K =  0.001597 (37)


------------------------------
Relative capture probabilities

PK  =  0.87589 (37)
PL1 =  0.10440 (22)
PL2 =  7.70E-4 (29)
PM1 =  0.01742 (8)
PM2 =  1.26E-4 (5)
PN1 =  0.001399 (32)

K =  0.87589 (37)
L =  0.10517 (25)
M =  0.01755 (8)
N =  0.001399 (32)


------------------------------
Capture branch from input data

Iec =   0.0020 (5) %


---------------------
Capture probabilities

PK  =  0.87589 (37)
PL1  =  0.10440 (22)
PL2  =  7.70E-4 (29)
PM1  =  0.01742 (8)
PM2  =  1.26E-4 (5)
PN1  =  0.001399 (32)

K =  0.87589 (37)
L =  0.10517 (25)
M =  0.01755 (8)
N =  0.001399 (32)


------------------------------------------------------------
Input log ft value (ec): 7.48

Log ft value (ec)    =  7.48 (11)
with log f           =  -1.752 (26)
and log partial T1/2 =  9.23 (11)

