--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1-] 3380.9420 (40) keV
The 1st forbidden non-unique transition from the electron capture decay of Ga-66 is calculated as allowed

Transition energy: 1794.1 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11120 (16)
PL2/PK =  8.39E-4 (31)
PM1/PK =  0.01840 (7)
PM2/PK =  1.36E-4 (5)
PN1/PK =  0.001476 (32)

L/K =  0.11204 (19)
M/K =  0.01854 (7)
N/K =  0.001476 (32)


------------------------------
Relative capture probabilities

PK  =  0.88335 (23)
PL1 =  0.09823 (12)
PL2 =  7.41E-4 (27)
PM1 =  0.01626 (6)
PM2 =  1.200E-4 (47)
PN1 =  0.001304 (28)

K =  0.88335 (23)
L =  0.09897 (14)
M =  0.01638 (6)
N =  0.001304 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  1.64 (7)
L1/b+ =  0.182 (7)
L2/b+ =  0.001375 (27)
M1/b+ =  0.0302 (11)
M2/b+ =  2.23E-4 (5)
N1/b+ =  0.00242 (5)

K/b+ =  1.64 (7)
L/b+ =  0.184 (7)
M/b+ =  0.0304 (11)
N/b+ =  0.00242 (5)

EC/b+ =  1.86 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   2.01 (13) %   Iec =   1.31 (11) %   Ib+ =   0.70 (6) %
Iec      =   1.31 (11) % (input data kept)
Ib+      =   0.70 (6) % (input data kept)
Iec tot. =   2.01 (13) % (input data kept)


---------------------
Capture probabilities

PK  =  0.574 (8)
PL1  =  0.0638 (9)
PL2  =  4.82E-4 (19)
PM1  =  0.01057 (16)
PM2  =  7.80E-5 (33)
PN1  =  8.47E-4 (22)

K =  0.574 (8)
L =  0.0643 (9)
M =  0.01064 (16)
N =  8.47E-4 (22)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.53

Log ft value (ec)    =  6.532 (39)
with log f           =  0.115 (14)
and log partial T1/2 =  6.416 (37)

