--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 4806.197 (5) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 368.8 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11533 (21)
PL2/PK =  8.52E-4 (32)
PM1/PK =  0.01917 (8)
PM2/PK =  1.39E-4 (6)
PN1/PK =  0.001538 (34)

L/K =  0.11618 (24)
M/K =  0.01931 (8)
N/K =  0.001538 (34)


------------------------------
Relative capture probabilities

PK  =  0.87948 (28)
PL1 =  0.10143 (15)
PL2 =  7.50E-4 (28)
PM1 =  0.01686 (6)
PM2 =  1.219E-4 (49)
PN1 =  0.001353 (29)

K =  0.87948 (28)
L =  0.10218 (18)
M =  0.01698 (7)
N =  0.001353 (29)


------------------------------
Capture branch from input data

Iec =   2.27 (19) %


---------------------
Capture probabilities

PK  =  0.87948 (28)
PL1  =  0.10143 (15)
PL2  =  7.50E-4 (28)
PM1  =  0.01686 (6)
PM2  =  1.219E-4 (49)
PN1  =  0.001353 (29)

K =  0.87948 (28)
L =  0.10218 (18)
M =  0.01698 (7)
N =  0.001353 (29)


------------------------------------------------------------
Input log ft value (ec): 4.9

Log ft value (ec)    =  4.902 (42)
with log f           =  -1.276 (20)
and log partial T1/2 =  6.177 (36)

