--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [2+] 3882.422 (10) keV
The 2nd forbidden non-unique transition from the electron capture decay of Ga-66 is calculated as 1st forbidden unique

Transition energy: 1292.6 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11305 (17)
PL2/PK =  8.41E-4 (31)
PL3/PK =  4.15E-4 (17)
PM1/PK =  0.01875 (7)
PM2/PK =  1.37E-4 (5)
PM3/PK =  6.17E-5 (28)
PN1/PK =  0.001504 (33)
PM4/PK =  2.06E-8 (8)

L/K =  0.11431 (22)
M/K =  0.01895 (8)
N/K =  0.001504 (33)


------------------------------
Relative capture probabilities

PK  =  0.88124 (25)
PL1 =  0.09963 (12)
PL2 =  7.41E-4 (27)
PL3 =  3.66E-4 (15)
PM1 =  0.01652 (6)
PM2 =  1.203E-4 (48)
PM3 =  5.43E-5 (25)
PN1 =  0.001325 (28)
PM4 =  1.82E-8 (7)

K =  0.88124 (25)
L =  0.10074 (16)
M =  0.01670 (6)
N =  0.001325 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  7.3E2 (6)
L1/b+ =  83 (7)
L2/b+ =  0.615 (37)
L3/b+ =  0.303 (20)
M1/b+ =  13.7 (11)
M2/b+ =  0.100 (6)
M3/b+ =  0.0451 (31)
N1/b+ =  1.10 (7)
M4/b+ =  1.51E-5 (10)

K/b+ =  7.3E2 (6)
L/b+ =  84 (7)
M/b+ =  13.8 (11)
N/b+ =  1.10 (7)

EC/b+ =  8.3E2 (7)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0014 (9) %   Iec =   0.0014 (9) %   Ib+ =   0. %
Iec      =   0.0014 (9) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.0014 (9) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88018 (27)
PL1  =  0.09951 (12)
PL2  =  7.41E-4 (27)
PL3  =  3.65E-4 (15)
PM1  =  0.01650 (6)
PM2  =  1.202E-4 (48)
PM3  =  5.43E-5 (25)
PN1  =  0.001324 (28)
PM4  =  1.81E-8 (7)

K =  0.88018 (27)
L =  0.10061 (16)
M =  0.01668 (6)
N =  0.001324 (28)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.2

Log ft value (ec)    =  10.02 (28)
with log f           =  0.629 (17)
and log partial T1/2 =  9.39 (28)

