--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 4085.9820 (40) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 1089.0 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11187 (16)
PL2/PK =  8.35E-4 (31)
PM1/PK =  0.01853 (7)
PM2/PK =  1.35E-4 (5)
PN1/PK =  0.001486 (32)

L/K =  0.11271 (19)
M/K =  0.01867 (7)
N/K =  0.001486 (32)


------------------------------
Relative capture probabilities

PK  =  0.88272 (24)
PL1 =  0.09875 (12)
PL2 =  7.37E-4 (27)
PM1 =  0.01636 (6)
PM2 =  1.195E-4 (47)
PN1 =  0.001312 (28)

K =  0.88272 (24)
L =  0.09949 (15)
M =  0.01648 (6)
N =  0.001312 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  2.8E4 (7)
L1/b+ =  3.1E3 (8)
L2/b+ =  23 (6)
M1/b+ =  5.1E2 (13)
M2/b+ =  3.8 (9)
N1/b+ =  41 (10)

K/b+ =  2.8E4 (7)
L/b+ =  3.1E3 (8)
M/b+ =  5.2E2 (13)
N/b+ =  41 (10)

EC/b+ =  3.1E4 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.67 (14) %   Iec =   1.67 (14) %   Ib+ =   0. %
Iec      =   1.67 (14) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   1.67 (14) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88269 (24)
PL1  =  0.09875 (12)
PL2  =  7.37E-4 (27)
PM1  =  0.01636 (6)
PM2  =  1.195E-4 (47)
PN1  =  0.001312 (28)

K =  0.88269 (24)
L =  0.09949 (15)
M =  0.01648 (6)
N =  0.001312 (28)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.99

Log ft value (ec)    =  5.989 (39)
with log f           =  -0.322 (15)
and log partial T1/2 =  6.311 (37)

