--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 4866.054 (16) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 308.9 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11638 (23)
PL2/PK =  8.59E-4 (32)
PM1/PK =  0.01937 (8)
PM2/PK =  1.40E-4 (6)
PN1/PK =  0.001554 (35)

L/K =  0.11723 (26)
M/K =  0.01951 (9)
N/K =  0.001554 (35)


------------------------------
Relative capture probabilities

PK  =  0.87851 (30)
PL1 =  0.10224 (17)
PL2 =  7.55E-4 (28)
PM1 =  0.01701 (7)
PM2 =  1.23E-4 (5)
PN1 =  0.001365 (30)

K =  0.87851 (30)
L =  0.10299 (20)
M =  0.01714 (7)
N =  0.001365 (30)


------------------------------
Capture branch from input data

Iec =   0.047 (6) %


---------------------
Capture probabilities

PK  =  0.87851 (30)
PL1  =  0.10224 (17)
PL2  =  7.55E-4 (28)
PM1  =  0.01701 (7)
PM2  =  1.23E-4 (5)
PN1  =  0.001365 (30)

K =  0.87851 (30)
L =  0.10299 (20)
M =  0.01714 (7)
N =  0.001365 (30)


------------------------------------------------------------
Input log ft value (ec): 6.42

Log ft value (ec)    =  6.43 (6)
with log f           =  -1.434 (21)
and log partial T1/2 =  7.86 (6)

