--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-66 [0+] g.s.  -->  Daughter nucleus: 30-Zn-66 [1+] 5005.80 (30) keV
Calculation of the allowed transition from the electron capture decay of Ga-66

Transition energy: 169.2 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12195 (41)
PL2/PK =  8.99E-4 (35)
PM1/PK =  0.02041 (12)
PM2/PK =  1.47E-4 (6)
PN1/PK =  0.001639 (39)

L/K =  0.12285 (44)
M/K =  0.02055 (13)
N/K =  0.001639 (39)


------------------------------
Relative capture probabilities

PK  =  0.87333 (46)
PL1 =  0.10650 (30)
PL2 =  7.85E-4 (30)
PM1 =  0.01782 (9)
PM2 =  1.29E-4 (5)
PN1 =  0.001431 (33)

K =  0.87333 (46)
L =  0.10729 (33)
M =  0.01795 (10)
N =  0.001431 (33)


------------------------------
Capture branch from input data

Iec =   0.00122 (15) %


---------------------
Capture probabilities

PK  =  0.87333 (46)
PL1  =  0.10650 (30)
PL2  =  7.85E-4 (30)
PM1  =  0.01782 (9)
PM2  =  1.29E-4 (5)
PN1  =  0.001431 (33)

K =  0.87333 (46)
L =  0.10729 (33)
M =  0.01795 (10)
N =  0.001431 (33)


------------------------------------------------------------
Input log ft value (ec): 7.47

Log ft value (ec)    =  7.47 (6)
with log f           =  -1.977 (29)
and log partial T1/2 =  9.45 (5)

