--------------------------------------------------------------------------------------

BetaShape
Version: 2.3.1 (12/2023)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 11-Na-22 [3+] g.s.  -->  Daughter nucleus: 10-Ne-22 [2+] 1274.577 (7) keV
Calculation of the allowed transition from the electron capture decay of Na-22

Transition energy: 1568.44 (21) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.06787 (20)
PL2/PK =  2.576E-5 (6)

L/K =  0.0679 (2)


------------------------------
Relative capture probabilities

PK  =  0.93642 (17)
PL1 =  0.06356 (17)
PL2 =  2.412E-5 (5)

K =  0.93642 (17)
L =  0.06358 (17)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1040 (8)
L1/b+ =  0.007058 (37)
L2/b+ =  2.678E-6 (15)

K/b+ =  0.1040 (8)
L/b+ =  0.007060 (37)

EC/b+ =  0.1110 (9)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   99.94 (13) %   Iec =   9.64 (9) %   Ib+ =   90.30 (9) %
Iec      =   9.99 (7) %
Ib+      =   89.95 (11) %
Iec tot. =   99.94 (13) %


---------------------
Capture probabilities

PK  =  0.0936 (7)
PL1  =  0.006352 (49)
PL2  =  2.411E-6 (18)

K =  0.0936 (7)
L =  0.006355 (49)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.41

Log ft value (ec)    =  7.4132 (44)
with log f           =  -1.5018 (30)
or f-value           =  0.03149 (22)
and log partial T1/2 =  8.9150 (32)

