--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [4+] 2085.0583 (25) keV
Calculation of the allowed transition from the electron capture decay of Co-56

Transition energy: 2480.9 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11151 (27)
PL2/PK =  6.209E-4 (30)
PM1/PK =  0.01752 (10)
PM2/PK =  9.27E-5 (8)
PN1/PK =  0.001141 (8)

L/K =  0.11214 (27)
M/K =  0.01761 (10)
N/K =  0.001141 (8)


------------------------------
Relative capture probabilities

PK  =  0.88426 (30)
PL1 =  0.09861 (20)
PL2 =  5.491E-4 (25)
PM1 =  0.01549 (9)
PM2 =  8.19E-5 (7)
PN1 =  0.001009 (7)

K =  0.88426 (30)
L =  0.09916 (21)
M =  0.01558 (9)
N =  0.001009 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1189 (12)
L1/b+ =  0.01326 (10)
L2/b+ =  7.381E-5 (38)
M1/b+ =  0.002083 (9)
M2/b+ =  1.102E-5 (8)
N1/b+ =  1.357E-4 (8)

K/b+ =  0.1189 (12)
L/b+ =  0.01333 (10)
M/b+ =  0.002094 (9)
N/b+ =  1.357E-4 (8)

EC/b+ =  0.1345 (13)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   20.72 (16) %   Iec =   2.430 (30) %   Ib+ =   18.29 (16) %
Iec      =   2.430 (30) % (input data kept)
Ib+      =   18.29 (16) % (input data kept)
Iec tot. =   20.72 (16) % (input data kept)


---------------------
Capture probabilities

PK  =  0.1048 (9)
PL1  =  0.01169 (10)
PL2  =  6.51E-5 (6)
PM1  =  0.001836 (19)
PM2  =  9.71E-6 (12)
PN1  =  1.196E-4 (13)

K =  0.1048 (9)
L =  0.01175 (10)
M =  0.001846 (19)
N =  1.196E-4 (13)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.62

Log ft value (ec)    =  8.628 (6)
with log f           =  0.1894 (30)
and log partial T1/2 =  8.439 (5)

