--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [3+] 4048.799 (8) keV
Calculation of the allowed transition from the electron capture decay of Co-56

Transition energy: 517.2 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11365 (28)
PL2/PK =  6.148E-4 (31)
PM1/PK =  0.01790 (11)
PM2/PK =  9.19E-5 (8)
PN1/PK =  0.001166 (8)

L/K =  0.11426 (29)
M/K =  0.01799 (11)
N/K =  0.001166 (8)


------------------------------
Relative capture probabilities

PK  =  0.88229 (31)
PL1 =  0.10027 (21)
PL2 =  5.425E-4 (25)
PM1 =  0.01579 (9)
PM2 =  8.11E-5 (7)
PN1 =  0.001029 (7)

K =  0.88229 (31)
L =  0.10081 (22)
M =  0.01587 (9)
N =  0.001029 (7)


------------------------------
Capture branch from input data

Iec =   3.965 (15) %


---------------------
Capture probabilities

PK  =  0.88229 (31)
PL1  =  0.10027 (21)
PL2  =  5.425E-4 (25)
PM1  =  0.01579 (9)
PM2  =  8.11E-5 (7)
PN1  =  0.001029 (7)

K =  0.88229 (31)
L =  0.10081 (22)
M =  0.01587 (9)
N =  0.001029 (7)


------------------------------------------------------------
Input log ft value (ec): 7.04

Log ft value (ec)    =  7.043 (6)
with log f           =  -1.183 (6)
and log partial T1/2 =  8.2261 (16)

