--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [2+] 2959.905 (5) keV
The 2nd forbidden non-unique transition from the electron capture decay of Co-56 is calculated as 1st forbidden unique

Transition energy: 1606.1 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11268 (27)
PL2/PK =  6.158E-4 (30)
PL3/PK =  2.050E-4 (16)
PM1/PK =  0.01773 (11)
PM2/PK =  9.20E-5 (8)
PM3/PK =  2.749E-5 (34)
PN1/PK =  0.001155 (8)
PM4/PK =  4.32E-9 (6)

L/K =  0.11350 (28)
M/K =  0.01784 (11)
N/K =  0.001155 (8)


------------------------------
Relative capture probabilities

PK  =  0.88300 (31)
PL1 =  0.09949 (21)
PL2 =  5.438E-4 (25)
PL3 =  1.810E-4 (14)
PM1 =  0.01565 (9)
PM2 =  8.12E-5 (7)
PM3 =  2.427E-5 (29)
PN1 =  0.001020 (7)
PM4 =  3.81E-9 (5)

K =  0.88300 (31)
L =  0.10022 (21)
M =  0.01576 (9)
N =  0.001020 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  13.88 (28)
L1/b+ =  1.564 (28)
L2/b+ =  0.00855 (13)
L3/b+ =  0.002845 (49)
M1/b+ =  0.2460 (36)
M2/b+ =  0.001277 (22)
M3/b+ =  3.81E-4 (8)
N1/b+ =  0.01603 (25)
M4/b+ =  5.99E-8 (13)

K/b+ =  13.88 (28)
L/b+ =  1.575 (28)
M/b+ =  0.2477 (36)
N/b+ =  0.01603 (25)

EC/b+ =  15.72 (31)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.032 (6) %   Iec =   0.023 (6) %   Ib+ =   0.0086 (22) %
Iec      =   0.023 (6) % (input data kept)
Ib+      =   0.0086 (22) % (input data kept)
Iec tot. =   0.032 (6) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8302 (10)
PL1  =  0.09354 (22)
PL2  =  5.112E-4 (24)
PL3  =  1.702E-4 (13)
PM1  =  0.01472 (8)
PM2  =  7.64E-5 (7)
PM3  =  2.282E-5 (27)
PN1  =  9.59E-4 (7)
PM4  =  3.585E-9 (48)

K =  0.8302 (10)
L =  0.09422 (23)
M =  0.01481 (8)
N =  9.59E-4 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 10.26

Log ft value (ec)    =  11.26 (11)
with log f           =  0.8007 (45)
and log partial T1/2 =  10.46 (11)

