--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [2-] 4447.60 (40) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of Co-56

Transition energy: 118.4 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1375 (9)
PL2/PK =  7.41E-4 (7)
PL3/PK =  0.0459 (21)
PM1/PK =  0.02213 (23)
PM2/PK =  1.130E-4 (15)
PM3/PK =  0.00622 (31)
PN1/PK =  0.001446 (17)
PM4/PK =  9.8E-7 (5)

L/K =  0.1842 (30)
M/K =  0.0285 (5)
N/K =  0.001446 (17)


------------------------------
Relative capture probabilities

PK  =  0.8237 (24)
PL1 =  0.11329 (39)
PL2 =  6.103E-4 (37)
PL3 =  0.0378 (16)
PM1 =  0.01823 (13)
PM2 =  9.30E-5 (10)
PM3 =  0.00512 (24)
PN1 =  0.001191 (10)
PM4 =  8.05E-7 (39)

K =  0.8237 (24)
L =  0.1517 (20)
M =  0.02344 (38)
N =  0.001191 (10)


------------------------------
Capture branch from input data

Iec =   0.0167 (5) %


---------------------
Capture probabilities

PK  =  0.8237 (24)
PL1  =  0.11329 (39)
PL2  =  6.103E-4 (37)
PL3  =  0.0378 (16)
PM1  =  0.01823 (13)
PM2  =  9.30E-5 (10)
PM3  =  0.00512 (24)
PN1  =  0.001191 (10)
PM4  =  8.05E-7 (39)

K =  0.8237 (24)
L =  0.1517 (20)
M =  0.02344 (38)
N =  0.001191 (10)


------------------------------------------------------------
Input log ft value (ec): 8.1

Log ft value (ec)    =  6.804 (36)
with log f           =  -3.797 (34)
and log partial T1/2 =  10.602 (13)

