--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [2+] 846.7700 (19) keV
The 2nd forbidden non-unique transition from the electron capture decay of Co-56 is calculated as 1st forbidden unique

Transition energy: 3719.2 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11170 (27)
PL2/PK =  6.311E-4 (30)
PL3/PK =  3.916E-5 (25)
PM1/PK =  0.01755 (10)
PM2/PK =  9.42E-5 (8)
PM3/PK =  5.25E-6 (6)
PN1/PK =  0.001143 (8)
PM4/PK =  8.24E-10 (10)

L/K =  0.11237 (27)
M/K =  0.01765 (10)
N/K =  0.001143 (8)


------------------------------
Relative capture probabilities

PK  =  0.88404 (30)
PL1 =  0.09875 (20)
PL2 =  5.579E-4 (25)
PL3 =  3.462E-5 (20)
PM1 =  0.01552 (9)
PM2 =  8.33E-5 (7)
PM3 =  4.639E-6 (48)
PN1 =  0.001011 (7)
PM4 =  7.29E-10 (8)

K =  0.88404 (30)
L =  0.09934 (21)
M =  0.01561 (9)
N =  0.001011 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  0.04657 (38)
L1/b+ =  0.005202 (30)
L2/b+ =  2.938E-5 (10)
L3/b+ =  1.823E-6 (7)
M1/b+ =  8.175E-4 (22)
M2/b+ =  4.386E-6 (23)
M3/b+ =  2.443E-7 (18)
N1/b+ =  5.325E-5 (20)
M4/b+ =  3.838E-11 (33)

K/b+ =  0.04657 (38)
L/b+ =  0.005233 (30)
M/b+ =  8.221E-4 (22)
N/b+ =  5.325E-5 (20)

EC/b+ =  0.05268 (41)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.26 (17) %   Iec =   0.0050 (30) %   Ib+ =   0.25 (17) %
Iec      =   0.0050 (30) % (input data kept)
Ib+      =   0.25 (17) % (input data kept)
Iec tot. =   0.26 (17) % (input data kept)


---------------------
Capture probabilities

PK  =  0.04424 (33)
PL1  =  0.004942 (38)
PL2  =  2.792E-5 (24)
PL3  =  1.732E-6 (16)
PM1  =  7.77E-4 (7)
PM2  =  4.168E-6 (46)
PM3  =  2.322E-7 (29)
PN1  =  5.06E-5 (5)
PM4  =  3.65E-11 (5)

K =  0.04424 (33)
L =  0.004971 (38)
M =  7.81E-4 (7)
N =  5.06E-5 (5)


------------------------------------------------------------
Input log ft value (ec & beta +): 11.6

Log ft value (ec)    =  13.39 (26)
with log f           =  2.2669 (33)
and log partial T1/2 =  11.13 (26)

