--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [2+] 3369.86 (11) keV
The 2nd forbidden non-unique transition from the electron capture decay of Co-56 is calculated as 1st forbidden unique

Transition energy: 1196.1 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11327 (28)
PL2/PK =  6.149E-4 (30)
PL3/PK =  3.692E-4 (33)
PM1/PK =  0.01783 (11)
PM2/PK =  9.19E-5 (8)
PM3/PK =  4.95E-5 (7)
PN1/PK =  0.001162 (8)
PM4/PK =  7.78E-9 (11)

L/K =  0.11426 (28)
M/K =  0.01797 (11)
N/K =  0.001162 (8)


------------------------------
Relative capture probabilities

PK  =  0.88231 (31)
PL1 =  0.09994 (21)
PL2 =  5.425E-4 (25)
PL3 =  3.258E-4 (28)
PM1 =  0.01573 (9)
PM2 =  8.11E-5 (7)
PM3 =  4.37E-5 (6)
PN1 =  0.001025 (7)
PM4 =  6.86E-9 (10)

K =  0.88231 (31)
L =  0.10081 (21)
M =  0.01586 (9)
N =  0.001025 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  3.10E3 (19)
L1/b+ =  352 (21)
L2/b+ =  1.91 (11)
L3/b+ =  1.15 (7)
M1/b+ =  55.4 (31)
M2/b+ =  0.285 (17)
M3/b+ =  0.154 (10)
N1/b+ =  3.61 (21)
M4/b+ =  2.42E-5 (16)

K/b+ =  3.10E3 (19)
L/b+ =  355 (21)
M/b+ =  55.8 (32)
N/b+ =  3.61 (21)

EC/b+ =  3.52E3 (22)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.015 (5) %   Iec =   0.015 (5) %   Ib+ =   0.6E-5 (20) %
Iec      =   0.015 (5) % (input data kept)
Ib+      =   0.6E-5 (20) % (input data kept)
Iec tot. =   0.015 (5) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88206 (31)
PL1  =  0.09991 (21)
PL2  =  5.424E-4 (25)
PL3  =  3.257E-4 (28)
PM1  =  0.01573 (9)
PM2  =  8.11E-5 (7)
PM3  =  4.37E-5 (6)
PN1  =  0.001025 (7)
PM4  =  6.86E-9 (10)

K =  0.88206 (31)
L =  0.10078 (21)
M =  0.01585 (9)
N =  0.001025 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 10.2

Log ft value (ec)    =  10.93 (14)
with log f           =  0.286 (5)
and log partial T1/2 =  10.65 (14)

