--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [4+] 4100.2730 (40) keV
Calculation of the allowed transition from the electron capture decay of Co-56

Transition energy: 465.7 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11395 (29)
PL2/PK =  6.160E-4 (31)
PM1/PK =  0.01795 (11)
PM2/PK =  9.21E-5 (8)
PN1/PK =  0.001170 (8)

L/K =  0.11457 (29)
M/K =  0.01804 (11)
N/K =  0.001170 (8)


------------------------------
Relative capture probabilities

PK  =  0.88200 (32)
PL1 =  0.10051 (22)
PL2 =  5.433E-4 (25)
PM1 =  0.01583 (9)
PM2 =  8.13E-5 (7)
PN1 =  0.001032 (7)

K =  0.88200 (32)
L =  0.10105 (22)
M =  0.01591 (9)
N =  0.001032 (7)


------------------------------
Capture branch from input data

Iec =   12.660 (40) %


---------------------
Capture probabilities

PK  =  0.88200 (32)
PL1  =  0.10051 (22)
PL2  =  5.433E-4 (25)
PM1  =  0.01583 (9)
PM2  =  8.13E-5 (7)
PN1  =  0.001032 (7)

K =  0.88200 (32)
L =  0.10105 (22)
M =  0.01591 (9)
N =  0.001032 (7)


------------------------------------------------------------
Input log ft value (ec): 6.44

Log ft value (ec)    =  6.447 (6)
with log f           =  -1.275 (6)
and log partial T1/2 =  7.7219 (14)

