--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [4+] 3122.9010 (30) keV
Calculation of the allowed transition from the electron capture decay of Co-56

Transition energy: 1443.1 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11191 (27)
PL2/PK =  6.138E-4 (30)
PM1/PK =  0.01759 (10)
PM2/PK =  9.16E-5 (8)
PN1/PK =  0.001146 (8)

L/K =  0.11253 (27)
M/K =  0.01768 (10)
N/K =  0.001146 (8)


------------------------------
Relative capture probabilities

PK  =  0.88390 (30)
PL1 =  0.09892 (21)
PL2 =  5.425E-4 (25)
PM1 =  0.01555 (9)
PM2 =  8.10E-5 (7)
PN1 =  0.001013 (7)

K =  0.88390 (30)
L =  0.09946 (21)
M =  0.01563 (9)
N =  0.001013 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  7.68 (18)
L1/b+ =  0.859 (18)
L2/b+ =  0.00471 (9)
M1/b+ =  0.1350 (24)
M2/b+ =  7.03E-4 (14)
N1/b+ =  0.00880 (16)

K/b+ =  7.68 (18)
L/b+ =  0.864 (18)
M/b+ =  0.1357 (24)
N/b+ =  0.00880 (16)

EC/b+ =  8.68 (20)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   10.03 (6) %   Iec =   8.99 (6) %   Ib+ =   1.040 (20) %
Iec      =   8.99 (6) % (input data kept)
Ib+      =   1.040 (20) % (input data kept)
Iec tot. =   10.03 (6) % (input data kept)


---------------------
Capture probabilities

PK  =  0.7926 (19)
PL1  =  0.08870 (28)
PL2  =  4.865E-4 (25)
PM1  =  0.01394 (8)
PM2  =  7.26E-5 (6)
PN1  =  9.08E-4 (6)

K =  0.7926 (19)
L =  0.08919 (28)
M =  0.01402 (8)
N =  9.08E-4 (6)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.58

Log ft value (ec)    =  7.5864 (46)
with log f           =  -0.2842 (35)
and log partial T1/2 =  7.8706 (29)

