--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [3+] 3856.4150 (30) keV
Calculation of the allowed transition from the electron capture decay of Co-56

Transition energy: 709.6 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11291 (28)
PL2/PK =  6.125E-4 (30)
PM1/PK =  0.01777 (11)
PM2/PK =  9.15E-5 (8)
PN1/PK =  0.001157 (8)

L/K =  0.11352 (28)
M/K =  0.01786 (11)
N/K =  0.001157 (8)


------------------------------
Relative capture probabilities

PK  =  0.88297 (31)
PL1 =  0.09970 (21)
PL2 =  5.409E-4 (25)
PM1 =  0.01569 (9)
PM2 =  8.08E-5 (7)
PN1 =  0.001022 (7)

K =  0.88297 (31)
L =  0.10024 (21)
M =  0.01577 (9)
N =  0.001022 (7)


------------------------------
Capture branch from input data

Iec =   16.86 (5) %


---------------------
Capture probabilities

PK  =  0.88297 (31)
PL1  =  0.09970 (21)
PL2  =  5.409E-4 (25)
PM1  =  0.01569 (9)
PM2  =  8.08E-5 (7)
PN1  =  0.001022 (7)

K =  0.88297 (31)
L =  0.10024 (21)
M =  0.01577 (9)
N =  0.001022 (7)


------------------------------------------------------------
Input log ft value (ec): 6.69

Log ft value (ec)    =  6.692 (5)
with log f           =  -0.9052 (48)
and log partial T1/2 =  7.5975 (13)

