--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [4+] 4458.300 (30) keV
Calculation of the allowed transition from the electron capture decay of Co-56

Transition energy: 107.7 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1249 (6)
PL2/PK =  6.727E-4 (49)
PM1/PK =  0.01988 (17)
PM2/PK =  1.016E-4 (12)
PN1/PK =  0.001297 (13)

L/K =  0.1256 (6)
M/K =  0.01998 (17)
N/K =  0.001297 (13)


------------------------------
Relative capture probabilities

PK  =  0.8719 (6)
PL1 =  0.10892 (44)
PL2 =  5.865E-4 (39)
PM1 =  0.01734 (14)
PM2 =  8.86E-5 (10)
PN1 =  0.001131 (10)

K =  0.8719 (6)
L =  0.10950 (45)
M =  0.01742 (14)
N =  0.001131 (10)


------------------------------
Capture branch from input data

Iec =   0.209 (7) %


---------------------
Capture probabilities

PK  =  0.8719 (6)
PL1  =  0.10892 (44)
PL2  =  5.865E-4 (39)
PM1  =  0.01734 (14)
PM2  =  8.86E-5 (10)
PN1  =  0.001131 (10)

K =  0.8719 (6)
L =  0.10950 (45)
M =  0.01742 (14)
N =  0.001131 (10)


------------------------------------------------------------
Input log ft value (ec): 6.91

Log ft value (ec)    =  6.917 (24)
with log f           =  -2.587 (20)
and log partial T1/2 =  9.504 (15)

