--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [3+] 3445.2700 (30) keV
Calculation of the allowed transition from the electron capture decay of Co-56

Transition energy: 1120.7 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11219 (27)
PL2/PK =  6.123E-4 (30)
PM1/PK =  0.01764 (10)
PM2/PK =  9.14E-5 (8)
PN1/PK =  0.001149 (8)

L/K =  0.11280 (28)
M/K =  0.01773 (11)
N/K =  0.001149 (8)


------------------------------
Relative capture probabilities

PK  =  0.88364 (30)
PL1 =  0.09913 (21)
PL2 =  5.411E-4 (25)
PM1 =  0.01559 (9)
PM2 =  8.08E-5 (7)
PN1 =  0.001015 (7)

K =  0.88364 (30)
L =  0.09968 (21)
M =  0.01567 (9)
N =  0.001015 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  2.35E3 (23)
L1/b+ =  264 (25)
L2/b+ =  1.44 (13)
M1/b+ =  41.4 (38)
M2/b+ =  0.215 (21)
N1/b+ =  2.70 (25)

K/b+ =  2.35E3 (23)
L/b+ =  265 (25)
M/b+ =  41.7 (38)
N/b+ =  2.70 (25)

EC/b+ =  2.66E3 (26)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   21.41 (5) %   Iec =   21.40 (5) %   Ib+ =   0.0080 (7) %
Iec      =   21.40 (5) % (input data kept)
Ib+      =   0.0080 (7) % (input data kept)
Iec tot. =   21.41 (5) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88331 (31)
PL1  =  0.09910 (21)
PL2  =  5.409E-4 (25)
PM1  =  0.01558 (9)
PM2  =  8.08E-5 (7)
PN1  =  0.001015 (7)

K =  0.88331 (31)
L =  0.09964 (21)
M =  0.01566 (9)
N =  0.001015 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.98

Log ft value (ec)    =  6.9888 (40)
with log f           =  -0.5051 (39)
and log partial T1/2 =  7.4939 (10)

