--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-56 [4+] g.s.  -->  Daughter nucleus: 26-Fe-56 [3+] 4394.82 (6) keV
Calculation of the allowed transition from the electron capture decay of Co-56

Transition energy: 171.2 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11942 (39)
PL2/PK =  6.432E-4 (38)
PM1/PK =  0.01891 (13)
PM2/PK =  9.67E-5 (10)
PN1/PK =  0.001233 (10)

L/K =  0.12007 (40)
M/K =  0.01901 (13)
N/K =  0.001233 (10)


------------------------------
Relative capture probabilities

PK  =  0.87696 (41)
PL1 =  0.10473 (30)
PL2 =  5.641E-4 (30)
PM1 =  0.01659 (11)
PM2 =  8.48E-5 (8)
PN1 =  0.001081 (8)

K =  0.87696 (41)
L =  0.10529 (30)
M =  0.01667 (11)
N =  0.001081 (8)


------------------------------
Capture branch from input data

Iec =   0.2159 (18) %


---------------------
Capture probabilities

PK  =  0.87696 (41)
PL1  =  0.10473 (30)
PL2  =  5.641E-4 (30)
PM1  =  0.01659 (11)
PM2  =  8.48E-5 (8)
PN1  =  0.001081 (8)

K =  0.87696 (41)
L =  0.10529 (30)
M =  0.01667 (11)
N =  0.001081 (8)


------------------------------------------------------------
Input log ft value (ec): 7.32

Log ft value (ec)    =  7.325 (13)
with log f           =  -2.165 (13)
and log partial T1/2 =  9.4901 (36)

