--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 24-Cr-51 [7/2-] g.s.  -->  Daughter nucleus: 23-V-51 [5/2-] 320.08350 (40) keV
Calculation of the allowed transition from the electron capture decay of Cr-51

Transition energy: 432.54 (24) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10875 (27)
PL2/PK =  4.32E-4 (5)
PM1/PK =  0.01723 (11)
PM2/PK =  6.35E-5 (11)
PN1/PK =  4.91E-4 (6)

L/K =  0.10918 (27)
M/K =  0.01729 (12)
N/K =  4.91E-4 (6)


------------------------------
Relative capture probabilities

PK  =  0.88734 (31)
PL1 =  0.09650 (20)
PL2 =  3.830E-4 (45)
PM1 =  0.01529 (10)
PM2 =  5.64E-5 (9)
PN1 =  4.354E-4 (49)

K =  0.88734 (31)
L =  0.09688 (21)
M =  0.01534 (10)
N =  4.354E-4 (49)


------------------------------
Capture branch from input data

Iec =   9.910 (20) %


---------------------
Capture probabilities

PK  =  0.88734 (31)
PL1  =  0.09650 (20)
PL2  =  3.830E-4 (45)
PM1  =  0.01529 (10)
PM2  =  5.64E-5 (9)
PN1  =  4.354E-4 (49)

K =  0.88734 (31)
L =  0.09688 (21)
M =  0.01534 (10)
N =  4.354E-4 (49)


------------------------------------------------------------
Input log ft value (ec): 5.86

Log ft value (ec)    =  5.870 (7)
with log f           =  -1.513 (7)
and log partial T1/2 =  7.3830 (9)

