--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 24-Cr-51 [7/2-] g.s.  -->  Daughter nucleus: 23-V-51 [7/2-] g.s.
Calculation of the allowed transition from the electron capture decay of Cr-51

Transition energy: 752.62 (24) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10773 (27)
PL2/PK =  4.30E-4 (5)
PM1/PK =  0.01705 (11)
PM2/PK =  6.32E-5 (10)
PN1/PK =  4.86E-4 (6)

L/K =  0.10816 (27)
M/K =  0.01711 (11)
N/K =  4.86E-4 (6)


------------------------------
Relative capture probabilities

PK  =  0.88829 (31)
PL1 =  0.09569 (20)
PL2 =  3.818E-4 (44)
PM1 =  0.01514 (9)
PM2 =  5.61E-5 (9)
PN1 =  4.313E-4 (49)

K =  0.88829 (31)
L =  0.09608 (21)
M =  0.01520 (10)
N =  4.313E-4 (49)


------------------------------
Capture branch from input data

Iec =   90.090 (20) %


---------------------
Capture probabilities

PK  =  0.88829 (31)
PL1  =  0.09569 (20)
PL2  =  3.818E-4 (44)
PM1  =  0.01514 (9)
PM2  =  5.61E-5 (9)
PN1  =  4.313E-4 (49)

K =  0.88829 (31)
L =  0.09608 (21)
M =  0.01520 (10)
N =  4.313E-4 (49)


------------------------------------------------------------
Input log ft value (ec): 5.39

Log ft value (ec)    =  5.397 (6)
with log f           =  -1.028 (6)
and log partial T1/2 =  6.42438 (12)

