--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 79-Au-195 [3/2+] g.s.  -->  Daughter nucleus: 78-Pt-195 [5/2-] 129.777 (5) keV
The 1st forbidden non-unique transition from the electron capture decay of Au-195 is calculated as allowed

Transition energy: 97.0 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  2.86 (25)
PL2/PK =  0.205 (18)
PM1/PK =  0.84 (8)
PM2/PK =  0.065 (6)
PN1/PK =  0.248 (24)
PN2/PK =  0.0188 (18)
PO1/PK =  0.058 (6)
PO2/PK =  0.00387 (39)
PP1/PK =  0.00171 (17)

L/K =  3.07 (27)
M/K =  0.91 (8)
N/K =  0.267 (26)
O/K =  0.062 (6)
P/K =  0.00171 (17)


------------------------------
Relative capture probabilities

PK  =  0.188 (13)
PL1 =  0.540 (8)
PL2 =  0.0386 (6)
PM1 =  0.1589 (29)
PM2 =  0.01230 (24)
PN1 =  0.0467 (10)
PN2 =  0.00355 (8)
PO1 =  0.01089 (28)
PO2 =  7.29E-4 (19)
PP1 =  3.22E-4 (8)

K =  0.188 (13)
L =  0.578 (9)
M =  0.1712 (32)
N =  0.0503 (11)
O =  0.01162 (29)
P =  3.22E-4 (8)


------------------------------
Capture branch from input data

Iec =   32.8 (30) %


---------------------
Capture probabilities

PK  =  0.188 (13)
PL1  =  0.540 (8)
PL2  =  0.0386 (6)
PM1  =  0.1589 (29)
PM2  =  0.01230 (24)
PN1  =  0.0467 (10)
PN2  =  0.00355 (8)
PO1  =  0.01089 (28)
PO2  =  7.29E-4 (19)
PP1  =  3.22E-4 (8)

K =  0.188 (13)
L =  0.578 (9)
M =  0.1712 (32)
N =  0.0503 (11)
O =  0.01162 (29)
P =  3.22E-4 (8)


------------------------------------------------------------
Input log ft value (ec): 6.3

Log ft value (ec)    =  6.392 (44)
with log f           =  -1.295 (18)
and log partial T1/2 =  7.687 (40)

