--------------------------------------------------------------------------------------

BetaShape
Version: 2.3.1 (12/2023)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 19-K-40 [4-] g.s.  -->  Daughter nucleus: 18-Ar-40 [2+] 1460.851 (6) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of K-40

Transition energy: 43.84 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1381 (11)
PL2/PK =  3.175E-4 (24)
PL3/PK =  0.1523 (22)
PM1/PK =  0.01868 (26)
PM2/PK =  3.354E-5 (25)
PM3/PK =  0.01260 (29)

L/K =  0.2907 (19)
M/K =  0.0313 (6)


------------------------------
Relative capture probabilities

PK  =  0.7564 (14)
PL1 =  0.1044 (6)
PL2 =  2.402E-4 (17)
PL3 =  0.1152 (15)
PM1 =  0.01413 (17)
PM2 =  2.537E-5 (14)
PM3 =  0.00953 (20)

K =  0.7564 (14)
L =  0.2199 (10)
M =  0.02369 (37)


------------------------------
Capture branch from input data

Iec =   10.55 (11) %


---------------------
Capture probabilities

PK  =  0.7564 (14)
PL1  =  0.1044 (6)
PL2  =  2.402E-4 (17)
PL3  =  0.1152 (15)
PM1  =  0.01413 (17)
PM2  =  2.537E-5 (14)
PM3  =  0.00953 (20)

K =  0.7564 (14)
L =  0.2199 (10)
M =  0.02369 (37)


------------------------------------------------------------
Input log ft value (ec): 11.55

Log ft value (ec)    =  11.537 (13)
with log f           =  -6.035 (13)
or f-value           =  9.22E-7 (26)
and log partial T1/2 =  17.5729 (46)

