--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [2+] 2067.35 (6) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 2265 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11724 (18)
PL2/PK =  0.001913 (38)
PM1/PK =  0.02357 (12)
PM2/PK =  4.02E-4 (10)
PN1/PK =  0.004735 (47)
PN2/PK =  7.12E-5 (21)
PO1/PK =  4.04E-4 (9)

L/K =  0.11915 (22)
M/K =  0.02397 (13)
N/K =  0.004806 (49)
O/K =  4.04E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.87083 (31)
PL1 =  0.10210 (12)
PL2 =  0.001666 (32)
PM1 =  0.02052 (10)
PM2 =  3.50E-4 (8)
PN1 =  0.004124 (39)
PN2 =  6.20E-5 (18)
PO1 =  3.52E-4 (7)

K =  0.87083 (31)
L =  0.10376 (15)
M =  0.02087 (11)
N =  0.004186 (41)
O =  3.52E-4 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  1.399 (45)
L1/b+ =  0.164 (5)
L2/b+ =  0.00268 (6)
M1/b+ =  0.0330 (9)
M2/b+ =  5.62E-4 (15)
N1/b+ =  0.00662 (15)
N2/b+ =  9.96E-5 (33)
O1/b+ =  5.65E-4 (14)

K/b+ =  1.399 (45)
L/b+ =  0.167 (5)
M/b+ =  0.0335 (9)
N/b+ =  0.00672 (15)
O/b+ =  5.65E-4 (14)

EC/b+ =  1.61 (5)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.56 (6) %   Iec =   0.34 (5) %   Ib+ =   0.220 (30) %
Iec      =   0.34 (5) % (input data kept)
Ib+      =   0.220 (30) % (input data kept)
Iec tot. =   0.56 (6) % (input data kept)


---------------------
Capture probabilities

PK  =  0.537 (7)
PL1  =  0.0629 (8)
PL2  =  0.001027 (24)
PM1  =  0.01265 (16)
PM2  =  2.16E-4 (6)
PN1  =  0.002541 (39)
PN2  =  3.82E-5 (12)
PO1  =  2.17E-4 (5)

K =  0.537 (7)
L =  0.0640 (8)
M =  0.01286 (17)
N =  0.002580 (40)
O =  2.17E-4 (5)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.8

Log ft value (ec)    =  6.82 (6)
with log f           =  0.863 (9)
and log partial T1/2 =  5.96 (6)

