--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [3+] 3331.74 (17) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 1000 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11951 (20)
PL2/PK =  0.001920 (39)
PM1/PK =  0.02408 (13)
PM2/PK =  4.04E-4 (10)
PN1/PK =  0.004842 (49)
PN2/PK =  7.17E-5 (22)
PO1/PK =  4.13E-4 (9)

L/K =  0.12143 (24)
M/K =  0.02449 (14)
N/K =  0.00491 (5)
O/K =  4.13E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.86863 (33)
PL1 =  0.10381 (14)
PL2 =  0.001668 (33)
PM1 =  0.02092 (10)
PM2 =  3.51E-4 (8)
PN1 =  0.004205 (41)
PN2 =  6.23E-5 (18)
PO1 =  3.59E-4 (8)

K =  0.86863 (33)
L =  0.10548 (17)
M =  0.02127 (11)
N =  0.004268 (43)
O =  3.59E-4 (8)


------------------------------
Capture branch from input data

Iec =   0.234 (20) %


---------------------
Capture probabilities

PK  =  0.86863 (33)
PL1  =  0.10381 (14)
PL2  =  0.001668 (33)
PM1  =  0.02092 (10)
PM2  =  3.51E-4 (8)
PN1  =  0.004205 (41)
PN2  =  6.23E-5 (18)
PO1  =  3.59E-4 (8)

K =  0.86863 (33)
L =  0.10548 (17)
M =  0.02127 (11)
N =  0.004268 (43)
O =  3.59E-4 (8)


------------------------------------------------------------
Input log ft value (ec): 6.3

Log ft value (ec)    =  6.267 (40)
with log f           =  0.144 (12)
and log partial T1/2 =  6.124 (38)

