--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [3+] 2965.41 (6) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 1367 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11841 (19)
PL2/PK =  0.001911 (38)
PM1/PK =  0.02383 (12)
PM2/PK =  4.02E-4 (10)
PN1/PK =  0.004790 (48)
PN2/PK =  7.12E-5 (21)
PO1/PK =  4.09E-4 (9)

L/K =  0.12032 (23)
M/K =  0.02424 (13)
N/K =  0.00486 (5)
O/K =  4.09E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.86970 (32)
PL1 =  0.10298 (13)
PL2 =  0.001662 (33)
PM1 =  0.02073 (10)
PM2 =  3.49E-4 (8)
PN1 =  0.004166 (40)
PN2 =  6.20E-5 (18)
PO1 =  3.56E-4 (8)

K =  0.86970 (32)
L =  0.10464 (16)
M =  0.02108 (11)
N =  0.004228 (42)
O =  3.56E-4 (8)


--------------------------
Capture-to-positron ratios

K/b+ =  139 (13)
L1/b+ =  16.5 (15)
L2/b+ =  0.266 (23)
M1/b+ =  3.32 (30)
M2/b+ =  0.056 (5)
N1/b+ =  0.67 (6)
N2/b+ =  0.0099 (10)
O1/b+ =  0.057 (5)

K/b+ =  139 (13)
L/b+ =  16.8 (16)
M/b+ =  3.38 (30)
N/b+ =  0.68 (6)
O/b+ =  0.057 (5)

EC/b+ =  160 (15)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.094 (14) %   Iec =   0.093 (14) %   Ib+ =   5.8E-4 (9) %
Iec      =   0.093 (14) % (input data kept)
Ib+      =   5.8E-4 (9) % (input data kept)
Iec tot. =   0.094 (14) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8643 (6)
PL1  =  0.10234 (14)
PL2  =  0.001652 (33)
PM1  =  0.02060 (10)
PM2  =  3.47E-4 (8)
PN1  =  0.004140 (40)
PN2  =  6.16E-5 (18)
PO1  =  3.53E-4 (7)

K =  0.8643 (6)
L =  0.10399 (17)
M =  0.02095 (11)
N =  0.004202 (42)
O =  3.53E-4 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.9

Log ft value (ec)    =  6.94 (7)
with log f           =  0.419 (10)
and log partial T1/2 =  6.52 (7)

