--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [2+] 2869.90 (8) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 1462 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11822 (19)
PL2/PK =  0.001910 (38)
PM1/PK =  0.02379 (12)
PM2/PK =  4.02E-4 (10)
PN1/PK =  0.004781 (48)
PN2/PK =  7.12E-5 (21)
PO1/PK =  4.08E-4 (9)

L/K =  0.12013 (23)
M/K =  0.02419 (13)
N/K =  0.00485 (5)
O/K =  4.08E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.86988 (32)
PL1 =  0.10283 (13)
PL2 =  0.001662 (33)
PM1 =  0.02069 (10)
PM2 =  3.49E-4 (8)
PN1 =  0.004159 (40)
PN2 =  6.19E-5 (18)
PO1 =  3.55E-4 (8)

K =  0.86988 (32)
L =  0.10450 (16)
M =  0.02104 (11)
N =  0.004221 (42)
O =  3.55E-4 (8)


--------------------------
Capture-to-positron ratios

K/b+ =  54.0 (40)
L1/b+ =  6.38 (47)
L2/b+ =  0.103 (7)
M1/b+ =  1.28 (9)
M2/b+ =  0.0217 (15)
N1/b+ =  0.258 (17)
N2/b+ =  0.00384 (30)
O1/b+ =  0.0220 (15)

K/b+ =  54.0 (40)
L/b+ =  6.48 (47)
M/b+ =  1.31 (9)
N/b+ =  0.262 (17)
O/b+ =  0.0220 (15)

EC/b+ =  62.0 (46)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.1520 (30) %   Iec =   0.150 (30) %   Ib+ =   0.0024 (5) %
Iec      =   0.150 (30) % (input data kept)
Ib+      =   0.0024 (5) % (input data kept)
Iec tot. =   0.152 (30) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8561 (11)
PL1  =  0.10120 (17)
PL2  =  0.001635 (32)
PM1  =  0.02037 (10)
PM2  =  3.44E-4 (8)
PN1  =  0.004093 (40)
PN2  =  6.09E-5 (18)
PO1  =  3.49E-4 (7)

K =  0.8561 (11)
L =  0.10284 (20)
M =  0.02071 (11)
N =  0.004154 (41)
O =  3.49E-4 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.8

Log ft value (ec)    =  6.80 (9)
with log f           =  0.479 (10)
and log partial T1/2 =  6.32 (9)

