--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [2+] 871.098 (16) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 3461 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11664 (17)
PL2/PK =  0.001932 (38)
PM1/PK =  0.02343 (12)
PM2/PK =  4.05E-4 (10)
PN1/PK =  0.004707 (46)
PN2/PK =  7.19E-5 (21)
PO1/PK =  4.02E-4 (9)

L/K =  0.11857 (21)
M/K =  0.02383 (13)
N/K =  0.004779 (48)
O/K =  4.02E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.87140 (30)
PL1 =  0.10164 (12)
PL2 =  0.001683 (32)
PM1 =  0.02042 (10)
PM2 =  3.53E-4 (8)
PN1 =  0.004102 (39)
PN2 =  6.26E-5 (18)
PO1 =  3.50E-4 (7)

K =  0.87140 (30)
L =  0.10332 (15)
M =  0.02077 (11)
N =  0.004164 (41)
O =  3.50E-4 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  0.1685 (38)
L1/b+ =  0.01966 (41)
L2/b+ =  3.255E-4 (43)
M1/b+ =  0.00395 (7)
M2/b+ =  6.83E-5 (12)
N1/b+ =  7.93E-4 (10)
N2/b+ =  1.211E-5 (28)
O1/b+ =  6.77E-5 (10)

K/b+ =  0.1685 (38)
L/b+ =  0.01998 (42)
M/b+ =  0.00402 (7)
N/b+ =  8.05E-4 (10)
O/b+ =  6.77E-5 (10)

EC/b+ =  0.1934 (43)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   80.00 (41) %   Iec =   12.80 (10) %   Ib+ =   67.20 (40) %
Iec      =   12.80 (10) % (input data kept)
Ib+      =   67.20 (40) % (input data kept)
Iec tot. =   80.00 (41) % (input data kept)


---------------------
Capture probabilities

PK  =  0.1412 (26)
PL1  =  0.01647 (31)
PL2  =  2.73E-4 (7)
PM1  =  0.00331 (6)
PM2  =  5.72E-5 (17)
PN1  =  6.65E-4 (14)
PN2  =  1.015E-5 (35)
PO1  =  5.67E-5 (16)

K =  0.1412 (26)
L =  0.01674 (31)
M =  0.00337 (6)
N =  6.75E-4 (14)
O =  5.67E-5 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.6

Log ft value (ec)    =  5.622 (12)
with log f           =  1.236 (8)
and log partial T1/2 =  4.386 (9)

