--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [**] 3400.83 (17) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 931 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11982 (21)
PL2/PK =  0.001923 (39)
PM1/PK =  0.02415 (13)
PM2/PK =  4.05E-4 (10)
PN1/PK =  0.004856 (49)
PN2/PK =  7.18E-5 (22)
PO1/PK =  4.14E-4 (9)

L/K =  0.12174 (25)
M/K =  0.02456 (14)
N/K =  0.00493 (5)
O/K =  4.14E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.86833 (34)
PL1 =  0.10404 (14)
PL2 =  0.001670 (33)
PM1 =  0.02097 (11)
PM2 =  3.52E-4 (8)
PN1 =  0.004217 (41)
PN2 =  6.24E-5 (19)
PO1 =  3.60E-4 (8)

K =  0.86833 (34)
L =  0.10571 (17)
M =  0.02133 (11)
N =  0.004279 (43)
O =  3.60E-4 (8)


------------------------------
Capture branch from input data

Iec =   0.360 (40) %


---------------------
Capture probabilities

PK  =  0.86833 (34)
PL1  =  0.10404 (14)
PL2  =  0.001670 (33)
PM1  =  0.02097 (11)
PM2  =  3.52E-4 (8)
PN1  =  0.004217 (41)
PN2  =  6.24E-5 (19)
PO1  =  3.60E-4 (8)

K =  0.86833 (34)
L =  0.10571 (17)
M =  0.02133 (11)
N =  0.004279 (43)
O =  3.60E-4 (8)


------------------------------------------------------------
Input log ft value (ec): 6.

Log ft value (ec)    =  6.02 (5)
with log f           =  0.080 (13)
and log partial T1/2 =  5.936 (49)

