--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [3+] 3163.29 (19) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 1169 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11892 (20)
PL2/PK =  0.001914 (39)
PM1/PK =  0.02395 (13)
PM2/PK =  4.03E-4 (10)
PN1/PK =  0.004814 (48)
PN2/PK =  7.14E-5 (21)
PO1/PK =  4.11E-4 (9)

L/K =  0.12083 (24)
M/K =  0.02435 (14)
N/K =  0.00489 (5)
O/K =  4.11E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.86920 (33)
PL1 =  0.10336 (13)
PL2 =  0.001664 (33)
PM1 =  0.02082 (10)
PM2 =  3.50E-4 (8)
PN1 =  0.004184 (40)
PN2 =  6.21E-5 (18)
PO1 =  3.57E-4 (8)

K =  0.86920 (33)
L =  0.10503 (16)
M =  0.02117 (11)
N =  0.004246 (42)
O =  3.57E-4 (8)


--------------------------
Capture-to-positron ratios

K/b+ =  5.1E3 (13)
L1/b+ =  6.1E2 (15)
L2/b+ =  9.8 (24)
M1/b+ =  123 (30)
M2/b+ =  2.1 (5)
N1/b+ =  25 (6)
N2/b+ =  0.37 (9)
O1/b+ =  2.1 (5)

K/b+ =  5.1E3 (13)
L/b+ =  6.2E2 (15)
M/b+ =  125 (30)
N/b+ =  25 (6)
O/b+ =  2.1 (5)

EC/b+ =  5.9E3 (15)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.058 (17) %   Iec =   0.058 (17) %   Ib+ =   0. %
Iec      =   0.058 (17) % (input data kept)
Ib+      =   0. % (input data kept)
Iec tot. =   0.058 (17) % (input data kept)


---------------------
Capture probabilities

PK  =  0.86906 (33)
PL1  =  0.10335 (13)
PL2  =  0.001664 (33)
PM1  =  0.02081 (10)
PM2  =  3.50E-4 (8)
PN1  =  0.004183 (40)
PN2  =  6.21E-5 (18)
PO1  =  3.57E-4 (8)

K =  0.86906 (33)
L =  0.10501 (16)
M =  0.02116 (11)
N =  0.004245 (42)
O =  3.57E-4 (8)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.

Log ft value (ec)    =  7.01 (13)
with log f           =  0.281 (11)
and log partial T1/2 =  6.73 (13)

