--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [2+] 1864.31 (5) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 2468 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11710 (18)
PL2/PK =  0.001916 (38)
PM1/PK =  0.02353 (12)
PM2/PK =  4.02E-4 (10)
PN1/PK =  0.004728 (47)
PN2/PK =  7.13E-5 (21)
PO1/PK =  4.04E-4 (9)

L/K =  0.11901 (22)
M/K =  0.02394 (13)
N/K =  0.004800 (49)
O/K =  4.04E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.87097 (31)
PL1 =  0.10199 (12)
PL2 =  0.001669 (32)
PM1 =  0.02050 (10)
PM2 =  3.50E-4 (8)
PN1 =  0.004118 (39)
PN2 =  6.21E-5 (18)
PO1 =  3.51E-4 (7)

K =  0.87097 (31)
L =  0.10366 (15)
M =  0.02085 (11)
N =  0.004180 (41)
O =  3.51E-4 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  0.858 (25)
L1/b+ =  0.1005 (28)
L2/b+ =  0.001643 (33)
M1/b+ =  0.02019 (49)
M2/b+ =  3.45E-4 (8)
N1/b+ =  0.00406 (8)
N2/b+ =  6.12E-5 (18)
O1/b+ =  3.46E-4 (8)

K/b+ =  0.858 (25)
L/b+ =  0.1021 (28)
M/b+ =  0.02053 (49)
N/b+ =  0.00412 (8)
O/b+ =  3.46E-4 (8)

EC/b+ =  0.985 (28)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.80 (13) %   Iec =   0.39 (9) %   Ib+ =   0.41 (10) %
Iec      =   0.39 (9) % (input data kept)
Ib+      =   0.41 (10) % (input data kept)
Iec tot. =   0.80 (13) % (input data kept)


---------------------
Capture probabilities

PK  =  0.432 (6)
PL1  =  0.0506 (7)
PL2  =  8.28E-4 (20)
PM1  =  0.01017 (16)
PM2  =  1.739E-4 (48)
PN1  =  0.002044 (35)
PN2  =  3.08E-5 (10)
PO1  =  1.744E-4 (45)

K =  0.432 (6)
L =  0.0514 (7)
M =  0.01034 (16)
N =  0.002074 (36)
O =  1.744E-4 (45)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.82

Log ft value (ec)    =  6.84 (10)
with log f           =  0.939 (8)
and log partial T1/2 =  5.90 (10)

