--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [2+] 3792.87 (15) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 539 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12313 (28)
PL2/PK =  0.001967 (41)
PM1/PK =  0.02491 (15)
PM2/PK =  4.16E-4 (10)
PN1/PK =  0.00501 (5)
PN2/PK =  7.38E-5 (23)
PO1/PK =  4.28E-4 (10)

L/K =  0.12510 (33)
M/K =  0.02533 (16)
N/K =  0.00509 (6)
O/K =  4.28E-4 (10)


------------------------------
Relative capture probabilities

PK  =  0.86509 (41)
PL1 =  0.10652 (19)
PL2 =  0.001702 (35)
PM1 =  0.02155 (12)
PM2 =  3.60E-4 (9)
PN1 =  0.004336 (45)
PN2 =  6.38E-5 (19)
PO1 =  3.70E-4 (8)

K =  0.86509 (41)
L =  0.10822 (23)
M =  0.02191 (13)
N =  0.004399 (47)
O =  3.70E-4 (8)


------------------------------
Capture branch from input data

Iec =   0.169 (20) %


---------------------
Capture probabilities

PK  =  0.86509 (41)
PL1  =  0.10652 (19)
PL2  =  0.001702 (35)
PM1  =  0.02155 (12)
PM2  =  3.60E-4 (9)
PN1  =  0.004336 (45)
PN2  =  6.38E-5 (19)
PO1  =  3.70E-4 (8)

K =  0.86509 (41)
L =  0.10822 (23)
M =  0.02191 (13)
N =  0.004399 (47)
O =  3.70E-4 (8)


------------------------------------------------------------
Input log ft value (ec): 5.9

Log ft value (ec)    =  5.86 (5)
with log f           =  -0.407 (17)
and log partial T1/2 =  6.26 (5)

