--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [2+] 2393.02 (6) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 1939 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11754 (18)
PL2/PK =  0.001910 (38)
PM1/PK =  0.02363 (12)
PM2/PK =  4.01E-4 (10)
PN1/PK =  0.004749 (47)
PN2/PK =  7.11E-5 (21)
PO1/PK =  4.05E-4 (9)

L/K =  0.11945 (22)
M/K =  0.02404 (13)
N/K =  0.004820 (49)
O/K =  4.05E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.87054 (31)
PL1 =  0.10232 (12)
PL2 =  0.001663 (33)
PM1 =  0.02057 (10)
PM2 =  3.49E-4 (8)
PN1 =  0.004134 (39)
PN2 =  6.19E-5 (18)
PO1 =  3.53E-4 (7)

K =  0.87054 (31)
L =  0.10398 (15)
M =  0.02092 (11)
N =  0.004196 (41)
O =  3.53E-4 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  3.85 (15)
L1/b+ =  0.452 (17)
L2/b+ =  0.00735 (23)
M1/b+ =  0.0910 (31)
M2/b+ =  0.00154 (5)
N1/b+ =  0.0183 (5)
N2/b+ =  2.74E-4 (11)
O1/b+ =  0.00156 (5)

K/b+ =  3.85 (15)
L/b+ =  0.460 (17)
M/b+ =  0.0925 (32)
N/b+ =  0.0186 (5)
O/b+ =  0.00156 (5)

EC/b+ =  4.42 (17)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   4.91 (21) %   Iec =   4.00 (20) %   Ib+ =   0.91 (6) %
Iec      =   4.00 (20) % (input data kept)
Ib+      =   0.91 (6) % (input data kept)
Iec tot. =   4.91 (21) % (input data kept)


---------------------
Capture probabilities

PK  =  0.710 (5)
PL1  =  0.0834 (6)
PL2  =  0.001356 (28)
PM1  =  0.01678 (15)
PM2  =  2.85E-4 (7)
PN1  =  0.003372 (40)
PN2  =  5.05E-5 (15)
PO1  =  2.88E-4 (6)

K =  0.710 (5)
L =  0.0848 (6)
M =  0.01706 (15)
N =  0.003422 (42)
O =  2.88E-4 (6)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.6

Log ft value (ec)    =  5.618 (25)
with log f           =  0.727 (9)
and log partial T1/2 =  4.891 (23)

