--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [1+] 3447.60 (40) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 884 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12005 (21)
PL2/PK =  0.001926 (39)
PM1/PK =  0.02421 (13)
PM2/PK =  4.06E-4 (10)
PN1/PK =  0.00487 (5)
PN2/PK =  7.19E-5 (22)
PO1/PK =  4.15E-4 (9)

L/K =  0.12198 (25)
M/K =  0.02461 (14)
N/K =  0.00494 (5)
O/K =  4.15E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.86809 (34)
PL1 =  0.10422 (14)
PL2 =  0.001672 (33)
PM1 =  0.02102 (11)
PM2 =  3.52E-4 (8)
PN1 =  0.004225 (41)
PN2 =  6.25E-5 (19)
PO1 =  3.61E-4 (8)

K =  0.86809 (34)
L =  0.10589 (18)
M =  0.02137 (11)
N =  0.004288 (43)
O =  3.61E-4 (8)


------------------------------
Capture branch from input data

Iec =   0.118 (19) %


---------------------
Capture probabilities

PK  =  0.86809 (34)
PL1  =  0.10422 (14)
PL2  =  0.001672 (33)
PM1  =  0.02102 (11)
PM2  =  3.52E-4 (8)
PN1  =  0.004225 (41)
PN2  =  6.25E-5 (19)
PO1  =  3.61E-4 (8)

K =  0.86809 (34)
L =  0.10589 (18)
M =  0.02137 (11)
N =  0.004288 (43)
O =  3.61E-4 (8)


------------------------------------------------------------
Input log ft value (ec): 6.4

Log ft value (ec)    =  6.46 (7)
with log f           =  0.035 (13)
and log partial T1/2 =  6.42 (7)

