--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 43-Tc-94m [2+] 76.0 (30) keV  -->  Daughter nucleus: 42-Mo-94 [2+] 3534.32 (9) keV
Calculation of the allowed transition from the electron capture decay of Tc-94

Transition energy: 798 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12057 (22)
PL2/PK =  0.001932 (40)
PM1/PK =  0.02433 (13)
PM2/PK =  4.07E-4 (10)
PN1/PK =  0.00489 (5)
PN2/PK =  7.22E-5 (22)
PO1/PK =  4.17E-4 (9)

L/K =  0.12250 (26)
M/K =  0.02473 (14)
N/K =  0.00496 (5)
O/K =  4.17E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.86759 (35)
PL1 =  0.10460 (15)
PL2 =  0.001676 (34)
PM1 =  0.02111 (11)
PM2 =  3.53E-4 (8)
PN1 =  0.004244 (42)
PN2 =  6.27E-5 (19)
PO1 =  3.62E-4 (8)

K =  0.86759 (35)
L =  0.10628 (18)
M =  0.02146 (12)
N =  0.004306 (44)
O =  3.62E-4 (8)


------------------------------
Capture branch from input data

Iec =   0.1060 (30) %


---------------------
Capture probabilities

PK  =  0.86759 (35)
PL1  =  0.10460 (15)
PL2  =  0.001676 (34)
PM1  =  0.02111 (11)
PM2  =  3.53E-4 (8)
PN1  =  0.004244 (42)
PN2  =  6.27E-5 (19)
PO1  =  3.62E-4 (8)

K =  0.86759 (35)
L =  0.10628 (18)
M =  0.02146 (12)
N =  0.004306 (44)
O =  3.62E-4 (8)


------------------------------------------------------------
Input log ft value (ec): 6.4

Log ft value (ec)    =  6.411 (20)
with log f           =  -0.057 (14)
and log partial T1/2 =  6.467 (15)

