--------------------------------------------------------------------------------------

BetaShape
Version: 2.3.1 (12/2023)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 17-Cl-36 [2+] g.s.  -->  Daughter nucleus: 16-S-36 [0+] g.s.
The 2nd forbidden non-unique transition from the electron capture decay of Cl-36 is calculated as 1st forbidden unique

Transition energy: 1142.14 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.09076 (47)
PL2/PK =  1.435E-4 (7)
PL3/PK =  1.002E-4 (6)
PM1/PK =  0.01318 (18)
PM2/PK =  1.441E-5 (22)
PM3/PK =  5.69E-6 (11)

L/K =  0.09100 (47)
M/K =  0.01320 (19)


------------------------------
Relative capture probabilities

PK  =  0.9056 (5)
PL1 =  0.08219 (38)
PL2 =  1.300E-4 (5)
PL3 =  9.07E-5 (5)
PM1 =  0.01194 (16)
PM2 =  1.305E-5 (19)
PM3 =  5.15E-6 (10)

K =  0.9056 (5)
L =  0.08241 (38)
M =  0.01195 (16)


--------------------------
Capture-to-positron ratios

K/b+ =  2.51E3 (5)
L1/b+ =  228.2 (36)
L2/b+ =  0.361 (6)
L3/b+ =  0.2519 (39)
M1/b+ =  33.14 (25)
M2/b+ =  0.03623 (32)
M3/b+ =  0.0143 (2)

K/b+ =  2.51E3 (5)
L/b+ =  228.8 (37)
M/b+ =  33.19 (25)

EC/b+ =  2.78E3 (6)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.90 (14) %   Iec =   1.90 (14) %   Ib+ =   0.00157 (31) %
Iec      =   1.90 (14) %
Ib+      =   6.8E-4 (5) %
Iec tot. =   1.90 (14) %


---------------------
Capture probabilities

PK  =  0.9053 (5)
PL1  =  0.08216 (38)
PL2  =  1.299E-4 (5)
PL3  =  9.07E-5 (5)
PM1  =  0.01193 (16)
PM2  =  1.304E-5 (19)
PM3  =  5.15E-6 (10)

K =  0.9053 (5)
L =  0.08239 (38)
M =  0.01195 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 13.5

Log ft value (ec)    =  14.231 (33)
with log f           =  -0.469 (6)
or f-value           =  0.3393 (46)
and log partial T1/2 =  14.700 (33)

