--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 4-Be-7 [3/2-] g.s.  -->  Daughter nucleus: 3-Li-7 [3/2-] g.s.
Calculation of the allowed transition from the electron capture decay of Be-7

Transition energy: 861.815 (18) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.105 (8)

L/K =  0.105 (8)


------------------------------
Relative capture probabilities

PK  =  0.905 (7)
PL1 =  0.095 (7)

K =  0.905 (7)
L =  0.095 (7)


------------------------------
Capture branch from input data

Iec =   89.560 (40) %


---------------------
Capture probabilities

PK  =  0.905 (7)
PL1  =  0.095 (7)

K =  0.905 (7)
L =  0.095 (7)


------------------------------------------------------------
Input log ft value (ec): 3.32

Log ft value (ec)    =  3.25 (6)
with log f           =  -3.46 (6)
and log partial T1/2 =  6.7105 (5)

