--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 21-Sc-44 [2+] g.s.  -->  Daughter nucleus: 20-Ca-44 [2+] 3301.46 (6) keV
Calculation of the allowed transition from the electron capture decay of Sc-44

Transition energy: 351.8 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.09738 (42)
PL2/PK =  2.825E-4 (33)
PM1/PK =  0.01489 (20)
PM2/PK =  3.82E-5 (9)
PN1/PK =  0.001454 (27)

L/K =  0.09766 (43)
M/K =  0.01493 (20)
N/K =  0.001454 (27)


------------------------------
Relative capture probabilities

PK  =  0.8976 (5)
PL1 =  0.08741 (33)
PL2 =  2.536E-4 (28)
PM1 =  0.01336 (17)
PM2 =  3.43E-5 (7)
PN1 =  0.001305 (24)

K =  0.8976 (5)
L =  0.08766 (33)
M =  0.01340 (17)
N =  0.001305 (24)


------------------------------
Capture branch from input data

Iec =   0.00440 (11) %


---------------------
Capture probabilities

PK  =  0.8976 (5)
PL1  =  0.08741 (33)
PL2  =  2.536E-4 (28)
PM1  =  0.01336 (17)
PM2  =  3.43E-5 (7)
PN1  =  0.001305 (24)

K =  0.8976 (5)
L =  0.08766 (33)
M =  0.01340 (17)
N =  0.001305 (24)


------------------------------------------------------------
Input log ft value (ec): 6.6

Log ft value (ec)    =  6.624 (16)
with log f           =  -1.887 (12)
and log partial T1/2 =  8.512 (12)

