--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 21-Sc-44 [2+] g.s.  -->  Daughter nucleus: 20-Ca-44 [2+] 1157.039 (15) keV
Calculation of the allowed transition from the electron capture decay of Sc-44

Transition energy: 2496.3 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.09571 (40)
PL2/PK =  2.887E-4 (32)
PM1/PK =  0.01461 (19)
PM2/PK =  3.90E-5 (8)
PN1/PK =  0.001426 (26)

L/K =  0.09600 (41)
M/K =  0.01465 (19)
N/K =  0.001426 (26)


------------------------------
Relative capture probabilities

PK  =  0.8992 (5)
PL1 =  0.08606 (32)
PL2 =  2.596E-4 (28)
PM1 =  0.01313 (16)
PM2 =  3.51E-5 (7)
PN1 =  0.001282 (23)

K =  0.8992 (5)
L =  0.08632 (32)
M =  0.01317 (17)
N =  0.001282 (23)


--------------------------
Capture-to-positron ratios

K/b+ =  0.0447 (9)
L1/b+ =  0.00428 (7)
L2/b+ =  1.291E-5 (11)
M1/b+ =  6.535E-4 (46)
M2/b+ =  1.745E-6 (16)
N1/b+ =  6.379E-5 (40)

K/b+ =  0.0447 (9)
L/b+ =  0.00429 (7)
M/b+ =  6.552E-4 (46)
N/b+ =  6.379E-5 (40)

EC/b+ =  0.0498 (10)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   98.97 (7) %   Iec =   4.70 (5) %   Ib+ =   94.27 (5) %
Iec      =   4.70 (5) % (input data kept)
Ib+      =   94.27 (5) % (input data kept)
Iec tot. =   98.97 (7) % (input data kept)


---------------------
Capture probabilities

PK  =  0.0426 (8)
PL1  =  0.00408 (8)
PL2  =  1.230E-5 (26)
PM1  =  6.23E-4 (14)
PM2  =  1.663E-6 (46)
PN1  =  6.08E-5 (16)

K =  0.0426 (8)
L =  0.00409 (8)
M =  6.24E-4 (14)
N =  6.08E-5 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.3

Log ft value (ec)    =  5.307 (10)
with log f           =  -0.176 (7)
and log partial T1/2 =  5.483 (6)

