--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 21-Sc-44 [2+] g.s.  -->  Daughter nucleus: 20-Ca-44 [2+] 2656.530 (24) keV
Calculation of the allowed transition from the electron capture decay of Sc-44

Transition energy: 996.8 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.09612 (41)
PL2/PK =  2.822E-4 (33)
PM1/PK =  0.01468 (19)
PM2/PK =  3.82E-5 (8)
PN1/PK =  0.001433 (27)

L/K =  0.09640 (41)
M/K =  0.01471 (19)
N/K =  0.001433 (27)


------------------------------
Relative capture probabilities

PK  =  0.8988 (5)
PL1 =  0.08639 (32)
PL2 =  2.536E-4 (28)
PM1 =  0.01319 (17)
PM2 =  3.43E-5 (7)
PN1 =  0.001288 (23)

K =  0.8988 (5)
L =  0.08665 (32)
M =  0.01323 (17)
N =  0.001288 (23)


------------------------------
Capture branch from input data

Iec =   1.020 (20) %


---------------------
Capture probabilities

PK  =  0.8988 (5)
PL1  =  0.08639 (32)
PL2  =  2.536E-4 (28)
PM1  =  0.01319 (17)
PM2  =  3.43E-5 (7)
PN1  =  0.001288 (23)

K =  0.8988 (5)
L =  0.08665 (32)
M =  0.01323 (17)
N =  0.001288 (23)


------------------------------------------------------------
Input log ft value (ec): 5.2

Log ft value (ec)    =  5.170 (13)
with log f           =  -0.977 (8)
and log partial T1/2 =  6.146 (10)

