--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 9-F-18 [1+] g.s.  -->  Daughter nucleus: 8-O-18 [0+] g.s.
Calculation of the allowed transition from the electron capture decay of F-18

Transition energy: 1655.9 (5) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.07462 (33)
PL2/PK =  1.617E-5 (19)

L/K =  0.07464 (33)


------------------------------
Relative capture probabilities

PK  =  0.93054 (28)
PL1 =  0.06944 (28)
PL2 =  1.504E-5 (17)

K =  0.93054 (28)
L =  0.06946 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  0.03147 (49)
L1/b+ =  0.002348 (26)
L2/b+ =  5.086E-7 (21)

K/b+ =  0.03147 (49)
L/b+ =  0.002349 (26)

EC/b+ =  0.0338 (5)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   100.00 (27) %   Iec =   3.14 (19) %   Ib+ =   96.86 (19) %
Iec      =   3.14 (19) % (input data kept)
Ib+      =   96.86 (19) % (input data kept)
Iec tot. =   100. % (input data kept)


---------------------
Capture probabilities

PK  =  0.03044 (45)
PL1  =  0.002272 (35)
PL2  =  4.92E-7 (9)

K =  0.03044 (45)
L =  0.002272 (35)


------------------------------------------------------------
Input log ft value (ec & beta +): 3.57

Log ft value (ec)    =  3.588 (27)
with log f           =  -1.733 (6)
and log partial T1/2 =  5.322 (26)

