--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 49-In-111 [9/2+] g.s.  -->  Daughter nucleus: 48-Cd-111 [11/2-] 396.15 keV
The 1st forbidden non-unique transition from the electron capture decay of In-111 is calculated as allowed

Transition energy: 465.6 (46) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13270 (30)
PL2/PK =  0.00288 (10)
PM1/PK =  0.02829 (15)
PM2/PK =  6.53E-4 (24)
PN1/PK =  0.00633 (6)
PN2/PK =  1.35E-4 (6)
PO1/PK =  0.001011 (28)

L/K =  0.13559 (40)
M/K =  0.02894 (18)
N/K =  0.00647 (6)
O/K =  0.001011 (28)


------------------------------
Relative capture probabilities

PK  =  0.85323 (49)
PL1 =  0.11323 (19)
PL2 =  0.00246 (8)
PM1 =  0.02414 (12)
PM2 =  5.57E-4 (20)
PN1 =  0.005404 (47)
PN2 =  1.149E-4 (47)
PO1 =  8.62E-4 (23)

K =  0.85323 (49)
L =  0.11569 (28)
M =  0.02470 (14)
N =  0.00552 (5)
O =  8.62E-4 (23)


------------------------------
Capture branch from input data

Iec =   0.005 (5) %


---------------------
Capture probabilities

PK  =  0.85323 (49)
PL1  =  0.11323 (19)
PL2  =  0.00246 (8)
PM1  =  0.02414 (12)
PM2  =  5.57E-4 (20)
PN1  =  0.005404 (47)
PN2  =  1.149E-4 (47)
PO1  =  8.62E-4 (23)

K =  0.85323 (49)
L =  0.11569 (28)
M =  0.02470 (14)
N =  0.00552 (5)
O =  8.62E-4 (23)


------------------------------------------------------------
Input log ft value (ec): 9.

Log ft value (ec)    =  9.38 (43)
with log f           =  -0.303 (22)
and log partial T1/2 =  9.69 (43)

