--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 47-Ag-110 [1+] g.s.  -->  Daughter nucleus: 46-Pd-110 [**] g.s.
Calculation of the allowed transition from the electron capture decay of Ag-110

Transition energy: 892 (11) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12405 (23)
PL2/PK =  0.0024541 (49)
PM1/PK =  0.02607 (13)
PM2/PK =  5.424E-4 (28)
PN1/PK =  0.00568 (5)
PN2/PK =  1.058E-4 (10)

L/K =  0.12650 (23)
M/K =  0.02661 (13)
N/K =  0.00579 (5)


------------------------------
Relative capture probabilities

PK  =  0.86288 (31)
PL1 =  0.10704 (16)
PL2 =  0.0021176 (35)
PM1 =  0.02249 (10)
PM2 =  4.681E-4 (23)
PN1 =  0.004905 (41)
PN2 =  9.13E-5 (8)

K =  0.86288 (31)
L =  0.10916 (16)
M =  0.02296 (11)
N =  0.004996 (42)


------------------------------
Capture branch from input data

Iec =   0.30 (6) %


---------------------
Capture probabilities

PK  =  0.86288 (31)
PL1  =  0.10704 (16)
PL2  =  0.0021176 (35)
PM1  =  0.02249 (10)
PM2  =  4.681E-4 (23)
PN1  =  0.004905 (41)
PN2  =  9.13E-5 (8)

K =  0.86288 (31)
L =  0.10916 (16)
M =  0.02296 (11)
N =  0.004996 (42)


------------------------------------------------------------
Input log ft value (ec): 4.1

Log ft value (ec)    =  4.12 (9)
with log f           =  0.205 (12)
and log partial T1/2 =  3.91 (9)

