--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-58 [2+] g.s.  -->  Daughter nucleus: 26-Fe-58 [2+] 1674.731 (6) keV
Calculation of the allowed transition from the electron capture decay of Co-58

Transition energy: 633.2 (11) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11315 (28)
PL2/PK =  6.132E-4 (30)
PM1/PK =  0.01781 (11)
PM2/PK =  9.17E-5 (8)
PN1/PK =  0.001160 (8)

L/K =  0.11376 (28)
M/K =  0.01790 (11)
N/K =  0.001160 (8)


------------------------------
Relative capture probabilities

PK  =  0.88275 (31)
PL1 =  0.09988 (21)
PL2 =  5.413E-4 (25)
PM1 =  0.01572 (9)
PM2 =  8.09E-5 (7)
PN1 =  0.001024 (7)

K =  0.88275 (31)
L =  0.10042 (21)
M =  0.01580 (9)
N =  0.001024 (7)


------------------------------
Capture branch from input data

Iec =   1.228 (35) %


---------------------
Capture probabilities

PK  =  0.88275 (31)
PL1  =  0.09988 (21)
PL2  =  5.413E-4 (25)
PM1  =  0.01572 (9)
PM2  =  8.09E-5 (7)
PN1  =  0.001024 (7)

K =  0.88275 (31)
L =  0.10042 (21)
M =  0.01580 (9)
N =  0.001024 (7)


------------------------------------------------------------
Input log ft value (ec): 7.7

Log ft value (ec)    =  7.693 (13)
with log f           =  -1.0051 (39)
and log partial T1/2 =  8.698 (12)

