--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 27-Co-58 [2+] g.s.  -->  Daughter nucleus: 26-Fe-58 [2+] 810.7662 (20) keV
Calculation of the allowed transition from the electron capture decay of Co-58

Transition energy: 1497.1 (11) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11188 (27)
PL2/PK =  6.141E-4 (30)
PM1/PK =  0.01759 (10)
PM2/PK =  9.17E-5 (8)
PN1/PK =  0.001145 (8)

L/K =  0.11249 (27)
M/K =  0.01768 (10)
N/K =  0.001145 (8)


------------------------------
Relative capture probabilities

PK  =  0.88393 (30)
PL1 =  0.09889 (20)
PL2 =  5.428E-4 (25)
PM1 =  0.01554 (9)
PM2 =  8.10E-5 (7)
PN1 =  0.001013 (7)

K =  0.88393 (30)
L =  0.09944 (21)
M =  0.01562 (9)
N =  0.001013 (7)


--------------------------
Capture-to-positron ratios

K/b+ =  4.98 (7)
L1/b+ =  0.557 (6)
L2/b+ =  0.003060 (28)
M1/b+ =  0.0876 (7)
M2/b+ =  4.57E-4 (5)
N1/b+ =  0.00571 (5)

K/b+ =  4.98 (7)
L/b+ =  0.561 (6)
M/b+ =  0.0881 (7)
N/b+ =  0.00571 (5)

EC/b+ =  5.64 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   98.77 (23) %   Iec =   83.83 (16) %   Ib+ =   14.94 (16) %
Iec      =   83.83 (16) % (input data kept)
Ib+      =   14.94 (16) % (input data kept)
Iec tot. =   98.77 (23) % (input data kept)


---------------------
Capture probabilities

PK  =  0.7508 (16)
PL1  =  0.08399 (24)
PL2  =  4.610E-4 (23)
PM1  =  0.01320 (8)
PM2  =  6.88E-5 (6)
PN1  =  8.60E-4 (6)

K =  0.7508 (16)
L =  0.08445 (25)
M =  0.01327 (8)
N =  8.60E-4 (6)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.6

Log ft value (ec)    =  6.6114 (31)
with log f           =  -0.2520 (30)
and log partial T1/2 =  6.8635 (8)

