--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 70-Yb-169 [7/2+] g.s.  -->  Daughter nucleus: 69-Tm-169 [9/2+] 832.41 keV
Calculation of the allowed transition from the electron capture decay of Yb-169

Transition energy: 76.6 (40) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  2.0 (9)
PL2/PK =  0.101 (48)
PM1/PK =  0.59 (30)
PM2/PK =  0.033 (17)
PN1/PK =  0.16 (8)
PN2/PK =  0.0090 (46)
PO1/PK =  0.027 (14)
PO2/PK =  0.0011 (6)
PP1/PK =  0.0022 (11)

L/K =  2.1 (10)
M/K =  0.63 (31)
N/K =  0.17 (9)
O/K =  0.028 (14)
P/K =  0.0022 (11)


------------------------------
Relative capture probabilities

PK  =  0.26 (7)
PL1 =  0.507 (44)
PL2 =  0.0259 (22)
PM1 =  0.152 (15)
PM2 =  0.0085 (9)
PN1 =  0.0416 (45)
PN2 =  0.00230 (25)
PO1 =  0.0068 (8)
PO2 =  2.84E-4 (32)
PP1 =  5.7E-4 (6)

K =  0.26 (7)
L =  0.533 (46)
M =  0.160 (16)
N =  0.0439 (48)
O =  0.0071 (8)
P =  5.7E-4 (6)


------------------------------
Capture branch from input data

Iec =   1.75E-5 (5) %


---------------------
Capture probabilities

PK  =  0.26 (7)
PL1  =  0.507 (44)
PL2  =  0.0259 (22)
PM1  =  0.152 (15)
PM2  =  0.0085 (9)
PN1  =  0.0416 (45)
PN2  =  0.00230 (25)
PO1  =  0.0068 (8)
PO2  =  2.84E-4 (32)
PP1  =  5.7E-4 (6)

K =  0.26 (7)
L =  0.533 (46)
M =  0.160 (16)
N =  0.0439 (48)
O =  0.0071 (8)
P =  5.7E-4 (6)


------------------------------------------------------------
Input log ft value (ec): 11.2

Log ft value (ec)    =  11.39 (10)
with log f           =  -1.81 (9)
and log partial T1/2 =  13.199 (12)

