--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 83-Bi-207 [9/2-] g.s.  -->  Daughter nucleus: 82-Pb-207 [5/2-] 569.7030 (20) keV
The 2nd forbidden non-unique transition from the electron capture decay of Bi-207 is calculated as 1st forbidden unique

Transition energy: 1827.8 (21) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.18682 (19)
PL2/PK =  0.01528 (18)
PL3/PK =  0.001263 (14)
PM1/PK =  0.04488 (13)
PM2/PK =  0.004011 (40)
PM3/PK =  3.339E-4 (44)
PN1/PK =  0.01281 (8)
PM4/PK =  2.603E-6 (29)
PN2/PK =  0.001128 (8)
PN3/PK =  8.97E-5 (15)
PO1/PK =  0.003198 (32)
PN4/PK =  7.60E-7 (11)
PO2/PK =  2.576E-4 (7)
PO3/PK =  1.801E-5 (38)
PP1/PK =  4.24E-4 (7)
PO4/PK =  9.72E-8 (20)
PP2/PK =  1.865E-5 (18)
PP3/PK =  1.571E-7 (36)

L/K =  0.20336 (6)
M/K =  0.04922 (10)
N/K =  0.01403 (7)
O/K =  0.003474 (32)
P/K =  4.43E-4 (7)


------------------------------
Relative capture probabilities

PK  =  0.78708 (15)
PL1 =  0.14704 (12)
PL2 =  0.01202 (14)
PL3 =  9.94E-4 (11)
PM1 =  0.03532 (10)
PM2 =  0.003157 (31)
PM3 =  2.628E-4 (34)
PN1 =  0.01008 (6)
PM4 =  2.049E-6 (22)
PN2 =  8.88E-4 (6)
PN3 =  7.06E-5 (11)
PO1 =  0.002517 (25)
PN4 =  5.98E-7 (9)
PO2 =  2.027E-4 (6)
PO3 =  1.417E-5 (30)
PP1 =  3.34E-4 (5)
PO4 =  7.65E-8 (16)
PP2 =  1.468E-5 (14)
PP3 =  1.236E-7 (28)

K =  0.78708 (15)
L =  0.16006 (6)
M =  0.03874 (7)
N =  0.01104 (5)
O =  0.002734 (25)
P =  3.49E-4 (5)


--------------------------
Capture-to-positron ratios

K/b+ =  1073 (27)
L1/b+ =  200 (5)
L2/b+ =  16.4 (6)
L3/b+ =  1.354 (26)
M1/b+ =  48.1 (11)
M2/b+ =  4.30 (15)
M3/b+ =  0.358 (6)
N1/b+ =  13.74 (28)
M4/b+ =  0.00279 (5)
N2/b+ =  1.210 (39)
N3/b+ =  0.0962 (14)
O1/b+ =  3.43 (6)
N4/b+ =  8.15E-4 (13)
O2/b+ =  0.276 (8)
O3/b+ =  0.01932 (34)
P1/b+ =  0.455 (6)
O4/b+ =  1.042E-4 (18)
P2/b+ =  0.02001 (33)
P3/b+ =  1.685E-4 (33)

K/b+ =  1073 (27)
L/b+ =  218 (6)
M/b+ =  52.8 (13)
N/b+ =  15.05 (32)
O/b+ =  3.73 (6)
P/b+ =  0.475 (6)

EC/b+ =  1363 (35)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   8.8 (6) %   Iec =   8.8 (6) %   Ib+ =   0.0120 (20) %
Iec      =   8.8 (6) % (input data kept)
Ib+      =   0.0120 (20) % (input data kept)
Iec tot. =   8.8 (6) % (input data kept)


---------------------
Capture probabilities

PK  =  0.78650 (15)
PL1  =  0.14693 (12)
PL2  =  0.01201 (14)
PL3  =  9.93E-4 (11)
PM1  =  0.03530 (10)
PM2  =  0.003154 (31)
PM3  =  2.626E-4 (34)
PN1  =  0.01007 (6)
PM4  =  2.047E-6 (22)
PN2  =  8.87E-4 (6)
PN3  =  7.05E-5 (11)
PO1  =  0.002515 (25)
PN4  =  5.98E-7 (9)
PO2  =  2.026E-4 (6)
PO3  =  1.416E-5 (30)
PP1  =  3.34E-4 (5)
PO4  =  7.64E-8 (16)
PP2  =  1.467E-5 (14)
PP3  =  1.236E-7 (28)

K =  0.78650 (15)
L =  0.15994 (6)
M =  0.03871 (7)
N =  0.01103 (5)
O =  0.002732 (25)
P =  3.48E-4 (5)


------------------------------------------------------------
Input log ft value (ec & beta +): 12.1

Log ft value (ec)    =  13.274 (36)
with log f           =  3.202 (8)
and log partial T1/2 =  10.072 (35)

