--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 54-Xe-127 [1/2+] g.s.  -->  Daughter nucleus: 53-I-127 [3/2+] 618.40 (30) keV
Calculation of the allowed transition from the electron capture decay of Xe-127

Transition energy: 43.9 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  1.5 (5)
PL2/PK =  0.043 (15)
PM1/PK =  0.37 (13)
PM2/PK =  0.0109 (39)
PN1/PK =  0.096 (36)
PN2/PK =  0.0027 (10)
PO1/PK =  0.017 (7)
PO2/PK =  3.1E-4 (12)

L/K =  1.6 (5)
M/K =  0.38 (14)
N/K =  0.099 (37)
O/K =  0.018 (7)


------------------------------
Relative capture probabilities

PK  =  0.33 (6)
PL1 =  0.497 (44)
PL2 =  0.0141 (13)
PM1 =  0.121 (12)
PM2 =  0.00356 (36)
PN1 =  0.0313 (34)
PN2 =  8.7E-4 (9)
PO1 =  0.0057 (7)
PO2 =  1.02E-4 (12)

K =  0.33 (6)
L =  0.511 (45)
M =  0.125 (13)
N =  0.0322 (35)
O =  0.0058 (7)


------------------------------
Capture branch from input data

Iec =   0.0142 (9) %


---------------------
Capture probabilities

PK  =  0.33 (6)
PL1  =  0.497 (44)
PL2  =  0.0141 (13)
PM1  =  0.121 (12)
PM2  =  0.00356 (36)
PN1  =  0.0313 (34)
PN2  =  8.7E-4 (9)
PO1  =  0.0057 (7)
PO2  =  1.02E-4 (12)

K =  0.33 (6)
L =  0.511 (45)
M =  0.125 (13)
N =  0.0322 (35)
O =  0.0058 (7)


------------------------------------------------------------
Input log ft value (ec): 7.42

Log ft value (ec)    =  7.46 (9)
with log f           =  -2.88 (9)
and log partial T1/2 =  10.345 (28)

