--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 13-Al-26 [5+] g.s.  -->  Daughter nucleus: 12-Mg-26 [2+] 1808.740 (40) keV
Calculation of the 2nd forbidden unique transition from the electron capture decay of Al-26

Transition energy: 2195.66 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.07808 (47)
PL2/PK =  5.70E-5 (47)
PL3/PK =  3.91E-5 (34)
PM1/PK =  0.00953 (40)

L/K =  0.07818 (48)
M/K =  0.00953 (40)


------------------------------
Relative capture probabilities

PK  =  0.9194 (7)
PL1 =  0.07179 (38)
PL2 =  5.24E-5 (43)
PL3 =  3.60E-5 (31)
PM1 =  0.00876 (36)

K =  0.9194 (7)
L =  0.07187 (39)
M =  0.00876 (36)


--------------------------
Capture-to-positron ratios

K/b+ =  0.171 (11)
L1/b+ =  0.0133 (8)
L2/b+ =  9.73E-6 (9)
L3/b+ =  6.67E-6 (8)
M1/b+ =  0.001627 (44)

K/b+ =  0.171 (11)
L/b+ =  0.0133 (8)
M/b+ =  0.001627 (44)

EC/b+ =  0.186 (12)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   97.24 (25) %   Iec =   15.23 (18) %   Ib+ =   82.01 (18) %
Iec      =   15.23 (18) %
Ib+      =   82.01 (18) %
Iec tot. =   97.24 (25) %


---------------------
Capture probabilities

PK  =  0.144 (8)
PL1  =  0.0112 (6)
PL2  =  8.2E-6 (8)
PL3  =  5.6E-6 (6)
PM1  =  0.00137 (9)

K =  0.144 (8)
L =  0.0113 (6)
M =  0.00137 (9)


------------------------------------------------------------
Input log ft value (ec & beta +): 15.726

Log ft value (ec)    =  15.718 (33)
with log f           =  1.547 (29)
and log partial T1/2 =  14.171 (16)

