--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 26-Fe-55 [3/2-] g.s.  -->  Daughter nucleus: 25-Mn-55 [5/2-] g.s.
Calculation of the allowed transition from the electron capture decay of Fe-55

Transition energy: 231.21 (18) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11572 (31)
PL2/PK =  5.693E-4 (31)
PM1/PK =  0.01816 (12)
PM2/PK =  8.44E-5 (9)
PN1/PK =  0.001272 (10)

L/K =  0.11628 (31)
M/K =  0.01824 (12)
N/K =  0.001272 (10)


------------------------------
Relative capture probabilities

PK  =  0.88044 (34)
PL1 =  0.10188 (23)
PL2 =  5.012E-4 (26)
PM1 =  0.01599 (10)
PM2 =  7.43E-5 (7)
PN1 =  0.001120 (8)

K =  0.88044 (34)
L =  0.10238 (23)
M =  0.01606 (10)
N =  0.001120 (8)


------------------------------
Capture branch from input data

Iec =   100. %


---------------------
Capture probabilities

PK  =  0.88044 (34)
PL1  =  0.10188 (23)
PL2  =  5.012E-4 (26)
PM1  =  0.01599 (10)
PM2  =  7.43E-5 (7)
PN1  =  0.001120 (8)

K =  0.88044 (34)
L =  0.10238 (23)
M =  0.01606 (10)
N =  0.001120 (8)


------------------------------------------------------------
Input log ft value (ec): 6.

Log ft value (ec)    =  5.9869 (35)
with log f           =  -1.9511 (33)
and log partial T1/2 =  7.9380 (13)

