--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 26-Fe-55 [3/2-] g.s.  -->  Daughter nucleus: 25-Mn-55 [7/2-] 125.949 (10) keV
The 2nd forbidden non-unique transition from the electron capture decay of Fe-55 is calculated as 1st forbidden unique

Transition energy: 105.26 (18) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13755 (41)
PL2/PK =  6.766E-4 (40)
PL3/PK =  0.0536 (5)
PM1/PK =  0.02200 (16)
PM2/PK =  1.020E-4 (11)
PM3/PK =  0.00713 (11)
PN1/PK =  0.001545 (13)
PM4/PK =  9.17E-7 (15)

L/K =  0.1918 (9)
M/K =  0.02924 (27)
N/K =  0.001545 (13)


------------------------------
Relative capture probabilities

PK  =  0.8180 (8)
PL1 =  0.11251 (23)
PL2 =  5.534E-4 (27)
PL3 =  0.04381 (39)
PM1 =  0.01800 (11)
PM2 =  8.34E-5 (8)
PM3 =  0.00583 (8)
PN1 =  0.001264 (9)
PM4 =  7.50E-7 (12)

K =  0.8180 (8)
L =  0.1569 (6)
M =  0.02391 (19)
N =  0.001264 (9)


------------------------------
Capture branch from input data

Iec =   1.30E-7 (10) %


---------------------
Capture probabilities

PK  =  0.8180 (8)
PL1  =  0.11251 (23)
PL2  =  5.534E-4 (27)
PL3  =  0.04381 (39)
PM1  =  0.01800 (11)
PM2  =  8.34E-5 (8)
PM3  =  0.00583 (8)
PN1  =  0.001264 (9)
PM4  =  7.50E-7 (12)

K =  0.8180 (8)
L =  0.1569 (6)
M =  0.02391 (19)
N =  0.001264 (9)


------------------------------------------------------------
Input log ft value (ec): 14.2

Log ft value (ec)    =  12.765 (34)
with log f           =  -4.059 (5)
and log partial T1/2 =  16.824 (33)

