--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52 [6+] g.s.  -->  Daughter nucleus: 24-Cr-52 [4+] 3415.330 (30) keV
The 2nd forbidden non-unique transition from the electron capture decay of Mn-52 is calculated as 1st forbidden unique

Transition energy: 1296.7 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11133 (29)
PL2/PK =  5.03E-4 (14)
PL3/PK =  2.62E-4 (8)
PM1/PK =  0.01733 (10)
PM2/PK =  7.34E-5 (24)
PM3/PK =  3.39E-5 (13)
PN1/PK =  0.001323 (26)
PM4/PK =  3.641E-9 (38)

L/K =  0.11210 (31)
M/K =  0.01744 (11)
N/K =  0.001323 (26)


------------------------------
Relative capture probabilities

PK  =  0.88429 (35)
PL1 =  0.09845 (22)
PL2 =  4.45E-4 (12)
PL3 =  2.32E-4 (7)
PM1 =  0.01532 (8)
PM2 =  6.49E-5 (21)
PM3 =  2.99E-5 (11)
PN1 =  0.001169 (22)
PM4 =  3.220E-9 (33)

K =  0.88429 (35)
L =  0.09913 (24)
M =  0.01542 (9)
N =  0.001169 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  250 (9)
L1/b+ =  27.8 (11)
L2/b+ =  0.126 (8)
L3/b+ =  0.0654 (47)
M1/b+ =  4.33 (19)
M2/b+ =  0.0183 (13)
M3/b+ =  0.0085 (6)
N1/b+ =  0.330 (19)
M4/b+ =  9.09E-7 (44)

K/b+ =  250 (9)
L/b+ =  28.0 (11)
M/b+ =  4.35 (19)
N/b+ =  0.330 (19)

EC/b+ =  282 (11)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.025 (38) %   Iec =   0.025 (38) %   Ib+ =   0.9E-4 (13) %
Iec      =   0.025 (38) % (input data kept)
Ib+      =   0.9E-4 (13) % (input data kept)
Iec tot. =   0.025 (38) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88116 (37)
PL1  =  0.09810 (22)
PL2  =  4.44E-4 (12)
PL3  =  2.31E-4 (7)
PM1  =  0.01527 (8)
PM2  =  6.47E-5 (21)
PM3  =  2.98E-5 (11)
PN1  =  0.001165 (22)
PM4  =  3.208E-9 (32)

K =  0.88116 (37)
L =  0.09878 (24)
M =  0.01536 (9)
N =  0.001165 (22)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.6

Log ft value (ec)    =  9.6 (7)
with log f           =  0.2807 (48)
and log partial T1/2 =  9.3 (7)

