--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52 [6+] g.s.  -->  Daughter nucleus: 24-Cr-52 [5+] 4015.520 (40) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 696.5 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11121 (29)
PL2/PK =  5.02E-4 (14)
PM1/PK =  0.01731 (10)
PM2/PK =  7.32E-5 (24)
PN1/PK =  0.001321 (26)

L/K =  0.11171 (31)
M/K =  0.01738 (10)
N/K =  0.001321 (26)


------------------------------
Relative capture probabilities

PK  =  0.88463 (34)
PL1 =  0.09838 (22)
PL2 =  4.44E-4 (12)
PM1 =  0.01531 (8)
PM2 =  6.47E-5 (21)
PN1 =  0.001169 (22)

K =  0.88463 (34)
L =  0.09883 (23)
M =  0.01538 (9)
N =  0.001169 (22)


------------------------------
Capture branch from input data

Iec =   1.07 (5) %


---------------------
Capture probabilities

PK  =  0.88463 (34)
PL1  =  0.09838 (22)
PL2  =  4.44E-4 (12)
PM1  =  0.01531 (8)
PM2  =  6.47E-5 (21)
PN1  =  0.001169 (22)

K =  0.88463 (34)
L =  0.09883 (23)
M =  0.01538 (9)
N =  0.001169 (22)


------------------------------------------------------------
Input log ft value (ec): 6.587

Log ft value (ec)    =  6.587 (21)
with log f           =  -1.0680 (46)
and log partial T1/2 =  7.655 (20)

