--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52 [6+] g.s.  -->  Daughter nucleus: 24-Cr-52 [4+] 4627.13 (20) keV
The 2nd forbidden non-unique transition from the electron capture decay of Mn-52 is calculated as 1st forbidden unique

Transition energy: 84.9 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1413 (12)
PL2/PK =  6.33E-4 (22)
PL3/PK =  0.078 (7)
PM1/PK =  0.02257 (29)
PM2/PK =  9.45E-5 (38)
PM3/PK =  0.0102 (9)
PN1/PK =  0.001728 (46)
PM4/PK =  1.10E-6 (7)

L/K =  0.220 (8)
M/K =  0.0329 (12)
N/K =  0.001728 (46)


------------------------------
Relative capture probabilities

PK  =  0.797 (6)
PL1 =  0.11263 (18)
PL2 =  5.05E-4 (14)
PL3 =  0.0621 (48)
PM1 =  0.01800 (10)
PM2 =  7.54E-5 (25)
PM3 =  0.0081 (7)
PN1 =  0.001378 (26)
PM4 =  8.74E-7 (48)

K =  0.797 (6)
L =  0.175 (5)
M =  0.0262 (8)
N =  0.001378 (26)


------------------------------
Capture branch from input data

Iec =   0.0027 (6) %


---------------------
Capture probabilities

PK  =  0.797 (6)
PL1  =  0.11263 (18)
PL2  =  5.05E-4 (14)
PL3  =  0.0621 (48)
PM1  =  0.01800 (10)
PM2  =  7.54E-5 (25)
PM3  =  0.0081 (7)
PN1  =  0.001378 (26)
PM4  =  8.74E-7 (48)

K =  0.797 (6)
L =  0.175 (5)
M =  0.0262 (8)
N =  0.001378 (26)


------------------------------------------------------------
Input log ft value (ec): 5.73

Log ft value (ec)    =  5.73 (11)
with log f           =  -4.527 (45)
and log partial T1/2 =  10.25 (10)

