--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52 [6+] g.s.  -->  Daughter nucleus: 24-Cr-52 [6+] 3113.883 (24) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 1598.1 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11028 (29)
PL2/PK =  5.04E-4 (14)
PM1/PK =  0.01715 (10)
PM2/PK =  7.35E-5 (24)
PN1/PK =  0.001308 (25)

L/K =  0.11078 (30)
M/K =  0.01722 (10)
N/K =  0.001308 (25)


------------------------------
Relative capture probabilities

PK  =  0.88550 (34)
PL1 =  0.09765 (22)
PL2 =  4.47E-4 (12)
PM1 =  0.01518 (8)
PM2 =  6.51E-5 (21)
PN1 =  0.001159 (22)

K =  0.88550 (34)
L =  0.09810 (23)
M =  0.01525 (9)
N =  0.001159 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  1.718 (28)
L1/b+ =  0.1895 (36)
L2/b+ =  8.66E-4 (39)
M1/b+ =  0.0295 (7)
M2/b+ =  1.26E-4 (6)
N1/b+ =  0.00225 (8)

K/b+ =  1.718 (28)
L/b+ =  0.1903 (36)
M/b+ =  0.0296 (7)
N/b+ =  0.00225 (8)

EC/b+ =  1.940 (32)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   90.8 (8) %   Iec =   59.9 (7) %   Ib+ =   30.85 (43) %
Iec      =   59.9 (7) % (input data kept)
Ib+      =   30.85 (43) % (input data kept)
Iec tot. =   90.7 (8) % (input data kept)


---------------------
Capture probabilities

PK  =  0.5843 (33)
PL1  =  0.06444 (39)
PL2  =  2.95E-4 (8)
PM1  =  0.01002 (8)
PM2  =  4.29E-5 (14)
PN1  =  7.65E-4 (15)

K =  0.5843 (33)
L =  0.06473 (40)
M =  0.01006 (8)
N =  7.65E-4 (15)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.6

Log ft value (ec)    =  5.564 (6)
with log f           =  -0.3422 (33)
and log partial T1/2 =  5.907 (5)

