--------------------------------------------------------------------------------------

BetaShape
Version: 2.2 (05/2021)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: X. Mougeot, Applied Radiation and Isotopes 154 (2019) 108884

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52 [6+] g.s.  -->  Daughter nucleus: 24-Cr-52 [5+] 3615.946 (24) keV
Calculation of the allowed transition from the electron capture decay of Mn-52

Transition energy: 1096.1 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11061 (29)
PL2/PK =  5.02E-4 (14)
PM1/PK =  0.01720 (10)
PM2/PK =  7.32E-5 (24)
PN1/PK =  0.001313 (25)

L/K =  0.11111 (30)
M/K =  0.01728 (10)
N/K =  0.001313 (25)


------------------------------
Relative capture probabilities

PK  =  0.88519 (34)
PL1 =  0.09791 (22)
PL2 =  4.44E-4 (12)
PM1 =  0.01523 (8)
PM2 =  6.48E-5 (21)
PN1 =  0.001162 (22)

K =  0.88519 (34)
L =  0.09835 (23)
M =  0.01529 (9)
N =  0.001162 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  5.1E3 (6)
L1/b+ =  5.6E2 (7)
L2/b+ =  2.56 (41)
M1/b+ =  88 (12)
M2/b+ =  0.37 (6)
N1/b+ =  6.7 (10)

K/b+ =  5.1E3 (6)
L/b+ =  5.7E2 (7)
M/b+ =  88 (12)
N/b+ =  6.7 (10)

EC/b+ =  5.8E3 (7)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   7.67 (6) %   Iec =   7.67 (6) %   Ib+ =   0.00133 (17) %
Iec      =   7.67 (6) % (input data kept)
Ib+      =   0.00133 (17) % (input data kept)
Iec tot. =   7.67 (6) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88504 (34)
PL1  =  0.09789 (22)
PL2  =  4.44E-4 (12)
PM1  =  0.01523 (8)
PM2  =  6.48E-5 (21)
PN1  =  0.001162 (22)

K =  0.88504 (34)
L =  0.09834 (23)
M =  0.01529 (9)
N =  0.001162 (22)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.13

Log ft value (ec)    =  6.128 (5)
with log f           =  -0.6715 (37)
and log partial T1/2 =  6.7993 (34)

